export type Language = "RU" | "KZ" | "EN";

export const modules: Record<Language, string[]> = {
  RU: [
    "Введение в нейрофизиологию",
    "История и современные методы исследования нервной системы",
    "Нейрон, нейроглия и микросреда нервной ткани",
    "Мембранная физиология: потенциал покоя, ионные каналы и потенциал действия",
    "Синапсы, нейромедиаторы и нейромодуляция",
    "Возбуждение, торможение и интеграция сигналов",
    "Рефлексы и нейронные сети",
    "Проводящие пути нервной системы",
    "Спинной мозг и спинальная регуляция",
    "Ствол мозга и ретикулярная формация",
    "Двигательные системы и контроль движений",
    "Базальные ганглии и экстрапирамидная регуляция",
    "Мозжечок и координация движений",
    "Таламус и таламо-кортикальные системы",
    "Гипоталамус и гомеостаз",
    "Лимбическая система, эмоции и мотивация",
    "Миндалина, эмоциональное обучение и память",
    "Кора больших полушарий и функциональная организация",
    "Соматосенсорная система и боль",
    "Зрительная система",
    "Слуховая, вестибулярная, вкусовая и обонятельная системы",
    "Вегетативная нервная система",
    "Высшая нервная деятельность: обучение, память, речь и поведение",
    "Сон, биологические ритмы и нейрогуморальная регуляция",
    "Нейропластичность и основы патофизиологии нервной системы",
  ],
  KZ: [
    "Нейрофизиологияға кіріспе",
    "Жүйке жүйесін зерттеу тарихы және заманауи әдістері",
    "Нейрон, нейроглия және жүйке тінінің микроортасы",
    "Мембраналық физиология: тыныштық потенциалы, иондық арналар және әрекет потенциалы",
    "Синапстар, нейромедиаторлар және нейромодуляция",
    "Қозу, тежелу және сигналдарды интеграциялау",
    "Рефлекстер және нейрондық желілер",
    "Жүйке жүйесінің өткізгіш жолдары",
    "Жұлын және жұлындық реттелу",
    "Ми сабауы және ретикулярлық формация",
    "Қозғалыс жүйелері және қозғалысты басқару",
    "Базальды ганглийлер және экстрапирамидалық реттелу",
    "Мишық және қозғалыс координациясы",
    "Таламус және таламо-кортикалық жүйелер",
    "Гипоталамус және гомеостаз",
    "Лимбиялық жүйе, эмоциялар және мотивация",
    "Амигдала, эмоциялық үйрену және жад",
    "Үлкен ми сыңарларының қыртысы және функционалдық ұйымдасуы",
    "Соматосенсорлық жүйе және ауырсыну",
    "Көру жүйесі",
    "Есту, вестибулярлық, дәм және иіс сезу жүйелері",
    "Вегетативтік жүйке жүйесі",
    "Жоғары жүйке қызметі: үйрену, жад, сөйлеу және мінез-құлық",
    "Ұйқы, биологиялық ырғақтар және нейрогуморальдық реттелу",
    "Нейропластика және жүйке жүйесі патофизиологиясының негіздері",
  ],
  EN: [
    "Introduction to Neurophysiology",
    "History and Modern Methods of Nervous System Research",
    "Neurons, Neuroglia, and the Neural Microenvironment",
    "Membrane Physiology: Resting Potential, Ion Channels, and the Action Potential",
    "Synapses, Neurotransmitters, and Neuromodulation",
    "Excitation, Inhibition, and Signal Integration",
    "Reflexes and Neural Networks",
    "Neural Pathways",
    "Spinal Cord and Spinal Regulation",
    "Brainstem and Reticular Formation",
    "Motor Systems and Motor Control",
    "Basal Ganglia and Extrapyramidal Regulation",
    "Cerebellum and Motor Coordination",
    "Thalamus and Thalamocortical Systems",
    "Hypothalamus and Homeostasis",
    "Limbic System, Emotion, and Motivation",
    "Amygdala, Emotional Learning, and Memory",
    "Cerebral Cortex and Functional Organization",
    "Somatosensory System and Pain",
    "Visual System",
    "Auditory, Vestibular, Gustatory, and Olfactory Systems",
    "Autonomic Nervous System",
    "Higher Nervous Activity: Learning, Memory, Language, and Behavior",
    "Sleep, Biological Rhythms, and Neurohumoral Regulation",
    "Neuroplasticity and Foundations of Nervous System Pathophysiology",
  ],
};

export const MODULE_COUNT = modules.RU.length;

export function isModuleId(id: string): boolean {
  const number = Number(id);
  return Number.isInteger(number) && number >= 1 && number <= MODULE_COUNT && String(number) === id;
}
