import type { Language } from "./course";
import { modules } from "./course";
import { topics, termDefinitions } from "./course-foundation/topics";
import { clinicalVignettes } from "./course-foundation/assessment";
export type ExamBankQuestion={id:string;moduleId:number;moduleTitle:string;prompt:string;options:{id:string;text:string}[];correctAnswer:string;explanation:string};
const S={
RU:{st:["Какое утверждение наиболее точно описывает физиологическую связь в этой теме?","Какой вывод лучше всего следует из физиологического принципа?","Как следует интерпретировать изменение одного звена системы?","Какой вариант лучше сохраняет причинно-следственную логику механизма?","Какое рассуждение корректно при переносе механизма в новую ситуацию?","Какой подход позволяет избежать преждевременного клинического вывода?","Какое утверждение лучше различает механизм и наблюдаемый результат?","Какой вывод учитывает ограничения физиологической интерпретации?","Как следует проверить предполагаемую связь элементов системы?","Какой вариант корректно описывает направление физиологического анализа?"],pair:"Рассмотрите связь",first:"Сначала определить физиологическую роль обоих элементов, затем установить причинное направление и проверить его в данных.",swap:"Считать элементы взаимозаменяемыми и не определять направление связи.",abs:"Считать, что изменение первого элемента всегда одинаково меняет второй независимо от состояния системы.",dx:"Сделать окончательный диагноз по одному изменению без проверки альтернатив.",ex:"Корректный ответ сохраняет различие элементов, причинное направление и ограничения интерпретации."},
EN:{st:["Which statement most accurately describes the physiological relationship in this topic?","Which conclusion best follows from the physiological principle?","How should a change in one link of the system be interpreted?","Which option best preserves the causal logic of the mechanism?","Which reasoning best transfers the mechanism to a new situation?","Which approach avoids a premature clinical conclusion?","Which statement best distinguishes mechanism from observed outcome?","Which conclusion accounts for limits of physiological interpretation?","How should a proposed relationship between system elements be tested?","Which option best describes the direction of physiological analysis?"],pair:"Consider the relationship",first:"First establish the physiological roles of both elements, then determine causal direction and test it against the evidence.",swap:"Treat the elements as interchangeable without determining the direction of the relationship.",abs:"Assume a change in the first element always changes the second identically regardless of system state.",dx:"Make a definitive diagnosis from one change without checking alternatives.",ex:"A sound answer preserves distinct elements, causal direction, and limits of interpretation."},
KZ:{st:["Осы тақырыптағы физиологиялық байланысты қай тұжырым ең дәл сипаттайды?","Физиологиялық қағидадан қай қорытынды дұрыс шығады?","Жүйенің бір буыны өзгергенде оны қалай түсіндіру керек?","Қай нұсқа механизмнің себеп-салдар логикасын дұрыс сақтайды?","Механизмді жаңа жағдайға көшіруде қай пайымдау дұрыс?","Қай тәсіл ерте клиникалық қорытындыдан сақтайды?","Қай тұжырым механизм мен бақыланатын нәтижені жақсы ажыратады?","Қай қорытынды физиологиялық түсіндіру шектеулерін ескереді?","Жүйе элементтері арасындағы болжамды байланысты қалай тексеру керек?","Қай нұсқа физиологиялық талдау бағытын дұрыс сипаттайды?"],pair:"Байланысты қарастырыңыз",first:"Алдымен екі элементтің физиологиялық рөлін анықтап, кейін себептік бағытты белгілеп, оны деректермен тексеру керек.",swap:"Элементтерді өзара алмастырылатын деп санап, байланыс бағытын анықтамау.",abs:"Бірінші элемент өзгерсе, жүйе күйіне қарамастан екіншісі әрқашан бірдей өзгереді деп санау.",dx:"Бір өзгеріс бойынша баламаларды тексермей түпкілікті диагноз жасау.",ex:"Дұрыс жауап элементтер айырмасын, себептік бағытты және түсіндіру шектеулерін сақтайды."}
};
function rot<T>(a:T[],n:number){const k=n%a.length;return [...a.slice(k),...a.slice(0,k)]}
function make(mid:number,title:string,n:number,prompt:string,correct:string,wrong:string[],explanation:string):ExamBankQuestion{const raw=rot([{k:"ok",text:correct},...wrong.map((text,i)=>({k:"w"+i,text}))],n);const options=raw.map((o,i)=>({id:"abcd"[i],text:o.text}));return{id:"exam-m"+mid+"-q"+(n+1),moduleId:mid,moduleTitle:title,prompt,options,correctAnswer:options[raw.findIndex(o=>o.k==="ok")].id,explanation}}
function firstModule(lang:Language){const s=S[lang],title=modules[lang][0],a=lang==="RU"?"афферентный вход":lang==="EN"?"afferent input":"афференттік кіріс",b=lang==="RU"?"центральная интеграция":lang==="EN"?"central integration":"орталық интеграция";return Array.from({length:20},(_,n)=>make(1,title,n,s.st[n%10]+" "+s.pair+" «"+a+" → "+b+"».",s.first,[s.swap,s.abs,s.dx],s.ex))}
export function createExamBank(lang:Language):ExamBankQuestion[]{const s=S[lang],bank=[...firstModule(lang)];for(const topic of topics){const defs=termDefinitions[topic.id];if(!defs)continue;const title=modules[lang][topic.id-1],a=topic.terms[0][lang],b=topic.terms[1][lang];for(let n=0;n<20;n++){const mode=n%4;const clinical=clinicalVignettes[topic.id]?.[lang] ?? topic.task[lang];const context=mode===0?topic.question[lang]:mode===1?topic.mechanism[lang]:mode===2?clinical:topic.interpretation[lang];const correct=mode===0?topic.mechanism[lang]:mode===1?topic.interpretation[lang]:mode===2?topic.mechanism[lang]:topic.interpretation[lang];bank.push(make(topic.id,title,n,context,correct,[s.swap,s.abs,s.dx],s.ex+" "+(mode===3?topic.interpretation[lang]:topic.mechanism[lang])))} }return bank}
