import type {Language} from "../content/course";
type R={file:string;page:string;credit:string;alt:Record<Language,string>};
const refs:Record<number,R[]>={
4:[{file:"Action_Potential.gif",page:"https://commons.wikimedia.org/wiki/File:Action_Potential.gif",credit:"Laurentaylorj / Wikimedia Commons — CC BY-SA 3.0",alt:{RU:"Динамическая анимация распространения потенциала действия с деполяризацией и реполяризацией мембраны",EN:"Animated propagation of an action potential showing membrane depolarization and repolarization",KZ:"Мембрана деполяризациясы мен реполяризациясын көрсететін әрекет потенциалының динамикалық таралуы"}}],
7:[{file:"Imgnotra%C3%A7at_arc_reflex_eng.svg",page:"https://commons.wikimedia.org/wiki/File:Imgnotra%C3%A7at_arc_reflex_eng.svg",credit:"Wikimedia Commons — open educational diagram",alt:{RU:"Рефлекторная дуга: афферентный вход, спинальная интеграция и эфферентный выход к мышце",EN:"Reflex arc showing afferent input, spinal integration, and efferent output to muscle",KZ:"Афференттік кіріс, жұлындық интеграция және бұлшықетке эфференттік шығуды көрсететін рефлекторлық доға"}}],
10:[{file:"Brain_stem_sagittal_section.svg",page:"https://commons.wikimedia.org/wiki/File:Brain_stem_sagittal_section.svg",credit:"Patrick J. Lynch / Wikimedia Commons — CC BY 2.5",alt:{RU:"Сагиттальная анатомия ствола мозга с ядрами лицевого и отводящего нервов",EN:"Sagittal brainstem anatomy showing facial and abducens nuclei",KZ:"Бет және әкеткіш нерв ядролары көрсетілген ми бағанының сагитталдық анатомиясы"}}],
18:[{file:"1605_Brocas_and_Wernickes_Areas-02.jpg",page:"https://commons.wikimedia.org/wiki/File:1605_Brocas_and_Wernickes_Areas-02.jpg",credit:"OpenStax College / Wikimedia Commons",alt:{RU:"Зоны Брока и Вернике и связь между ними в доминантном полушарии",EN:"Broca and Wernicke language areas and their connection in the dominant hemisphere",KZ:"Доминантты жартышардағы Брока және Вернике аймақтары және олардың байланысы"}}],
21:[{file:"Cochlea_and_vestibular_system.gif",page:"https://commons.wikimedia.org/wiki/File:Cochlea_and_vestibular_system.gif",credit:"Nevit Dilmen / Wikimedia Commons — open licence",alt:{RU:"Динамическая 3D-анатомия улитки и вестибулярного аппарата",EN:"Dynamic 3D anatomy of the cochlea and vestibular apparatus",KZ:"Ұлу мен вестибулярлық аппараттың динамикалық 3D анатомиясы"}}],
22:[{file:"1503_Connections_of_the_Parasympathetic_Nervous_System.jpg",page:"https://commons.wikimedia.org/wiki/File:1503_Connections_of_the_Parasympathetic_Nervous_System.jpg",credit:"OpenStax College / Wikimedia Commons",alt:{RU:"Парасимпатические связи вегетативной нервной системы",EN:"Parasympathetic connections of the autonomic nervous system",KZ:"Вегетативтік жүйке жүйесінің парасимпатикалық байланыстары"}}],
23:[{file:"Hippocampus.png",page:"https://commons.wikimedia.org/wiki/File:Hippocampus.png",credit:"Wikimedia Commons — public domain",alt:{RU:"Положение гиппокампа в головном мозге",EN:"Location of the hippocampus in the human brain",KZ:"Адам миындағы гиппокамптың орналасуы"}},{file:"Hippocampus_sagittal_sections.gif",page:"https://commons.wikimedia.org/wiki/File:Hippocampus_sagittal_sections.gif",credit:"Danielsabinasz / Wikimedia Commons — CC BY-SA 4.0",alt:{RU:"Динамические сагиттальные МРТ-срезы мозга с выделенным гиппокампом",EN:"Animated sagittal MRI slices highlighting the hippocampus",KZ:"Гиппокамп белгіленген мидың динамикалық сагитталдық МРТ кесінділері"}}],
24:[{file:"Suprachiasmatic_nucleus.gif",page:"https://commons.wikimedia.org/wiki/File:Suprachiasmatic_nucleus.gif",credit:"BodyParts3D/DBCLS — CC BY-SA 2.1 JP",alt:{RU:"Динамическая 3D-локализация супрахиазматического ядра",EN:"Dynamic 3D location of the suprachiasmatic nucleus",KZ:"Супрахиазмалық ядроның динамикалық 3D орналасуы"}}],
25:[{file:"Changes_in_cellular_structures_related_to_neuroplasticity.png",page:"https://commons.wikimedia.org/wiki/File:Changes_in_cellular_structures_related_to_neuroplasticity.png",credit:"Wikimedia Commons — neuroplasticity cellular structures",alt:{RU:"Клеточные и синаптические изменения при нейропластичности",EN:"Cellular and synaptic changes related to neuroplasticity",KZ:"Нейропластика кезіндегі жасушалық және синапстық өзгерістер"}}]};
export default function AdvancedAnatomyReference({moduleId,language}:{moduleId:number;language:Language}){const rs=refs[moduleId];if(!rs)return null;return <div style={{display:"grid",gap:14,margin:"18px 0"}}>{rs.map(r=><figure key={r.file} style={{margin:0,padding:12,border:"1px solid #d9e3e8",borderRadius:14}}><img src={`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(r.file)}`} alt={r.alt[language]} loading="lazy" style={{display:"block",width:"100%",maxHeight:430,objectFit:"contain",background:"#fff"}}/><figcaption style={{fontSize:".85rem",marginTop:8}}>{r.alt[language]}. <a href={r.page} target="_blank" rel="noopener noreferrer">{r.credit}</a></figcaption></figure>)}</div>}