"use client";

import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import {recordOutcome} from "../lib/courseProgress";

type Node={id:string;labels:Record<Language,string>;kind:"receptor"|"nerve"|"cns"|"neuron"|"muscle"|"organ"|"process"};
type Link={from:string;to:string;type:"excite"|"inhibit"};
type Spec={nodes:Node[];links:Link[];lesion:string};

const L=(RU:string,EN:string,KZ:string)=>({RU,EN,KZ});
const N=(id:string,RU:string,EN:string,KZ:string,kind:Node["kind"]="cns"):Node=>({id,labels:L(RU,EN,KZ),kind});
const chain=(nodes:Node[],lesion:string,types:("excite"|"inhibit")[]=[])=>({nodes,lesion,links:nodes.slice(0,-1).map((n,i)=>({from:n.id,to:nodes[i+1].id,type:types[i]??"excite"}))});
const specs:Record<number,Spec>={
1:chain([N("stim","Стимул","Stimulus","Стимул","process"),N("receptor","Рецептор","Receptor","Рецептор","receptor"),N("afferent","Афферентный нейрон","Afferent neuron","Афференттік нейрон","nerve"),N("cns","ЦНС: интеграция","CNS integration","ОЖЖ: интеграция"),N("efferent","Эфферентный нейрон","Efferent neuron","Эфференттік нейрон","nerve"),N("effector","Эффектор","Effector","Эффектор","organ")],"afferent"),
2:chain([N("stim","Физиологический сигнал","Physiological signal","Физиологиялық сигнал","process"),N("sensor","Датчик / электроды","Sensor / electrodes","Датчик / электродтар","receptor"),N("amp","Усилитель","Amplifier","Күшейткіш","process"),N("record","Регистрация сигнала","Signal recording","Сигналды тіркеу","process"),N("analysis","Физиологическая интерпретация","Physiological interpretation","Физиологиялық түсіндіру","process")],"sensor"),
3:chain([N("dend","Дендриты","Dendrites","Дендриттер","neuron"),N("soma","Тело нейрона","Soma","Нейрон денесі","neuron"),N("ais","Начальный сегмент аксона","Axon initial segment","Аксонның бастапқы сегменті","neuron"),N("axon","Миелинизированный аксон","Myelinated axon","Миелинді аксон","nerve"),N("terminal","Аксонное окончание","Axon terminal","Аксон ұшы","neuron")],"axon"),
4:chain([N("rest","Потенциал покоя","Resting potential","Тыныштық потенциалы","process"),N("threshold","Порог","Threshold","Табалдырық","process"),N("na","Открытие Na⁺-каналов","Na⁺ channels open","Na⁺ арналары ашылады","process"),N("depol","Деполяризация","Depolarization","Деполяризация","process"),N("k","Открытие K⁺-каналов","K⁺ channels open","K⁺ арналары ашылады","process"),N("repol","Реполяризация","Repolarization","Реполяризация","process")],"na"),
5:chain([N("ap","ПД пресинаптического окончания","Presynaptic action potential","Пресинапстық әрекет потенциалы","process"),N("ca","Ca²⁺-каналы","Ca²⁺ channels","Ca²⁺ арналары","process"),N("ves","Слияние везикул","Vesicle fusion","Везикулалардың қосылуы","process"),N("nt","Нейромедиатор","Neurotransmitter","Нейромедиатор","process"),N("rec","Постсинаптический рецептор","Postsynaptic receptor","Постсинапстық рецептор","receptor"),N("psp","Постсинаптический потенциал","Postsynaptic potential","Постсинапстық потенциал","process")],"ca"),
6:chain([N("epsp","Возбуждающие входы","Excitatory inputs","Қоздырушы кірістер","process"),N("soma","Сома и дендриты","Soma and dendrites","Сома және дендриттер","neuron"),N("ais","Аксонный холмик / начальный сегмент","Axon hillock / initial segment","Аксон төмпешігі / бастапқы сегмент","neuron"),N("ap","Потенциал действия","Action potential","Әрекет потенциалы","process")],"soma"),
7:{nodes:[N("spindle","Мышечное веретено","Muscle spindle","Бұлшықет ұршығы","receptor"),N("ia","Ia-афферент","Ia afferent","Ia-афферент","nerve"),N("alpha","α-мотонейрон мышцы","α-motor neuron","Бұлшықет α-мотонейроны","neuron"),N("muscle","Растянутая мышца","Stretched muscle","Созылған бұлшықет","muscle"),N("inter","Тормозный интернейрон","Inhibitory interneuron","Тежегіш интернейрон","neuron"),N("antalpha","α-мотонейрон антагониста","Antagonist α-motor neuron","Антагонист α-мотонейроны","neuron"),N("ant","Мышца-антагонист","Antagonist muscle","Антагонист бұлшықет","muscle")],links:[{from:"spindle",to:"ia",type:"excite"},{from:"ia",to:"alpha",type:"excite"},{from:"alpha",to:"muscle",type:"excite"},{from:"ia",to:"inter",type:"excite"},{from:"inter",to:"antalpha",type:"inhibit"},{from:"antalpha",to:"ant",type:"excite"}],lesion:"ia"},
8:chain([N("receptor","Проприорецептор","Proprioceptor","Проприорецептор","receptor"),N("first","Первичный афферент","Primary afferent","Біріншілік афферент","nerve"),N("cord","Задние столбы","Dorsal columns","Артқы бағандар","nerve"),N("medulla","Ядра задних столбов","Dorsal-column nuclei","Артқы баған ядролары"),N("cross","Перекрёст в продолговатом мозге","Medullary decussation","Сопақша мидағы айқас"),N("thalamus","Таламус VPL","VPL thalamus","Таламус VPL"),N("cortex","Соматосенсорная кора","Somatosensory cortex","Соматосенсорлық қыртыс")],"cross"),
9:chain([N("spindle","Мышечное веретено","Muscle spindle","Бұлшықет ұршығы","receptor"),N("droot","Задний корешок","Dorsal root","Артқы түбір","nerve"),N("cord","Сегментарная сеть спинного мозга","Spinal segmental network","Жұлынның сегменттік желісі"),N("vroot","Передний корешок","Ventral root","Алдыңғы түбір","nerve"),N("muscle","Скелетная мышца","Skeletal muscle","Қаңқа бұлшықеті","muscle")],"droot"),
10:chain([N("sensory","Сенсорный вход","Sensory input","Сенсорлық кіріс","nerve"),N("brainstem","Стволовые сети","Brainstem networks","Ми сабауы желілері"),N("reticular","Ретикулярная формация","Reticular formation","Ретикулярлық формация"),N("thalamus","Таламо-кортикальная активация","Thalamocortical activation","Таламо-қыртыстық белсендіру"),N("arousal","Бодрствование","Arousal","Сергектік","process")],"reticular"),
11:chain([N("premotor","Премоторная кора","Premotor cortex","Премоторлық қыртыс"),N("m1","Первичная моторная кора","Primary motor cortex","Біріншілік моторлық қыртыс"),N("cst","Кортикоспинальный путь","Corticospinal tract","Кортикоспиналдық жол","nerve"),N("alpha","α-мотонейрон","α-motor neuron","α-мотонейрон","neuron"),N("muscle","Скелетная мышца","Skeletal muscle","Қаңқа бұлшықеті","muscle")],"cst"),
12:chain([N("cortex","Кора","Cortex","Қыртыс"),N("striatum","Стриатум","Striatum","Стриатум"),N("gpi","GPi/SNr","GPi/SNr","GPi/SNr"),N("thalamus","Таламус","Thalamus","Таламус"),N("motor","Моторная кора","Motor cortex","Моторлық қыртыс")],"striatum",["excite","inhibit","inhibit","excite"]),
13:chain([N("cortex","Моторная кора","Motor cortex","Моторлық қыртыс"),N("pons","Ядра моста","Pontine nuclei","Көпір ядролары"),N("cerebellum","Кора мозжечка","Cerebellar cortex","Мишық қыртысы"),N("deep","Глубокие ядра мозжечка","Deep cerebellar nuclei","Мишықтың терең ядролары"),N("thalamus","Таламус","Thalamus","Таламус"),N("motor","Моторная кора: коррекция","Motor cortex: correction","Моторлық қыртыс: түзету")],"cerebellum"),
14:chain([N("sensory","Сенсорный путь","Sensory pathway","Сенсорлық жол","nerve"),N("relay","Специфическое ядро таламуса","Specific thalamic nucleus","Таламустың арнайы ядросы"),N("cortex","Первичная сенсорная кора","Primary sensory cortex","Біріншілік сенсорлық қыртыс"),N("association","Ассоциативная кора","Association cortex","Ассоциативтік қыртыс")],"relay"),
15:chain([N("osmo","Осморецепторы","Osmoreceptors","Осморецепторлар","receptor"),N("hypo","Гипоталамус","Hypothalamus","Гипоталамус"),N("adh","Вазопрессиновый выход","Vasopressin output","Вазопрессиндік шығу","process"),N("kidney","Почка","Kidney","Бүйрек","organ"),N("water","Сохранение воды","Water conservation","Суды сақтау","process")],"hypo"),
16:chain([N("sensory","Сенсорный контекст","Sensory context","Сенсорлық контекст","process"),N("hipp","Гиппокамп","Hippocampus","Гиппокамп"),N("amyg","Миндалина","Amygdala","Амигдала"),N("hypo","Гипоталамус","Hypothalamus","Гипоталамус"),N("response","Вегетативно-поведенческий ответ","Autonomic-behavioral response","Вегетативтік-мінез-құлық жауабы","process")],"amyg"),
17:chain([N("cue","Эмоционально значимый стимул","Emotionally salient cue","Эмоциялық маңызды стимул","process"),N("thalamus","Таламус","Thalamus","Таламус"),N("amyg","Миндалина","Amygdala","Амигдала"),N("hypo","Гипоталамус/ствол","Hypothalamus/brainstem","Гипоталамус/ми сабауы"),N("response","Вегетативная реакция","Autonomic response","Вегетативтік реакция","process")],"amyg"),
18:chain([N("sensory","Сенсорная кора","Sensory cortex","Сенсорлық қыртыс"),N("association","Ассоциативная кора","Association cortex","Ассоциативтік қыртыс"),N("prefrontal","Префронтальная кора","Prefrontal cortex","Префронталдық қыртыс"),N("premotor","Премоторная кора","Premotor cortex","Премоторлық қыртыс"),N("motor","Моторная кора","Motor cortex","Моторлық қыртыс")],"association"),
19:chain([N("receptor","Кожный рецептор","Cutaneous receptor","Тері рецепторы","receptor"),N("afferent","Первичный афферент","Primary afferent","Біріншілік афферент","nerve"),N("cord","Спинной мозг","Spinal cord","Жұлын"),N("thalamus","Таламус","Thalamus","Таламус"),N("s1","Первичная соматосенсорная кора","Primary somatosensory cortex","Біріншілік соматосенсорлық қыртыс")],"afferent"),
20:chain([N("retina","Сетчатка","Retina","Торқабық","receptor"),N("optic","Зрительный нерв","Optic nerve","Көру нерві","nerve"),N("chiasm","Хиазма","Optic chiasm","Хиазма","nerve"),N("lgn","Латеральное коленчатое тело","Lateral geniculate nucleus","Латералдық тізелі дене"),N("radiation","Зрительная лучистость","Optic radiation","Көру сәулеленуі","nerve"),N("v1","Первичная зрительная кора","Primary visual cortex","Біріншілік көру қыртысы")],"chiasm"),
21:chain([N("hair","Вестибулярные волосковые клетки","Vestibular hair cells","Вестибулярлық түкті жасушалар","receptor"),N("viii","Вестибулярный нерв VIII","Vestibular nerve VIII","VIII вестибулярлық нерв","nerve"),N("nuclei","Вестибулярные ядра","Vestibular nuclei","Вестибулярлық ядролар"),N("mlf","Медиальный продольный пучок","Medial longitudinal fasciculus","Медиалдық бойлық шоғыр","nerve"),N("ocular","Глазодвигательные ядра","Ocular motor nuclei","Көз қимылдатқыш ядролар"),N("eyes","Компенсаторное движение глаз","Compensatory eye movement","Көздің компенсаторлық қозғалысы","process")],"viii"),
22:chain([N("baro","Барорецептор","Baroreceptor","Барорецептор","receptor"),N("afferent","IX/X афференты","CN IX/X afferents","IX/X афференттері","nerve"),N("nts","Ядро одиночного пути","Nucleus tractus solitarius","Жалғыз жол ядросы"),N("pregang","Преганглионарный нейрон","Preganglionic neuron","Преганглионарлық нейрон","neuron"),N("ganglion","Вегетативный ганглий","Autonomic ganglion","Вегетативтік ганглий"),N("heart","Сердце/сосуды","Heart/vessels","Жүрек/тамырлар","organ")],"afferent"),
23:chain([N("input","Учебный стимул","Learning input","Оқу стимулы","process"),N("hipp","Гиппокамп","Hippocampus","Гиппокамп"),N("cortex","Распределённые корковые сети","Distributed cortical networks","Таралған қыртыстық желілер"),N("retrieval","Извлечение","Retrieval","Қайта жаңғырту","process"),N("response","Поведенческий ответ","Behavioral response","Мінез-құлық жауабы","process")],"hipp"),
24:chain([N("light","Свет","Light","Жарық","process"),N("retina","Сетчатка","Retina","Торқабық","receptor"),N("rht","Ретино-гипоталамический путь","Retinohypothalamic tract","Ретино-гипоталамустық жол","nerve"),N("scn","Супрахиазматическое ядро","Suprachiasmatic nucleus","Супрахиазмалық ядро"),N("pineal","Эпифиз / мелатониновый сигнал","Pineal / melatonin signal","Эпифиз / мелатонин сигналы","organ"),N("sleep","Циркадная организация сна","Circadian sleep organization","Ұйқының циркадтық ұйымдасуы","process")],"scn"),
25:chain([N("activity","Повторная активность","Repeated activity","Қайталанатын белсенділік","process"),N("nmda","NMDA-рецептор","NMDA receptor","NMDA-рецептор","receptor"),N("ca","Постсинаптический Ca²⁺","Postsynaptic Ca²⁺","Постсинапстық Ca²⁺","process"),N("plastic","Изменение силы синапса","Synaptic strength change","Синапс күшінің өзгеруі","process"),N("network","Перестройка сети","Network reorganization","Желінің қайта құрылуы","process"),N("function","Изменение функции","Functional change","Функцияның өзгеруі","process")],"nmda")
};

const C={RU:{title:"Анатомо-физиологический конструктор",intro:"Соберите путь из реальных анатомических и физиологических звеньев. Выберите следующий элемент и тип связи.",excite:"→ возбуждение / передача",inhibit:"┤ торможение",check:"Проверить схему",reset:"Сначала",good:"Связи собраны правильно. Это засчитывается как применение знания.",bad:"Есть ошибка в структуре, направлении или типе связи. Исправьте схему.",lesion:"Проверка нарушения",lesionQ:"Если указанное звено повреждено, где впервые прервётся нормальная передача?",choose:"Выберите звено",lesionGood:"Верно: вы локализовали место нарушения.",lesionBad:"Проверьте, какое звено находится непосредственно после повреждения."},EN:{title:"Anatomy–physiology pathway builder",intro:"Build the pathway from anatomical and physiological elements. Choose the next structure and the connection type.",excite:"→ excitation / transmission",inhibit:"┤ inhibition",check:"Check pathway",reset:"Reset",good:"The pathway and connections are correct. This counts as application evidence.",bad:"A structure, direction, or connection type is incorrect. Revise the pathway.",lesion:"Lesion challenge",lesionQ:"If the indicated element is damaged, where is normal transmission first interrupted?",choose:"Choose element",lesionGood:"Correct: you localized the interruption.",lesionBad:"Check which element lies immediately after the damaged link."},KZ:{title:"Анатомиялық-физиологиялық конструктор",intro:"Анатомиялық және физиологиялық буындардан жолды құрастырыңыз. Келесі құрылым мен байланыс түрін таңдаңыз.",excite:"→ қозу / берілу",inhibit:"┤ тежелу",check:"Сызбаны тексеру",reset:"Басынан",good:"Жол мен байланыстар дұрыс. Бұл білімді қолдану дәлелі ретінде есептеледі.",bad:"Құрылымда, бағытта немесе байланыс түрінде қате бар. Сызбаны түзетіңіз.",lesion:"Зақым сынағы",lesionQ:"Көрсетілген буын зақымдалса, қалыпты берілу алғаш қай жерде үзіледі?",choose:"Буын таңдаңыз",lesionGood:"Дұрыс: үзілу орнын анықтадыңыз.",lesionBad:"Зақымдалған буыннан кейін қай құрылым орналасқанын тексеріңіз."}} as const;

export default function AnatomyPhysiologyBuilder({moduleId,language}:{moduleId:number;language:Language}){
 const spec=specs[moduleId]; const t=C[language]; const [links,setLinks]=useState<Link[]>([]); const [from,setFrom]=useState(""); const [type,setType]=useState<"excite"|"inhibit">("excite"); const [checked,setChecked]=useState(false); const [lesionAnswer,setLesionAnswer]=useState("");
 const expectedAfter=useMemo(()=>spec?.links.find(x=>x.from===spec.lesion)?.to??"",[spec]);
 if(!spec)return null;
 const add=(to:string)=>{if(!from||from===to)return;setLinks(v=>[...v.filter(x=>!(x.from===from&&x.to===to)),{from,to,type}]);setFrom("");setChecked(false)};
 const good=links.length===spec.links.length&&spec.links.every(e=>links.some(x=>x.from===e.from&&x.to===e.to&&x.type===e.type));
 return <section style={{margin:"24px 0",padding:"clamp(14px,3vw,22px)",border:"1px solid #bfd5e2",borderRadius:18,background:"#fafdff"}}>
  <h2 style={{marginTop:0}}>{t.title}</h2><p>{t.intro}</p>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}>
   {spec.nodes.map(n=><button key={n.id} type="button" aria-pressed={from===n.id} onClick={()=>from?add(n.id):setFrom(n.id)} style={{minHeight:76,padding:10,borderRadius:14,fontWeight:700}}><span aria-hidden="true" style={{display:"block",fontSize:24}}>{n.kind==="receptor"?"◉":n.kind==="nerve"?"〰":n.kind==="cns"?"🧠":n.kind==="neuron"?"⌁":n.kind==="muscle"?"▰":n.kind==="organ"?"⬡":"◎"}</span>{n.labels[language]}</button>)}
  </div>
  <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><button type="button" aria-pressed={type==="excite"} onClick={()=>setType("excite")}>{t.excite}</button><button type="button" aria-pressed={type==="inhibit"} onClick={()=>setType("inhibit")}>{t.inhibit}</button></div>
  <ol>{links.map((x,i)=><li key={i}>{spec.nodes.find(n=>n.id===x.from)?.labels[language]} {x.type==="inhibit"?" ┤ ":" → "} {spec.nodes.find(n=>n.id===x.to)?.labels[language]}</li>)}</ol>
  <div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" disabled={!links.length} onClick={()=>{setLinks([]);setFrom("");setChecked(false);setLesionAnswer("")}}>{t.reset}</button><button type="button" disabled={!links.length} onClick={()=>{setChecked(true);recordOutcome(moduleId,"criterion:application:anatomy-builder",good?1:0,1)}}>{t.check}</button></div>
  {checked&&<p role="status"><strong>{good?t.good:t.bad}</strong></p>}
  {good&&<div style={{marginTop:18,padding:14,border:"1px solid #d7e5ed",borderRadius:14}}><h3>{t.lesion}</h3><p>{t.lesionQ}</p><p><strong>{spec.nodes.find(n=>n.id===spec.lesion)?.labels[language]}</strong></p><select value={lesionAnswer} onChange={e=>{const v=e.target.value;setLesionAnswer(v);if(v)recordOutcome(moduleId,"criterion:transfer:anatomy-builder",v===expectedAfter?1:0,1)}}><option value="">{t.choose}</option>{spec.nodes.filter(n=>n.id!==spec.lesion).map(n=><option key={n.id} value={n.id}>{n.labels[language]}</option>)}</select>{lesionAnswer&&<p><strong>{lesionAnswer===expectedAfter?t.lesionGood:t.lesionBad}</strong></p>}</div>}
 </section>;
}
