"use client";
import {useEffect,useMemo,useState} from "react";
import type {Language} from "../content/course";
import {baroreflexMechanism,baroreflexModes,type Direction} from "../content/baroreflex-lab";
import {recordOutcome} from "../lib/courseProgress";
import {isMeaningfulResponse} from "../lib/meaningfulResponse";
import styles from "./AutonomicLab.module.css";

const C={
RU:{title:"Виртуальная ортостатическая проба",intro:"Учебная физиологическая модель: значения не принадлежат реальному пациенту и не предназначены для диагностики.",mode:"Режим эксперимента",baseline:"1. Исходное состояние лёжа",record:"Зафиксировать baseline",recorded:"Baseline зафиксирован",prediction:"2. Прогноз до пробы",question:"Что изменится сразу после перехода в положение стоя?",hr:"ЧСС",sbp:"Систолическое АД",dbp:"Диастолическое АД",map:"Среднее АД",up:"Повысится",down:"Снизится",same:"Без изменения",stand:"3. Перейти в положение стоя",need:"Сначала зафиксируйте baseline и выберите прогноз для всех трёх показателей.",play:"Продолжить",pause:"Пауза",replay:"Повторить",reset:"Сбросить",graph:"Динамика во времени",heart:"ЧСС",pressure:"АД",mechanism:"Активный механизм барорефлекса",your:"Ваш прогноз",observed:"Наблюдаемый результат",correct:"Совпало",revise:"Требует пересмотра",interpret:"4. Физиологическая интерпретация",prompt:"Почему ЧСС изменяется раньше, чем система достигает нового устойчивого состояния? Свяжите венозный возврат, барорецепторы и автономные влияния.",finish:"Сохранить вывод",done:"Эксперимент завершён и учтён в прогрессе модуля.",supine:"Лёжа",standing:"Стоя",seconds:"с"},
EN:{title:"Virtual orthostatic challenge",intro:"Teaching physiology model: values do not belong to a real patient and are not intended for diagnosis.",mode:"Experiment mode",baseline:"1. Supine baseline",record:"Record baseline",recorded:"Baseline recorded",prediction:"2. Predict before the challenge",question:"What changes immediately after moving to standing?",hr:"Heart rate",sbp:"Systolic BP",dbp:"Diastolic BP",map:"Mean BP",up:"Increase",down:"Decrease",same:"No change",stand:"3. Move to standing",need:"Record baseline and predict all three variables first.",play:"Continue",pause:"Pause",replay:"Replay",reset:"Reset",graph:"Time course",heart:"Heart rate",pressure:"Blood pressure",mechanism:"Active baroreflex mechanism",your:"Your prediction",observed:"Observed result",correct:"Matched",revise:"Review needed",interpret:"4. Physiological interpretation",prompt:"Why does heart rate change before the system reaches a new steady state? Link venous return, baroreceptors and autonomic drive.",finish:"Save conclusion",done:"Experiment completed and recorded in module progress.",supine:"Supine",standing:"Standing",seconds:"s"},
KZ:{title:"Виртуалды ортостатикалық сынама",intro:"Оқу физиологиялық моделі: мәндер нақты пациентке тиесілі емес және диагноз қоюға арналмаған.",mode:"Тәжірибе режимі",baseline:"1. Жатқандағы бастапқы күй",record:"Baseline тіркеу",recorded:"Baseline тіркелді",prediction:"2. Сынамаға дейінгі болжам",question:"Тік қалыпқа ауысқаннан кейін бірден не өзгереді?",hr:"ЖЖЖ",sbp:"Систолалық АҚ",dbp:"Диастолалық АҚ",map:"Орташа АҚ",up:"Жоғарылайды",down:"Төмендейді",same:"Өзгермейді",stand:"3. Тік қалыпқа ауысу",need:"Алдымен baseline тіркеп, үш көрсеткішке де болжам таңдаңыз.",play:"Жалғастыру",pause:"Кідірту",replay:"Қайталау",reset:"Қалпына келтіру",graph:"Уақыт бойынша динамика",heart:"ЖЖЖ",pressure:"Артериялық қысым",mechanism:"Барорефлекстің белсенді механизмі",your:"Сіздің болжамыңыз",observed:"Бақыланған нәтиже",correct:"Сәйкес келді",revise:"Қайта қарау қажет",interpret:"4. Физиологиялық түсіндіру",prompt:"Неліктен ЖЖЖ жүйе жаңа тұрақты күйге жеткенге дейін өзгереді? Веналық қайтуды, барорецепторларды және автономдық ықпалды байланыстырыңыз.",finish:"Қорытындыны сақтау",done:"Тәжірибе аяқталды және модуль прогресіне енгізілді.",supine:"Жатқан",standing:"Тік тұрған",seconds:"с"}} as const;
type Metric="hr"|"bp";type Variable="hr"|"sbp"|"dbp";
const directions:Direction[]=["up","down","same"];
const mean=(sbp:number,dbp:number)=>Math.round((sbp+2*dbp)/3);
const y=(value:number,min:number,max:number)=>154-((value-min)/(max-min))*124;

export default function AutonomicLab({language}:{language:Language}){
 const t=C[language];const[modeId,setModeId]=useState("normal");const mode=baroreflexModes.find(x=>x.id===modeId)??baroreflexModes[0];
 const[baseline,setBaseline]=useState(false);const[prediction,setPrediction]=useState<Partial<Record<Variable,Direction>>>({});const[started,setStarted]=useState(false);const[playing,setPlaying]=useState(false);const[index,setIndex]=useState(0);const[metric,setMetric]=useState<Metric>("hr");const[explanation,setExplanation]=useState("");const[finished,setFinished]=useState(false);
 const ready=Boolean(baseline&&prediction.hr&&prediction.sbp&&prediction.dbp);const point=mode.series[index];const visible=mode.series.slice(0,index+1);const resultReady=started&&index===mode.series.length-1;
 useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setIndex(old=>{if(old>=mode.series.length-1){setPlaying(false);return old}return old+1}),700);return()=>window.clearInterval(timer)},[playing,mode.series.length]);
 const path=(key:Variable,min:number,max:number)=>visible.map((p,i)=>`${i?"L":"M"} ${28+i*64} ${y(p[key],min,max)}`).join(" ");
 const feedback=useMemo(()=>resultReady?(["hr","sbp","dbp"] as const).map(key=>({key,match:prediction[key]===mode.expected[key]})):[],[resultReady,prediction,mode]);
 function reset(next=modeId){setModeId(next);setBaseline(false);setPrediction({});setStarted(false);setPlaying(false);setIndex(0);setExplanation("");setFinished(false)}
 function run(){if(!ready)return;setStarted(true);setIndex(0);setFinished(false);if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){setIndex(mode.series.length-1);setPlaying(false)}else setPlaying(true)}
 function finish(){if(!resultReady||!isMeaningfulResponse(explanation,40,6))return;setFinished(true);recordOutcome(22,"interactive",1,1);recordOutcome(22,"criterion:application:baroreflex-lab",1,1);recordOutcome(22,"criterion:justification:baroreflex-lab",1,1)}
 return <section className={styles.lab} data-testid="baroreflex-lab"><header><div><span>Baroreflex lab</span><h2>{t.title}</h2><p>{t.intro}</p></div><div className={styles.posture} data-standing={started} aria-label={started?t.standing:t.supine}><i/><b>♥</b><small>{started?t.standing:t.supine}</small></div></header>
 <label className={styles.mode}>{t.mode}<select value={modeId} onChange={e=>reset(e.target.value)}>{baroreflexModes.map(x=><option key={x.id} value={x.id}>{x.label[language]}</option>)}</select></label>
 <section className={styles.panel}><h3>{t.baseline}</h3><Readings t={t} hr={mode.baseline.hr} sbp={mode.baseline.sbp} dbp={mode.baseline.dbp}/><button type="button" disabled={baseline} onClick={()=>setBaseline(true)}>{baseline?t.recorded:t.record}</button></section>
 <fieldset className={styles.predict}><legend>{t.prediction}</legend><p>{t.question}</p>{(["hr","sbp","dbp"] as const).map(key=><div key={key}><strong>{t[key]}</strong>{directions.map(direction=><label key={direction}><input type="radio" name={key} checked={prediction[key]===direction} onChange={()=>setPrediction(old=>({...old,[key]:direction}))}/>{t[direction]}</label>)}</div>)}</fieldset>
 <div className={styles.controls}><button type="button" disabled={!ready||playing} onClick={run}>{started?t.replay:t.stand}</button>{started&&<button type="button" disabled={resultReady} onClick={()=>setPlaying(v=>!v)}>{playing?t.pause:t.play}</button>}<button type="button" onClick={()=>reset()}>{t.reset}</button>{!ready&&<p role="status">{t.need}</p>}</div>
 {started&&<><section className={styles.dashboard}><Readings t={t} hr={point.hr} sbp={point.sbp} dbp={point.dbp}/><p className={styles.clock}>{point.time} {t.seconds}</p><div className={styles.graph}><div><h3>{t.graph}</h3><button type="button" aria-pressed={metric==="hr"} onClick={()=>setMetric("hr")}>{t.heart}</button><button type="button" aria-pressed={metric==="bp"} onClick={()=>setMetric("bp")}>{t.pressure}</button></div><svg viewBox="0 0 380 190" role="img" aria-label={t.graph}><path d="M28 12V154H356" className={styles.axis}/>{mode.series.map((p,i)=><text key={p.time} x={28+i*64} y="176" textAnchor="middle">{p.time}</text>)}{metric==="hr"?<path d={path("hr",50,115)} className={styles.hr}/>:<><path d={path("sbp",75,125)} className={styles.sbp}/><path d={path("dbp",45,85)} className={styles.dbp}/></>}</svg></div><div className={styles.mechanism}><h3>{t.mechanism}</h3><ol>{baroreflexMechanism.map((item,i)=><li key={item.EN} data-active={i===Math.min(index,5)}>{item[language]}</li>)}</ol></div></section>
 {resultReady&&<><section className={styles.feedback}><h3>{t.your} / {t.observed}</h3>{feedback.map(item=><p key={item.key}><strong>{t[item.key]}:</strong> {prediction[item.key]&&t[prediction[item.key]!]} → {t[mode.expected[item.key]]} · <b>{item.match?t.correct:t.revise}</b></p>)}</section><section className={styles.interpret}><h3>{t.interpret}</h3><label>{t.prompt}<textarea rows={5} value={explanation} onChange={e=>{setExplanation(e.target.value);setFinished(false)}}/></label><button type="button" disabled={!isMeaningfulResponse(explanation,40,6)} onClick={finish}>{t.finish}</button>{finished&&<p role="status"><strong>{t.done}</strong></p>}</section></>}
 </>}</section>
}
type Copy=(typeof C)[Language];
function Readings({t,hr,sbp,dbp}:{t:Copy;hr:number;sbp:number;dbp:number}){return <div className={styles.readings}><Value label={t.hr} value={hr} unit="/min"/><Value label={t.sbp} value={sbp} unit="mmHg"/><Value label={t.dbp} value={dbp} unit="mmHg"/><Value label={t.map} value={mean(sbp,dbp)} unit="mmHg"/></div>}
function Value({label,value,unit}:{label:string;value:number;unit:string}){return <div><span>{label}</span><strong>{value}</strong><small>{unit}</small></div>}
