"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
import {isMeaningfulResponse} from "../lib/meaningfulResponse";
import AdvancedAnatomyReference from "./AdvancedAnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Лаборатория вегетативного баланса",a:"Симпатический влияющий сигнал",b:"Парасимпатический влияющий сигнал",out:"Моделируемое влияние на частоту сердечных сокращений",predict:"Прогноз",task:"Сначала сформулируйте прогноз. Затем изменяйте только один параметр за опыт, запишите результат и объясните механизм.",save:"Записать опыт",explain:"Объяснение",limit:"Модель относится только к хронотропной регуляции сердца: усиление симпатического влияния обычно повышает, а вагусного — снижает частоту. Это нельзя переносить как единую шкалу на сосуды, ЖКТ, зрачок и другие органы; там набор рецепторов и организация автономного контроля различаются. Проценты условны и не являются клиническим измерением."},EN:{title:"Autonomic balance laboratory",a:"Sympathetic drive",b:"Parasympathetic drive",out:"Modeled influence on heart rate",predict:"Prediction",task:"Make a prediction first. Then change only one parameter per trial, record the result, and explain the mechanism.",save:"Record trial",explain:"Explanation",limit:"This model is limited to cardiac chronotropic control: stronger sympathetic drive generally raises heart rate, whereas stronger vagal drive lowers it. Do not generalize this as a single opposition scale to blood vessels, the gastrointestinal tract, pupil, or other organs; receptor expression and autonomic organization differ. Percentages are modeled, not clinical measurements."},KZ:{title:"Вегетативтік теңгерім зертханасы",a:"Симпатикалық ықпал",b:"Парасимпатикалық ықпал",out:"Жүрек жиілігіне модельденген ықпал",predict:"Болжам",task:"Алдымен болжам жасаңыз. Әр тәжірибеде тек бір параметрді өзгертіп, нәтижені жазып, механизмді түсіндіріңіз.",save:"Тәжірибені жазу",explain:"Түсіндірме",limit:"Бұл модель жүректің хронотроптық реттелуіне ғана қатысты: симпатикалық ықпалдың күшеюі әдетте жүрек жиілігін арттырады, ал вагустық ықпал төмендетеді. Мұны қан тамырларына, асқазан-ішек жолына, қарашыққа және басқа мүшелерге бір ғана қарама-қарсы шкала ретінде қолдануға болмайды; рецепторлар мен автономдық реттелу әртүрлі. Пайыздар шартты, клиникалық өлшем емес."}} as const;
function calc(a:number,b:number){return Math.max(0,Math.min(100,Math.round(50+(a-b)/2)));}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(60),[b,setB]=useState(40),[prediction,setPrediction]=useState(""),[revealed,setRevealed]=useState(false),[rows,setRows]=useState<Row[]>([]);const value=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AdvancedAnatomyReference moduleId={22} language={language}/><p><strong>{t.task}</strong></p><label>{t.predict}<textarea value={prediction} onChange={e=>{setPrediction(e.target.value);setRevealed(false)}} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a}%<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b}%<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 180" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><path d="M60 90 H250" stroke="currentColor" strokeWidth={2+a/25}/><circle cx="310" cy="90" r="42" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M352 90 H555" stroke="currentColor" strokeWidth={2+value/25}/><circle cx="600" cy="90" r={12+value/9} fill="none" stroke="currentColor" strokeWidth="3"/>{revealed&&<text x="255" y="155">{t.out}: {value}%</text>}</svg><button disabled={!isMeaningfulResponse(prediction,12,3)} onClick={()=>{setRevealed(true);recordOutcome(22,"interactive",1,1);recordOutcome(22,"criterion:application:lab",1,1);setRows(r=>[...r,{id:Date.now(),a,b,out:value,note:""}])}}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.out}</th><th>{t.explain}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}</td><td>{r.b}</td><td>{r.out}%</td><td><input value={r.note} onChange={e=>{const note=e.target.value;setRows(xs=>xs.map(q=>q.id===r.id?{...q,note}:q));if(isMeaningfulResponse(note,30,4))recordOutcome(22,"criterion:justification:lab",1,1)}}/></td></tr>)}</tbody></table></div><ExperimentReflection language={language} theoryHref={`/modules/22/theory?lang=${language}`}/><p><small>{t.limit}</small></p></section>}
