"use client";

import {useState} from "react";
import type {Language} from "../content/course";

type Entry={title:Record<Language,string>;normal:Record<Language,string>;lesion:Record<Language,string>;task:Record<Language,string>};
const E:Record<number,Entry[]>={
7:[{title:{RU:"Рефлекторная дуга",EN:"Reflex arc",KZ:"Рефлекстік доға"},normal:{RU:"Рецептор → афферент → центр → эфферент → эффектор.",EN:"Receptor → afferent → center → efferent → effector.",KZ:"Рецептор → афферент → орталық → эфферент → эффектор."},lesion:{RU:"Разрыв любого звена меняет латентность, силу или устраняет ответ.",EN:"A break at any link changes latency, response strength, or abolishes the response.",KZ:"Кез келген буынның үзілуі латенттілікті, жауап күшін өзгертеді немесе жауапты жояды."},task:{RU:"Нажмите «Поражение» и назовите, какое звено проверите первым.",EN:"Switch to Lesion and name the first link you would test.",KZ:"«Зақымдану» режимін қосып, алдымен қай буынды тексеретініңізді атаңыз."}}],
8:[{title:{RU:"Восходящие и нисходящие пути",EN:"Ascending and descending pathways",KZ:"Өрлеме және төмендеуші жолдар"},normal:{RU:"Сенсорный поток поднимается к вышележащим центрам; моторная команда идёт к спинальным исполнительным цепям.",EN:"Sensory information ascends; motor commands descend to spinal execution circuits.",KZ:"Сенсорлық ақпарат жоғары көтеріледі; моторлық команда жұлындық орындаушы тізбектерге төмендейді."},lesion:{RU:"Локализация дефицита зависит от уровня повреждения и места перекрёста пути.",EN:"The deficit depends on lesion level and where the pathway crosses.",KZ:"Тапшылық зақым деңгейіне және жолдың айқасу орнына тәуелді."},task:{RU:"Предскажите сторону сенсорного и моторного дефицита до просмотра объяснения.",EN:"Predict the side of sensory and motor deficit before viewing the explanation.",KZ:"Түсіндірмені ашпай тұрып сенсорлық және моторлық тапшылық жағын болжаңыз."}}],
9:[{title:{RU:"Спинальный шок",EN:"Spinal shock",KZ:"Жұлындық шок"},normal:{RU:"Нисходящие влияния регулируют возбудимость сегментарных рефлекторных сетей.",EN:"Descending influences regulate excitability of segmental reflex networks.",KZ:"Төмендеуші әсерлер сегменттік рефлекстік желілердің қозғыштығын реттейді."},lesion:{RU:"После острого повреждения рефлексы временно угнетаются, затем могут возвращаться с гиперрефлексией.",EN:"After acute injury reflexes are transiently depressed and may later return with hyperreflexia.",KZ:"Жедел зақымнан кейін рефлекстер уақытша тежеліп, кейін гиперрефлексиямен қайта оралуы мүмкін."},task:{RU:"Расположите фазы: арефлексия → возврат рефлексов → гиперрефлексия/стабилизация.",EN:"Order the phases: areflexia → return of reflexes → hyperreflexia/stabilization.",KZ:"Кезеңдерді реттеңіз: арефлексия → рефлекстердің қайтуы → гиперрефлексия/тұрақтану."}}],
10:[{title:{RU:"Ствол мозга и ретикулярная формация",EN:"Brainstem and reticular formation",KZ:"Ми бағаны және ретикулярлық формация"},normal:{RU:"Ствол объединяет ядра черепных нервов, жизненно важные центры и системы бодрствования.",EN:"The brainstem integrates cranial-nerve nuclei, vital centers, and arousal systems.",KZ:"Ми бағаны бассүйек нервтері ядроларын, өмірлік маңызды орталықтарды және сергектік жүйелерін біріктіреді."},lesion:{RU:"Симптомы зависят от уровня: глазодвигательные, бульбарные, дыхательные и сознательные функции могут нарушаться по-разному.",EN:"Findings vary by level: ocular motor, bulbar, respiratory, and consciousness functions can be affected differently.",KZ:"Белгілер деңгейге тәуелді: көз қимылы, бульбарлық, тыныс алу және сана функциялары әртүрлі бұзылуы мүмкін."},task:{RU:"Выберите функцию и объясните, почему уровень поражения важнее названия симптома.",EN:"Choose one function and explain why lesion level matters more than the symptom label.",KZ:"Бір функцияны таңдап, неліктен зақым деңгейі симптом атауынан маңызды екенін түсіндіріңіз."}}],
12:[{title:{RU:"Базальные ганглии",EN:"Basal ganglia",KZ:"Базальды ганглийлер"},normal:{RU:"Контуры базальных ганглиев помогают выбирать и масштабировать двигательные программы.",EN:"Basal-ganglia loops help select and scale motor programs.",KZ:"Базальды ганглий контурлары қозғалыс бағдарламаларын таңдауға және масштабтауға көмектеседі."},lesion:{RU:"Нарушение дофаминергической модуляции меняет баланс прямого и непрямого путей и характер движения.",EN:"Altered dopaminergic modulation shifts direct/indirect pathway balance and movement.",KZ:"Дофаминдік модуляцияның бұзылуы тікелей/жанама жол теңгерімін және қозғалысты өзгертеді."},task:{RU:"Сравните гипокинетический и гиперкинетический паттерн.",EN:"Compare a hypokinetic with a hyperkinetic pattern.",KZ:"Гипокинетикалық және гиперкинетикалық үлгіні салыстырыңыз."}}],
13:[{title:{RU:"Мозжечок и координация",EN:"Cerebellum and coordination",KZ:"Мишық және координация"},normal:{RU:"Мозжечок сопоставляет план движения с сенсорной обратной связью и корректирует ошибку.",EN:"The cerebellum compares the motor plan with sensory feedback and corrects error.",KZ:"Мишық қозғалыс жоспарын сенсорлық кері байланыспен салыстырып, қатені түзетеді."},lesion:{RU:"Нарушается точность, время и согласованность движения; возможны атаксия, дисметрия и интенционный тремор.",EN:"Accuracy, timing, and coordination deteriorate; ataxia, dysmetria, and intention tremor may appear.",KZ:"Қозғалыстың дәлдігі, уақыты және үйлесімі бұзылады; атаксия, дисметрия және интенциялық тремор болуы мүмкін."},task:{RU:"Предскажите, что изменится в пробе палец–нос.",EN:"Predict what changes in a finger-to-nose test.",KZ:"Саусақ–мұрын сынамасында не өзгеретінін болжаңыз."}}],
18:[{title:{RU:"Кора: зоны Бродмана и речь",EN:"Cortex: Brodmann areas and language",KZ:"Қыртыс: Бродман аймақтары және сөйлеу"},normal:{RU:"Первичные, ассоциативные и языковые зоны работают как сеть, а не как изолированные «центры».",EN:"Primary, association, and language areas operate as a network rather than isolated centers.",KZ:"Біріншілік, ассоциативтік және сөйлеу аймақтары оқшау «орталықтар» емес, желі ретінде жұмыс істейді."},lesion:{RU:"Поражение разных узлов сети даёт различные сочетания нарушений продукции, понимания и повторения речи.",EN:"Lesions at different network nodes produce different combinations of impaired production, comprehension, and repetition.",KZ:"Желінің әр түйінінің зақымы сөйлеу өндіру, түсіну және қайталау бұзылыстарының әртүрлі үйлесімін береді."},task:{RU:"Сопоставьте нарушение речи с наиболее вероятным повреждённым звеном сети.",EN:"Match a language deficit to the most likely damaged network node.",KZ:"Сөйлеу бұзылысын желінің ең ықтимал зақымданған түйінімен сәйкестендіріңіз."}}],
21:[{title:{RU:"Вестибулоспинальная коррекция равновесия",EN:"Vestibulospinal balance correction",KZ:"Вестибулоспиналдық тепе-теңдік түзетуі"},normal:{RU:"Вестибулярный сигнал через стволовые ядра меняет тонус постуральных мышц и стабилизирует тело.",EN:"Vestibular signals through brainstem nuclei adjust postural muscle tone and stabilize the body.",KZ:"Вестибулярлық сигналдар ми бағаны ядролары арқылы постуралдық бұлшықет тонусын өзгертіп, денені тұрақтандырады."},lesion:{RU:"Ошибочная оценка движения головы или нарушение выхода к мышцам ухудшает постуральную коррекцию.",EN:"Faulty head-motion estimation or impaired motor output degrades postural correction.",KZ:"Бас қозғалысын қате бағалау немесе моторлық шығудың бұзылуы постуралдық түзетуді нашарлатады."},task:{RU:"Проследите путь от внутреннего уха до изменения активности разгибателей.",EN:"Trace the pathway from the inner ear to altered extensor activity.",KZ:"Ішкі құлақтан жазғыш бұлшықеттер белсенділігінің өзгеруіне дейінгі жолды қадағалаңыз."}}],
23:[{title:{RU:"Обучение, память и условный рефлекс",EN:"Learning, memory, and conditioned reflex",KZ:"Үйрену, жад және шартты рефлекс"},normal:{RU:"Повторное сочетание значимых сигналов изменяет эффективность нейронных связей и вероятность ответа.",EN:"Repeated pairing of meaningful signals changes synaptic effectiveness and response probability.",KZ:"Маңызды сигналдарды қайталап жұптау синапстық тиімділікті және жауап ықтималдығын өзгертеді."},lesion:{RU:"Нарушение ключевых звеньев сети ухудшает формирование, консолидацию или воспроизведение памяти.",EN:"Damage to key network nodes can impair formation, consolidation, or retrieval of memory.",KZ:"Желінің негізгі түйіндерінің зақымы жадтың қалыптасуын, консолидациясын немесе қайта жаңғыртылуын бұзуы мүмкін."},task:{RU:"Отделите приобретение условной реакции от её угасания.",EN:"Distinguish acquisition of a conditioned response from extinction.",KZ:"Шартты жауаптың қалыптасуын оның сөнуінен ажыратыңыз."}}],
24:[{title:{RU:"Сон и ЭЭГ",EN:"Sleep and EEG",KZ:"Ұйқы және ЭЭГ"},normal:{RU:"Стадии сна сопровождаются характерными изменениями синхронизации и частотного состава ЭЭГ.",EN:"Sleep stages show characteristic changes in EEG synchronization and frequency composition.",KZ:"Ұйқы сатылары ЭЭГ синхрондалуы мен жиілік құрамының тән өзгерістерімен жүреді."},lesion:{RU:"Отклонение ритма само по себе не является диагнозом: его оценивают вместе с состоянием, артефактами и клиникой.",EN:"An abnormal rhythm alone is not a diagnosis; state, artifacts, and clinical context matter.",KZ:"Ырғақ ауытқуы өздігінен диагноз емес; күй, артефакт және клиникалық контекст ескеріледі."},task:{RU:"Сравните бодрствование, NREM и REM по ожидаемому ЭЭГ-паттерну.",EN:"Compare expected EEG patterns in wakefulness, NREM, and REM.",KZ:"Сергектік, NREM және REM кезіндегі күтілетін ЭЭГ үлгілерін салыстырыңыз."}}],
25:[{title:{RU:"Патофизиология: от механизма к симптому",EN:"Pathophysiology: mechanism to symptom",KZ:"Патофизиология: механизмнен симптомға"},normal:{RU:"Нормальная функция возникает из согласованной работы мембран, синапсов, путей и сетей.",EN:"Normal function emerges from coordinated membranes, synapses, pathways, and networks.",KZ:"Қалыпты функция мембраналар, синапстар, жолдар және желілердің үйлесімді жұмысынан туындайды."},lesion:{RU:"Клинический симптом нужно выводить из нарушенного механизма, а не запоминать как отдельный факт.",EN:"A clinical sign should be derived from the disrupted mechanism, not memorized as an isolated fact.",KZ:"Клиникалық белгіні жеке факт ретінде жаттамай, бұзылған механизмнен шығару керек."},task:{RU:"Выберите симптом и постройте цепочку: структура → механизм → функция → симптом.",EN:"Choose a sign and build: structure → mechanism → function → sign.",KZ:"Белгіні таңдап, тізбек құрыңыз: құрылым → механизм → функция → белгі."}}]
};
const ui={RU:{title:"Клинический атлас: норма ↔ поражение",n:"Норма",l:"Поражение",task:"Задание"},EN:{title:"Clinical atlas: normal ↔ lesion",n:"Normal",l:"Lesion",task:"Task"},KZ:{title:"Клиникалық атлас: норма ↔ зақымдану",n:"Қалыпты",l:"Зақымдану",task:"Тапсырма"}};
export default function ClinicalMechanismAtlas({moduleId,language}:{moduleId:number;language:Language}){
 const entries=E[moduleId]; const [lesion,setLesion]=useState(false); const [running,setRunning]=useState(false); const [step,setStep]=useState(0); if(!entries)return null; const t=ui[language];
 const stages=language==="RU"?["Стимул","Рецептор / вход","Центральная обработка","Выход","Функциональный ответ"]:language==="KZ"?["Стимул","Рецептор / кіріс","Орталық өңдеу","Шығыс","Функциялық жауап"]:["Stimulus","Receptor / input","Central processing","Output","Functional response"];
 function animate(){setRunning(true);setStep(0); let n=0; const timer=setInterval(()=>{n++;setStep(n);if(n>=4){clearInterval(timer);setRunning(false)}},520);}
 const sim=language==="RU"?{run:"▶ Запустить сигнал",reset:"Сброс",hint:"Проследите сигнал слева направо. При поражении цепь показывает функциональный сбой."}:language==="KZ"?{run:"▶ Сигналды іске қосу",reset:"Қалпына келтіру",hint:"Сигналды солдан оңға қадағалаңыз. Зақымдануда тізбек функциялық ақауды көрсетеді."}:{run:"▶ Run signal",reset:"Reset",hint:"Trace the signal left to right. In lesion mode the chain represents functional failure."};
 return <section style={{margin:"22px 0",padding:16,border:"1px solid #d8e2e8",borderRadius:16,background:"#fbfdff"}}>
  <h2 style={{marginTop:0}}>{t.title}</h2>
  <div role="group" aria-label={t.title} style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:14}}>
   <button type="button" aria-pressed={!lesion} onClick={()=>setLesion(false)}>{t.n}</button>
   <button type="button" aria-pressed={lesion} onClick={()=>setLesion(true)}>{t.l}</button>
  </div>
  <div aria-label={sim.hint} style={{margin:"14px 0 18px",padding:12,borderRadius:14,background:"#f3f8fb"}}>
    <p style={{marginTop:0}}>{sim.hint}</p>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:8}}>
      {stages.map((s,i)=><div key={s} style={{padding:"12px 8px",textAlign:"center",borderRadius:12,border:step===i?"2px solid currentColor":"1px solid #ccd8df",transform:step===i?"scale(1.03)":"none",transition:"all .25s",opacity:lesion&&i>2?.55:1}}><strong>{i+1}</strong><br/>{s}{lesion&&i===2?<div aria-label="lesion">⚠</div>:null}</div>)}
    </div>
    <div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap"}}>
      <button type="button" onClick={animate} disabled={running}>{sim.run}</button>
      <button type="button" onClick={()=>{setStep(0);setRunning(false)}}>{sim.reset}</button>
    </div>
  </div>
  {entries.map((e,i)=><article key={i} style={{padding:"12px 0"}}>
   <h3>{e.title[language]}</h3><p>{lesion?e.lesion[language]:e.normal[language]}</p>
   <p><strong>{t.task}: </strong>{e.task[language]}</p>
  </article>)}
 </section>;
}
