"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
import AnatomyReference from "./AnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Контраст и популяционное кодирование",a:"Возбуждение центра",b:"Торможение окружения",c:"Усиление контраста",d:"Популяционный ответ",task:"Сформулируйте прогноз. Измените один параметр, сохранив второй постоянным; затем поменяйте второй и сравните результаты.",save:"Записать опыт",prediction:"Прогноз перед опытом",note:"Физиологическое объяснение",limit:"Модель иллюстрирует общий принцип повышения пространственного контраста за счёт взаимодействия возбуждающих и тормозных влияний. Классические центр–окружение рецептивные поля формируются уже в сетчатке и латеральном коленчатом теле; корковая обработка дополнительно использует ориентационную, пространственно-частотную и контекстную селективность распределённых нейронных популяций. Поэтому схема не должна трактоваться как буквальная количественная запись одного коркового нейрона."},EN:{title:"Contrast and population coding",a:"Center excitation",b:"Surround inhibition",c:"Contrast enhancement",d:"Population response",task:"Make a prediction. Change one parameter while holding the other constant, then change the second and compare results.",save:"Record trial",prediction:"Prediction before trial",note:"Physiological explanation",limit:"This model illustrates the general principle of spatial contrast enhancement through interacting excitatory and inhibitory influences. Classical center–surround receptive fields are already established in retinal and lateral geniculate pathways; cortical processing additionally uses orientation, spatial-frequency, and contextual selectivity across distributed populations. The diagram should therefore not be read as a quantitative recording from a single cortical neuron."},KZ:{title:"Контраст және популяциялық кодтау",a:"Орталықтың қозуы",b:"Айналаның тежелуі",c:"Контрасттың күшеюі",d:"Популяциялық жауап",task:"Алдымен болжам жасаңыз. Бір параметрді тұрақты екіншісінде өзгертіңіз, кейін екіншісін өзгертіп нәтижелерді салыстырыңыз.",save:"Тәжірибені жазу",prediction:"Тәжірибеге дейінгі болжам",note:"Физиологиялық түсіндірме",limit:"Модель қоздырушы және тежеуші ықпалдардың өзара әрекеті арқылы кеңістіктік контрасттың күшею қағидасын көрсетеді. Классикалық орталық–айналма рецептивтік өрістер торқабық пен латералдық тізелі дене жолдарында-ақ қалыптасады; қыртыстық өңдеу бұған қоса бағдарға, кеңістіктік жиілікке және контекстке селективті таралған нейрондық популяцияларды пайдаланады. Сондықтан сызбаны бір қыртыстық нейронның сандық жазбасы ретінде түсіндіруге болмайды."}} as const;
function calc(a:number,b:number){return Math.max(0,Math.min(100,Math.round(a-b*.55)));}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(60),[b,setB]=useState(50),[prediction,setPrediction]=useState(""),[rows,setRows]=useState<Row[]>([]);const out=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AnatomyReference moduleId={18} language={language}/><p><strong>{t.task}</strong></p><label>{t.prediction}<textarea value={prediction} onChange={e=>setPrediction(e.target.value)} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a}%<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b}%<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 190" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><defs><marker id="arr18" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8Z" fill="currentColor"/></marker></defs><circle cx="80" cy="90" r={18+a/7} fill="none" stroke="currentColor" strokeWidth="3"/><path d="M115 90 H290" stroke="currentColor" strokeWidth={2+a/30} markerEnd="url(#arr18)"/><rect x="300" y="52" width="130" height="76" rx="22" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M430 90 H575" stroke="currentColor" strokeWidth={2+out/30} markerEnd="url(#arr18)"/><circle cx="610" cy="90" r={12+out/8} fill="none" stroke="currentColor" strokeWidth="3"/><text x="315" y="82">{t.c}</text><text x="315" y="108">{out}%</text><text x="475" y="55">{t.d}</text></svg><button disabled={!prediction.trim()} onClick={()=>{recordOutcome(18,"interactive",prediction.trim().length>=20?1:0,1);recordOutcome(18,"criterion:application:lab",1,1);setRows(r=>[...r,{id:Date.now(),a,b,out,note:""}])}}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.c}</th><th>{t.note}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}</td><td>{r.b}</td><td>{r.out}%</td><td><input value={r.note} onChange={e=>{const note=e.target.value;setRows(xs=>xs.map(q=>q.id===r.id?{...q,note}:q));if(note.trim().length>=30)recordOutcome(18,"criterion:justification:lab",1,1)}}/></td></tr>)}</tbody></table></div><ExperimentReflection language={language} theoryHref={`/modules/18/theory?lang=${language}`}/><p><small>{t.limit}</small></p></section>}
