"use client";

import { useState } from "react";
import type { Language } from "../content/course";
import { topics } from "../content/course-foundation/topics";
import VoiceTextarea from "./VoiceTextarea";
import VisualPathwayLocalizer from "./VisualPathwayLocalizer";

const ui={
 RU:{title:"Виртуальный пациент",intro:"Синтетический учебный сценарий. Двигайтесь от наблюдения к механизму; это тренировка рассуждения, а не постановка реального диагноза.",stage:["1. Наблюдение","2. Физиологическая гипотеза","3. Проверка и границы вывода"],prompt:["Что в ситуации является наблюдаемым фактом?","Какой физиологический механизм может объяснить изменение?","Какое дополнительное наблюдение проверит гипотезу и чего пока нельзя утверждать?"],show:"Открыть ориентир",hide:"Скрыть ориентир",answer:"Ориентир для самопроверки",note:"Сначала сформулируйте ответ самостоятельно."},
 EN:{title:"Virtual Patient",intro:"A synthetic teaching scenario. Move from observation to mechanism; this trains reasoning and does not establish a real diagnosis.",stage:["1. Observation","2. Physiological hypothesis","3. Test and limits"],prompt:["What in the scenario is directly observable?","Which physiological mechanism could explain the change?","What additional observation would test the hypothesis, and what cannot yet be concluded?"],show:"Show guide",hide:"Hide guide",answer:"Self-check guide",note:"Formulate your own answer first."},
 KZ:{title:"Виртуалды пациент",intro:"Синтетикалық оқу сценарийі. Бақылаудан тетікке өтіңіз; бұл нақты диагноз қою емес, пайымдауды жаттықтыру.",stage:["1. Бақылау","2. Физиологиялық гипотеза","3. Тексеру және шектеу"],prompt:["Жағдайдағы тікелей бақыланатын дерек қандай?","Өзгерісті қандай физиологиялық тетік түсіндіре алады?","Гипотезаны қандай қосымша бақылау тексереді және әзірге нені айтуға болмайды?"],show:"Бағдарды ашу",hide:"Бағдарды жасыру",answer:"Өзін-өзі тексеру бағдары",note:"Алдымен жауабыңызды өзіңіз тұжырымдаңыз."}
} as const;

type Scenario={role:Record<Language,string>;finding:Record<Language,string>;test:Record<Language,string>;alternative:Record<Language,string>};
const scenarioFor=(id:number):Scenario=>{
 const t=(RU:string,EN:string,KZ:string)=>({RU,EN,KZ});
 if(id===3)return{role:t("Пациент после локального повреждения периферического нерва","Patient after a focal peripheral nerve injury","Перифериялық жүйкенің жергілікті зақымынан кейінгі пациент"),finding:t("В зоне иннервации меняются чувствительность и скорость восстановления функции, при этом состояние окружающей ткани неоднородно.","Sensation and functional recovery change within the innervated territory while the surrounding tissue environment is heterogeneous.","Иннервация аймағында сезімталдық пен функцияның қалпына келу жылдамдығы өзгереді, ал қоршаған тін ортасы біркелкі емес."),test:t("Сопоставить состояние аксона, глии и микроокружения и проследить изменение функции во времени.","Compare axonal, glial, and microenvironmental states and follow function over time.","Аксонның, глияның және микроортаның күйін салыстырып, функцияның уақыт бойынша өзгерісін бақылау."),alternative:t("Проверить, объясняется ли изменение только нейроном или вкладом глии и внеклеточной среды.","Test whether the change is explained by the neuron alone or also by glia and extracellular environment.","Өзгеріс тек нейронмен бе, әлде глия мен жасушадан тыс ортаның үлесімен де түсіндіріле ме, соны тексеру.")};
 if(id===6)return{role:t("Пациент при исследовании баланса возбуждения и торможения","Patient during testing of excitation-inhibition balance","Қозу мен тежелу тепе-теңдігін зерттеудегі пациент"),finding:t("Одинаковый входной стимул вызывает разные выходные ответы в зависимости от предшествующей активности сети.","The same input evokes different outputs depending on preceding network activity.","Бірдей кіріс стимулы желінің алдыңғы белсенділігіне қарай әртүрлі шығыс жауаптарын туғызады."),test:t("Раздельно изменить возбуждающий и тормозный вход и сравнить итоговый ответ нейронной сети.","Vary excitatory and inhibitory input separately and compare the network output.","Қоздырғыш және тежегіш кірісті бөлек өзгертіп, нейрондық желінің қорытынды жауабын салыстыру."),alternative:t("Проверить роль временной и пространственной суммации вместо изменения одного синапса.","Test temporal and spatial summation rather than attributing the effect to a single synapse.","Әсерді бір синапсқа ғана жатқызбай, уақыттық және кеңістіктік суммацияның рөлін тексеру.")};
 if(id===8)return{role:t("Пациент с избирательным изменением проведения чувствительного сигнала","Patient with selective alteration of sensory conduction","Сезімтал сигнал өткізгіштігі таңдамалы өзгерген пациент"),finding:t("Одна модальность чувствительности изменена, тогда как другая при исследовании сохраняется лучше.","One sensory modality is altered while another is relatively preserved on examination.","Зерттеуде сезімталдықтың бір модальдылығы өзгерген, ал екіншісі салыстырмалы жақсы сақталған."),test:t("Сопоставить распределение нарушения с ходом восходящих путей и местом их перекрёста.","Relate the deficit pattern to ascending pathways and their decussation.","Бұзылыс таралуын жоғарылаушы жолдармен және олардың айқасу орнымен салыстыру."),alternative:t("Проверить периферический нерв, корешок и центральный проводящий путь как разные уровни.","Test peripheral nerve, root, and central tract as distinct levels.","Перифериялық жүйкені, түбірді және орталық өткізгіш жолды бөлек деңгейлер ретінде тексеру.")};
 if(id===9)return{role:t("Пациент при исследовании спинальной регуляции","Patient undergoing spinal regulation assessment","Жұлындық реттелуді зерттеудегі пациент"),finding:t("Ниже предполагаемого уровня изменяются рефлекторные ответы и произвольный контроль движения.","Below a suspected level, reflex responses and voluntary motor control are altered.","Болжамды деңгейден төмен рефлекстік жауаптар мен ерікті қозғалыс бақылауы өзгерген."),test:t("Сравнить сегментарные рефлексы на разных уровнях и нисходящий контроль.","Compare segmental reflexes at different levels and descending control.","Әртүрлі деңгейдегі сегменттік рефлекстерді және төмендеуші бақылауды салыстыру."),alternative:t("Отделить сегментарное нарушение от изменения нисходящих влияний на сохранную дугу.","Distinguish a segmental lesion from altered descending influence on an intact arc.","Сегменттік бұзылысты сақталған доғаға төмендеуші ықпалдың өзгерісінен ажырату.")};
 if(id===10)return{role:t("Пациент с изменением уровня бодрствования и стволовых реакций","Patient with altered arousal and brainstem responses","Сергектік деңгейі мен ми сабауы реакциялары өзгерген пациент"),finding:t("Реакция на сенсорный стимул замедлена, а уровень бодрствования колеблется во время наблюдения.","Response to sensory stimulation is slowed and arousal fluctuates during observation.","Сенсорлық стимулға жауап баяулаған, бақылау кезінде сергектік деңгейі ауытқиды."),test:t("Сопоставить стволовые рефлексы, сенсорный вход и изменения бодрствования во времени.","Compare brainstem reflexes, sensory input, and arousal changes over time.","Ми сабауы рефлекстерін, сенсорлық кірісті және сергектіктің уақыт бойынша өзгерісін салыстыру."),alternative:t("Проверить, связано ли снижение ответа с сенсорным входом, моторным выходом или системой активации.","Test whether reduced responsiveness reflects sensory input, motor output, or arousal systems.","Жауаптың төмендеуі сенсорлық кіріске, моторлық шығысқа немесе белсендіру жүйесіне байланысты ма, соны тексеру.")};
 if(id===11)return{role:t("Пациент с нарушением выполнения произвольного движения","Patient with impaired voluntary movement performance","Ерікті қозғалысты орындауы бұзылған пациент"),finding:t("Пациент понимает команду, но сила, траектория и точность движения меняются при разных заданиях.","The patient understands the command, but movement strength, trajectory, and accuracy vary across tasks.","Пациент команданы түсінеді, бірақ әр тапсырмада қозғалыс күші, траекториясы және дәлдігі өзгереді."),test:t("Раздельно оценить планирование, нисходящую команду, мышечный ответ и сенсорную коррекцию.","Assess planning, descending command, muscle response, and sensory correction separately.","Жоспарлауды, төмендеуші команданы, бұлшықет жауабын және сенсорлық түзетуді бөлек бағалау."),alternative:t("Проверить, находится ли ограничение в центральной команде, периферическом исполнении или обратной связи.","Test whether the limitation lies in central command, peripheral execution, or feedback.","Шектеу орталық командада, перифериялық орындауда немесе кері байланыста ма, соны тексеру.")};
 if(id===14)return{role:t("Пациент с изменением обработки сенсорной информации перед корой","Patient with altered sensory processing before cortex","Қыртысқа дейінгі сенсорлық өңдеуі өзгерген пациент"),finding:t("Реакция на одинаковый стимул меняется в зависимости от состояния внимания и уровня бодрствования.","Response to the same stimulus varies with attention and arousal.","Бірдей стимулға жауап зейін мен сергектік күйіне қарай өзгереді."),test:t("Сравнить сенсорный вход и корковый ответ при разных состояниях внимания.","Compare sensory input and cortical response across attention states.","Әртүрлі зейін күйлерінде сенсорлық кіріс пен қыртыстық жауапты салыстыру."),alternative:t("Проверить таламическое переключение и корковую модуляцию как взаимосвязанные, но разные уровни.","Test thalamic gating and cortical modulation as related but distinct levels.","Таламустық қақпалау мен қыртыстық модуляцияны өзара байланысты, бірақ бөлек деңгейлер ретінде тексеру.")};
 if(id===4)return{role:t("Пациент при исследовании возбудимости нервного волокна","Patient during nerve excitability testing","Жүйке талшығының қозғыштығын зерттеудегі пациент"),finding:t("При постепенном усилении стимула ответ отсутствует до определённого уровня, затем возникает быстрый стереотипный сигнал.","As stimulus strength rises, no response appears until a threshold is reached, followed by a rapid stereotyped signal.","Стимул күшейгенде белгілі бір табалдырыққа дейін жауап жоқ, одан кейін жылдам стереотипті сигнал пайда болады."),test:t("Сопоставить порог, фазу деполяризации и рефрактерный период при повторных стимулах.","Compare threshold, depolarization, and refractory period during repeated stimuli.","Қайталама стимулдарда табалдырықты, деполяризацияны және рефрактерлік кезеңді салыстыру."),alternative:t("Проверить, не связано ли изменение ответа с проведением по аксону, а не с генерацией потенциала действия.","Test whether the altered response reflects axonal conduction rather than action-potential generation.","Жауап өзгерісі әрекет потенциалының түзілуінен емес, аксон бойымен өткізуден туындай ма, соны тексеру.")};
 if(id===5)return{role:t("Пациент при исследовании синаптической передачи","Patient during synaptic transmission testing","Синапстық берілісті зерттеудегі пациент"),finding:t("Пресинаптический сигнал регистрируется, но постсинаптический ответ изменён по амплитуде и времени.","A presynaptic signal is recorded, but the postsynaptic response has altered amplitude and timing.","Пресинапстық сигнал тіркеледі, бірақ постсинапстық жауаптың амплитудасы мен уақыты өзгерген."),test:t("Сравнить пресинаптический сигнал, высвобождение медиатора и постсинаптический ответ.","Compare the presynaptic signal, transmitter release, and postsynaptic response.","Пресинапстық сигналды, медиатор бөлінуін және постсинапстық жауапты салыстыру."),alternative:t("Проверить отдельно пресинаптический и постсинаптический уровни передачи.","Test presynaptic and postsynaptic levels separately.","Берілістің пресинапстық және постсинапстық деңгейлерін бөлек тексеру.")};
 if(id===7)return{role:t("Пациент при исследовании сухожильного рефлекса","Patient undergoing tendon-reflex examination","Сіңір рефлексін тексерудегі пациент"),finding:t("При одинаковом стимуле сухожильный рефлекс справа и слева различается по выраженности.","With the same stimulus, tendon-reflex magnitude differs between the two sides.","Бірдей стимул кезінде оң және сол жақтағы сіңір рефлексінің айқындығы әртүрлі."),test:t("Последовательно проверить афферентное звено, центральную интеграцию и эфферентный ответ рефлекторной дуги.","Sequentially test the afferent limb, central integration, and efferent response of the reflex arc.","Рефлекс доғасының афференттік буынын, орталық интеграциясын және эфференттік жауабын ретімен тексеру."),alternative:t("Проверить, может ли различие быть связано с состоянием мышцы или условиями исследования, а не только с центральным звеном.","Test whether muscle state or examination conditions, rather than only the central limb, could explain the difference.","Айырмашылық тек орталық буыннан емес, бұлшықет күйінен немесе зерттеу жағдайынан болуы мүмкін бе, соны тексеру.")};
 if(id===12)return{role:t("Пациент с замедленностью и трудностью запуска движения","Patient with slowed movement initiation","Қозғалысты бастауы баяулаған пациент"),finding:t("Произвольное движение начинается с задержкой и выполняется медленнее, хотя задача понята.","Voluntary movement starts after a delay and is slower despite intact task comprehension.","Тапсырманы түсінгенімен, ерікті қозғалыс кеш басталып, баяу орындалады."),test:t("Сравнить запуск движения, его масштаб и автоматические компоненты в повторных пробах.","Compare movement initiation, scaling, and automatic components across repeated tasks.","Қайталама сынақтарда қозғалыстың басталуын, ауқымын және автоматты компоненттерін салыстыру."),alternative:t("Отделить нарушение выбора и запуска моторной программы от слабости или мозжечковой дисметрии.","Distinguish impaired motor-program selection/initiation from weakness or cerebellar dysmetria.","Моторлық бағдарламаны таңдау/бастау бұзылысын әлсіздік немесе мишықтық дисметриядан ажырату.")};
 if(id===13)return{role:t("Пациент с неточностью целенаправленного движения","Patient with inaccurate goal-directed movement","Мақсатты қозғалысы дәл емес пациент"),finding:t("При пальце-носовой пробе движение становится неточным у цели, особенно при повторении.","During finger-to-nose testing, movement becomes inaccurate near the target, especially on repetition.","Саусақ-мұрын сынағында қозғалыс нысанаға жақындағанда, әсіресе қайталауда дәлдігін жоғалтады."),test:t("Сравнить траекторию, коррекцию ошибки и зависимость результата от сенсорной обратной связи.","Compare trajectory, error correction, and dependence on sensory feedback.","Траекторияны, қатені түзетуді және нәтижесінің сенсорлық кері байланысқа тәуелділігін салыстыру."),alternative:t("Проверить, объясняется ли неточность слабостью или нарушением чувствительности, а не координацией.","Test whether weakness or sensory loss rather than coordination explains the inaccuracy.","Дәлсіздік координациядан емес, әлсіздік немесе сезімталдық бұзылысынан туындай ма, соны тексеру.")};
 if(id===15)return{role:t("Пациент при исследовании гомеостатической регуляции","Patient undergoing homeostatic regulation assessment","Гомеостаздық реттелуді зерттеудегі пациент"),finding:t("После изменения внутреннего состояния одновременно меняются субъективное ощущение, вегетативная реакция и поведение.","After a change in internal state, subjective sensation, autonomic response, and behaviour change together.","Ішкі күй өзгергеннен кейін субъективті сезім, вегетативтік реакция және мінез-құлық қатар өзгереді."),test:t("Сопоставить контролируемую переменную, компенсаторную реакцию и возвращение к исходному диапазону.","Relate the controlled variable, compensatory response, and return toward baseline range.","Бақыланатын айнымалыны, компенсаторлық реакцияны және бастапқы диапазонға қайтуды салыстыру."),alternative:t("Проверить, является ли наблюдаемая реакция специфической гомеостатической коррекцией или неспецифическим стрессовым ответом.","Test whether the response is a specific homeostatic correction or a nonspecific stress response.","Бақыланған реакция арнайы гомеостаздық түзету ме, әлде спецификалық емес стресс жауабы ма, соны тексеру.")};
 if(id===16)return{role:t("Пациент с изменением эмоциональной и мотивационной реакции","Patient with altered emotional and motivational responses","Эмоциялық және мотивациялық реакциясы өзгерген пациент"),finding:t("Один и тот же значимый стимул вызывает различную автономную и поведенческую реакцию в разных контекстах.","The same salient stimulus produces different autonomic and behavioural responses across contexts.","Бір маңызды стимул әр контексте әртүрлі вегетативтік және мінез-құлық реакциясын туғызады."),test:t("Сравнить контекст, вегетативный компонент, мотивационную значимость и выбранное поведение.","Compare context, autonomic component, motivational salience, and selected behaviour.","Контексті, вегетативтік компонентті, мотивациялық маңыздылықты және таңдалған мінез-құлықты салыстыру."),alternative:t("Проверить вклад памяти и текущего физиологического состояния, не сводя реакцию к одной структуре.","Test contributions of memory and current physiological state without reducing the response to a single structure.","Реакцияны бір құрылымға ғана телімей, жад пен ағымдағы физиологиялық күйдің үлесін тексеру.")};
 if(id===17)return{role:t("Пациент при исследовании эмоционального обучения","Patient undergoing emotional-learning assessment","Эмоциялық үйренуді зерттеудегі пациент"),finding:t("После повторного сочетания нейтрального сигнала со значимым событием автономная реакция начинает возникать уже на сигнал.","After repeated pairing of a neutral cue with a salient event, an autonomic response begins to occur to the cue alone.","Бейтарап сигнал маңызды оқиғамен бірнеше рет жұптасқаннан кейін вегетативтік реакция сигналдың өзіне пайда болады."),test:t("Сравнить реакцию до обучения, после сочетаний и при предъявлении сигнала без подкрепления.","Compare responses before learning, after pairing, and when the cue is presented without reinforcement.","Үйренуге дейінгі, жұптастырудан кейінгі және сигналды бекітусіз бергендегі реакцияларды салыстыру."),alternative:t("Проверить, отражает ли изменение ассоциативное обучение, сенситизацию или контекстный эффект.","Test whether the change reflects associative learning, sensitization, or a contextual effect.","Өзгеріс ассоциативтік үйренуді, сенситизацияны немесе контекст әсерін көрсете ме, соны тексеру.")};
 if(id===18)return{role:t("Пациент при исследовании функциональной организации коры","Patient undergoing cortical functional assessment","Қыртыстың функционалдық ұйымдасуын зерттеудегі пациент"),finding:t("При двух разных заданиях меняются разные компоненты сложной функции, несмотря на сохранное понимание инструкции.","Two tasks alter different components of a complex function despite preserved instruction comprehension.","Екі түрлі тапсырмада нұсқауды түсіну сақталғанымен, күрделі функцияның әртүрлі компоненттері өзгереді."),test:t("Разделить сенсорный анализ, планирование ответа и выполнение, сопоставив результаты нескольких заданий.","Separate sensory analysis, response planning, and execution by comparing several tasks.","Бірнеше тапсырманы салыстырып, сенсорлық талдауды, жауапты жоспарлауды және орындауды ажырату."),alternative:t("Проверить сетевое объяснение результата вместо жёсткой локализации всей функции в одной зоне.","Test a network explanation rather than rigidly localizing the entire function to one cortical area.","Бүкіл функцияны бір аймаққа қатаң локализациялаудың орнына желілік түсіндіруді тексеру.")};
 if(id===19)return{role:t("Пациент с изменённым восприятием прикосновения и боли","Patient with altered touch and pain perception","Жанасу мен ауырсынуды қабылдауы өзгерген пациент"),finding:t("Одинаковый стандартизированный стимул на двух участках кожи воспринимается по-разному.","The same standardized stimulus is perceived differently at two skin sites.","Бірдей стандартталған стимул терінің екі аймағында әртүрлі қабылданады."),test:t("Раздельно сравнить модальность, порог, локализацию и распределение чувствительности.","Compare modality, threshold, localization, and sensory distribution separately.","Модальдылықты, табалдырықты, локализацияны және сезімталдық таралуын бөлек салыстыру."),alternative:t("Проверить периферическую территорию нерва и центральный проводящий путь как разные уровни локализации.","Test peripheral nerve territory and central pathway as distinct localization levels.","Перифериялық жүйке аймағын және орталық өткізгіш жолды бөлек локализация деңгейлері ретінде тексеру.")};
 if(id===20)return{role:t("Пациент с жалобой на изменение поля зрения","Patient reporting a visual-field change","Көру өрісі өзгерген пациент"),finding:t("При фиксации взгляда часть стандартных зрительных стимулов систематически не обнаруживается в определённой области поля зрения.","During fixation, standard visual stimuli are consistently missed in a particular visual-field region.","Көзді бір нүктеге бекіткенде стандартты көру стимулдарының бір бөлігі көру өрісінің белгілі аймағында тұрақты байқалмайды."),test:t("Картировать поле зрения обоих глаз и сопоставить рисунок выпадения с уровнем зрительного пути.","Map both visual fields and relate the loss pattern to the level of the visual pathway.","Екі көздің көру өрісін картаға түсіріп, жоғалу үлгісін көру жолының деңгейімен салыстыру."),alternative:t("Отделить оптическую проблему глаза от поражения сетчатки, зрительного нерва и более центральных отделов пути.","Distinguish an optical eye problem from retinal, optic-nerve, or more central pathway involvement.","Көздің оптикалық мәселесін торқабық, көру жүйкесі немесе жолдың орталық бөлімдері зақымынан ажырату.")};
 if(id===21)return{role:t("Пациент с избирательным изменением слухового и вестибулярного восприятия","Patient with selective auditory and vestibular changes","Есту және вестибулярлық қабылдауы таңдамалы өзгерген пациент"),finding:t("При стандартизированных пробах меняются восприятие звука и устойчивость, но выраженность изменений зависит от типа стимула.","Standardized tests reveal changes in sound perception and balance whose magnitude depends on stimulus type.","Стандартталған сынақтарда дыбысты қабылдау мен тепе-теңдік өзгереді, өзгеріс дәрежесі стимул түріне тәуелді."),test:t("Раздельно исследовать слуховой и вестибулярный вход и сопоставить результаты с направлением и частотой стимула.","Test auditory and vestibular inputs separately and relate findings to stimulus direction and frequency.","Есту және вестибулярлық кірісті бөлек зерттеп, нәтижені стимул бағыты мен жиілігімен салыстыру."),alternative:t("Проверить периферический рецепторный аппарат и центральную обработку как разные уровни объяснения.","Test peripheral receptor apparatus and central processing as distinct explanatory levels.","Перифериялық рецепторлық аппарат пен орталық өңдеуді бөлек түсіндіру деңгейлері ретінде тексеру.")};
 if(id===22)return{role:t("Пациент при ортостатической функциональной пробе","Patient undergoing an orthostatic challenge","Ортостатикалық функционалдық сынақтағы пациент"),finding:t("После перехода из положения лёжа в положение стоя изменяются частота сердечных сокращений и самочувствие.","After moving from supine to standing, heart rate and symptoms change.","Жатқан қалыптан тұрған кезде жүрек соғу жиілігі мен өзін-өзі сезінуі өзгереді."),test:t("Сравнить показатели лёжа, сразу после вставания и в период восстановления.","Compare measurements supine, immediately after standing, and during recovery.","Жатқандағы, тұрғаннан кейінгі және қалпына келу кезіндегі көрсеткіштерді салыстыру."),alternative:t("Разделить нормальную компенсаторную вегетативную реакцию и устойчивое нарушение регуляции.","Distinguish a normal compensatory autonomic response from persistent dysregulation.","Қалыпты компенсаторлық вегетативтік реакцияны тұрақты реттелу бұзылысынан ажырату.")};
 if(id===24)return{role:t("Пациент с нарушением режима сна и бодрствования","Patient with a disrupted sleep-wake schedule","Ұйқы-ояу режимі бұзылған пациент"),finding:t("После смещения времени сна меняются дневная сонливость, внимание и субъективная бодрость.","After a shift in sleep timing, daytime sleepiness, attention, and alertness change.","Ұйқы уақыты ығысқаннан кейін күндізгі ұйқышылдық, зейін және сергектік өзгереді."),test:t("Сопоставить время сна, световой режим, дневную функцию и повторные наблюдения в разные часы.","Compare sleep timing, light exposure, daytime function, and repeated observations at different clock times.","Ұйқы уақытын, жарық режимін, күндізгі функцияны және әр сағаттағы қайталама бақылауларды салыстыру."),alternative:t("Отделить циркадный сдвиг от недостаточной продолжительности сна и других причин сонливости.","Distinguish circadian misalignment from insufficient sleep duration and other causes of sleepiness.","Циркадтық ығысуды ұйқы ұзақтығының жеткіліксіздігінен және ұйқышылдықтың басқа себептерінен ажырату.")};
 if(id===2)return{role:t("Пациент на функциональном исследовании","Patient undergoing functional testing","Функционалдық зерттеудегі пациент"),finding:t("Во время регистрации появляется изменение сигнала; одновременно пациент моргает и напрягает мышцы лба.","A signal change appears during recording while the patient blinks and tenses the forehead muscles.","Тіркеу кезінде сигнал өзгереді, сол сәтте пациент көзін жыпылықтатып, маңдай бұлшықеттерін кернейді."),test:t("Повторить запись после устранения возможного артефакта и сравнить участки сигнала.","Repeat the recording after reducing the possible artifact and compare signal segments.","Ықтимал артефактты азайтып, жазбаны қайталап, сигнал бөліктерін салыстыру."),alternative:t("Рассмотреть физиологическое изменение сигнала, но отделить его от артефакта регистрации.","Consider a physiological signal change while separating it from recording artifact.","Физиологиялық сигнал өзгерісін қарастыру, бірақ оны тіркеу артефактынан ажырату.")};
 if(id>=3&&id<=6)return{role:t("Пациент с изменением нервно-мышечной функции","Patient with altered neuromuscular function","Жүйке-бұлшықет қызметі өзгерген пациент"),finding:t("После стандартного стимула ответ ткани отличается от ожидаемого.","After a standard stimulus, the tissue response differs from the expected pattern.","Стандартты стимулдан кейін тін жауабы күтілгеннен өзгеше."),test:t("Изменить один физиологический параметр и сравнить величину и временной ход ответа.","Change one physiological parameter and compare response magnitude and time course.","Бір физиологиялық параметрді өзгертіп, жауап шамасы мен уақыттық барысын салыстыру."),alternative:t("Проверить, относится ли изменение к мембране, проведению или синаптической передаче.","Test whether the change arises from membrane, conduction, or synaptic transmission.","Өзгерістің мембранаға, өткізуге немесе синапстық берілуге қатысты екенін тексеру.")};
 if(id>=7&&id<=14)return{role:t("Пациент с изменением движения или рефлекторного ответа","Patient with an altered movement or reflex response","Қозғалысы немесе рефлекстік жауабы өзгерген пациент"),finding:t("При выполнении двигательной пробы меняются точность, сила или характер ответа.","During a motor task, response accuracy, strength, or pattern changes.","Қозғалыс сынағында жауаптың дәлдігі, күші немесе сипаты өзгереді."),test:t("Сравнить сенсорный вход, двигательную команду и коррекцию при повторной пробе.","Compare sensory input, motor command, and correction during a repeated task.","Қайталама сынақта сенсорлық кірісті, қозғалтқыш команданы және түзетуді салыстыру."),alternative:t("Проверить альтернативную локализацию в другом звене двигательной системы.","Test an alternative localization in another link of the motor system.","Қозғалыс жүйесінің басқа буынындағы балама локализацияны тексеру.")};
 if(id>=15&&id<=18)return{role:t("Пациент с изменением регуляции, эмоций или поведения","Patient with altered regulation, emotion, or behaviour","Реттелуі, эмоциясы немесе мінез-құлқы өзгерген пациент"),finding:t("Наблюдается устойчивое изменение реакции на значимый стимул или внутреннее состояние.","A persistent change is observed in response to a salient stimulus or internal state.","Маңызды стимулға немесе ішкі күйге жауаптың тұрақты өзгерісі байқалады."),test:t("Сопоставить контекст, автономную реакцию и поведенческий ответ в повторной ситуации.","Compare context, autonomic response, and behaviour in a repeated situation.","Қайталама жағдайда контексті, вегетативтік реакцияны және мінез-құлық жауабын салыстыру."),alternative:t("Проверить, объясняется ли результат другой регуляторной системой или контекстом.","Test whether another regulatory system or context explains the result.","Нәтижені басқа реттеуші жүйе немесе контекст түсіндіре ме, соны тексеру.")};
 if(id>=19&&id<=21)return{role:t("Пациент с изменением сенсорного восприятия","Patient with altered sensory perception","Сенсорлық қабылдауы өзгерген пациент"),finding:t("При стандартизированном стимуле пациент описывает изменение качества, локализации или интенсивности ощущения.","With a standardized stimulus, the patient reports altered quality, location, or intensity of sensation.","Стандартталған стимул кезінде пациент сезім сапасының, орнының немесе қарқындылығының өзгеруін сипаттайды."),test:t("Изменить один параметр стимула и сравнить порог, локализацию и субъективный ответ.","Change one stimulus parameter and compare threshold, localization, and subjective response.","Стимулдың бір параметрін өзгертіп, табалдырықты, локализацияны және субъективті жауапты салыстыру."),alternative:t("Проверить периферический и центральный уровни сенсорного пути как разные гипотезы.","Test peripheral and central levels of the sensory pathway as separate hypotheses.","Сенсорлық жолдың перифериялық және орталық деңгейлерін бөлек гипотеза ретінде тексеру.")};
 if(id===22)return{role:t("Пациент с изменением вегетативной реакции","Patient with an altered autonomic response","Вегетативтік реакциясы өзгерген пациент"),finding:t("При смене функционального состояния меняются частота сердечных сокращений и другие вегетативные показатели.","With a change in functional state, heart rate and other autonomic measures change.","Функционалдық күй өзгергенде жүрек жиілігі және басқа вегетативтік көрсеткіштер өзгереді."),test:t("Сравнить исходное состояние, нагрузку и восстановление.","Compare baseline, challenge, and recovery.","Бастапқы күйді, жүктемені және қалпына келуді салыстыру."),alternative:t("Разделить вклад симпатического, парасимпатического и неспецифического стрессового ответа.","Separate sympathetic, parasympathetic, and nonspecific stress contributions.","Симпатикалық, парасимпатикалық және спецификалық емес стресс жауабының үлесін ажырату.")};
 if(id===23)return{role:t("Пациент при исследовании обучения, памяти и речевой функции","Patient undergoing learning, memory, and language assessment","Үйрену, жад және сөйлеу функциясын зерттеудегі пациент"),finding:t("После короткого обучения немедленное выполнение сохранено, но результат меняется при задержке и при смене способа предъявления материала.","After brief learning, immediate performance is preserved but changes after a delay and when material presentation changes.","Қысқа үйренуден кейін дереу орындау сақталған, бірақ кідірістен соң және материалды ұсыну тәсілі өзгергенде нәтиже өзгереді."),test:t("Сравнить кодирование, удержание и воспроизведение, используя разные способы предъявления и отсрочку.","Compare encoding, retention, and retrieval using different presentation modes and a delay.","Әртүрлі ұсыну тәсілдері мен кідірісті қолданып, кодтауды, сақтауды және қайта жаңғыртуды салыстыру."),alternative:t("Отделить нарушение памяти от влияния внимания, понимания инструкции и речевого ответа.","Distinguish memory impairment from effects of attention, instruction comprehension, and language output.","Жад бұзылысын зейін, нұсқауды түсіну және сөйлеу жауабының әсерінен ажырату.")};
 if(id===25)return{role:t("Пациент в период восстановления после функционального нарушения нервной системы","Patient recovering after a functional nervous-system disturbance","Жүйке жүйесінің функционалдық бұзылысынан кейін қалпына келіп жатқан пациент"),finding:t("При повторных тренировках функция постепенно улучшается, но перенос результата на новое задание остаётся неполным.","Function gradually improves with repeated training, but transfer to a new task remains incomplete.","Қайталама жаттығуларда функция біртіндеп жақсарады, бірақ нәтижені жаңа тапсырмаға көшіру толық емес."),test:t("Сравнить исходный уровень, динамику обучения, сохранение результата и перенос на новую задачу.","Compare baseline, learning trajectory, retention, and transfer to a new task.","Бастапқы деңгейді, үйрену динамикасын, нәтижені сақтауды және жаңа тапсырмаға көшіруді салыстыру."),alternative:t("Отделить специфическое научение заданию от более общей нейропластической перестройки функции.","Distinguish task-specific learning from broader neuroplastic reorganization of function.","Тапсырмаға тән үйренуді функцияның кеңірек нейропластикалық қайта құрылуынан ажырату.")};
 return{role:t("Пациент на нейрофизиологическом обследовании","Patient undergoing neurophysiological assessment","Нейрофизиологиялық тексерудегі пациент"),finding:t("В ходе задания меняется результат по сравнению с исходным состоянием.","Task performance changes relative to baseline.","Тапсырма барысында нәтиже бастапқы күймен салыстырғанда өзгереді."),test:t("Повторить задание с изменением одного условия и сравнить результат.","Repeat the task after changing one condition and compare the result.","Бір шартты өзгертіп, тапсырманы қайталап, нәтижені салыстыру."),alternative:t("Проверить альтернативное объяснение и указать пределы вывода.","Test an alternative explanation and state the limits of inference.","Балама түсіндіруді тексеріп, қорытынды шегін көрсету.")};
};

function ExamScene({moduleId,step,path,language}:{moduleId:number;step:number;path:"mechanism"|"alternative";language:Language}){
 const kind=moduleId===2?"signal":moduleId<=6?"cell":moduleId<=14?"motor":moduleId<=18?"regulation":moduleId<=21?"sensory":moduleId===22?"autonomic":"cognitive";
 const labels:{[key:string]:Record<Language,string>}={
 signal:{RU:"Монитор функциональной регистрации",EN:"Functional recording monitor",KZ:"Функционалдық тіркеу мониторы"},
 cell:{RU:"Нервно-мышечный ответ",EN:"Neuromuscular response",KZ:"Жүйке-бұлшықет жауабы"},
 motor:{RU:"Двигательная проба",EN:"Motor examination",KZ:"Қозғалыс сынағы"},
 regulation:{RU:"Регуляторная реакция",EN:"Regulatory response",KZ:"Реттеуші реакция"},
 sensory:{RU:"Сенсорная проба",EN:"Sensory examination",KZ:"Сенсорлық сынақ"},
 autonomic:{RU:"Вегетативный мониторинг",EN:"Autonomic monitoring",KZ:"Вегетативтік мониторинг"},
 cognitive:{RU:"Когнитивная проба",EN:"Cognitive task",KZ:"Когнитивтік сынақ"}};
 const amplitude=(path==="mechanism"?[28,55,78]:[28,43,61])[step];
 return <figure style={{margin:"16px 0",padding:16,borderRadius:18,background:"linear-gradient(145deg,#071a2c,#12364a)",color:"white",boxShadow:"0 10px 24px rgba(7,26,44,.18)"}}>
  <figcaption style={{fontWeight:800,marginBottom:12}}>{labels[kind][language]}</figcaption>
  <svg viewBox="0 0 640 190" role="img" aria-label={labels[kind][language]} style={{display:"block",width:"100%",borderRadius:12,background:"#06131f"}}>
   <defs><linearGradient id="vpGlow" x1="0" x2="1"><stop stopColor="#38bdf8"/><stop offset="1" stopColor="#4ade80"/></linearGradient></defs>
   <path d={`M10 105 C55 ${105-amplitude/2},85 ${105+amplitude/3},125 105 S190 ${105-amplitude},230 105 S300 ${105+amplitude/2},345 105 S410 ${105-amplitude*.8},455 105 S535 ${105+amplitude/2},630 105`} fill="none" stroke="url(#vpGlow)" strokeWidth="5" style={{transition:"all .5s ease"}}/>
   {kind==="motor"&&<><circle cx={110+step*120} cy={55} r="18" fill="#fbbf24"/><path d={`M${110+step*120} 73v48m0-30l-35 28m35-28l38 20m-38 14l-28 43m28-43l30 43`} stroke="#fde68a" strokeWidth="8" strokeLinecap="round"/></>}
   {kind==="sensory"&&[0,1,2,3,4].map(i=><circle key={i} cx={170+i*55} cy={55+(i%2)*12} r={9+step*3} fill={i<=step+1?"#f472b6":"#475569"}/>)}
   {kind==="autonomic"&&<><text x="28" y="45" fill="#bae6fd" fontSize="22">HR</text><text x="80" y="45" fill="white" fontSize="28">{72+step*(path==="mechanism"?9:5)}</text></>}
   {kind==="cognitive"&&<><rect x="475" y="28" width="120" height="48" rx="10" fill="#312e81"/><text x="495" y="60" fill="white" fontSize="20">{step===0?"BASE":step===1?"TASK":"RETEST"}</text></>}
  </svg>
 </figure>;
}

export default function FoundationVirtualPatient({moduleId,language}:{moduleId:number;language:Language}){
 const topic=topics.find(x=>x.id===moduleId);
 const [open,setOpen]=useState<boolean[]>([false,false,false]);
 const [answers,setAnswers]=useState(["","",""]);
 const [path,setPath]=useState<"mechanism"|"alternative"|null>(null);
 const [examStep,setExamStep]=useState(0);
 const [decision,setDecision]=useState<"support"|"challenge"|null>(null);
 const [revised,setRevised]=useState(false);
 if(!topic)return null;
 const c=ui[language], scenario=scenarioFor(moduleId), guides=[scenario.finding[language],topic.mechanism[language],topic.interpretation[language]];
 const speak=(value:string)=>{if(typeof window==="undefined"||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(value);u.lang={RU:"ru-RU",EN:"en-US",KZ:"kk-KZ"}[language];window.speechSynthesis.speak(u)};
 const teacher=path==="mechanism"?topic.mechanism[language]:path==="alternative"?topic.interpretation[language]:"";
 const pathResult=path==="mechanism"?scenario.test[language]:path==="alternative"?scenario.alternative[language]:"";
 const stateLabels=language==="RU"?["Исходное состояние","После первого шага","После проверки"]:language==="EN"?["Baseline","After first step","After verification"]:["Бастапқы күй","Бірінші қадамнан кейін","Тексеруден кейін"];
 const stateValues=path==="alternative"?[35,52,68]:[35,64,82];
 const decisionFeedback=decision==="support"?topic.mechanism[language]:decision==="challenge"?topic.interpretation[language]:"";
 return <section>
  <h1>{c.title}</h1><p>{c.intro}</p><p><strong>{scenario.role[language]}</strong></p>
  {moduleId===20&&<VisualPathwayLocalizer language={language}/>}
  <div style={{padding:18,border:"1px solid #b9d8e8",borderRadius:18,background:"linear-gradient(135deg,#e8f7ff,#f6f0ff)",margin:"18px 0"}}><strong>{scenario.finding[language]}</strong><div><button type="button" onClick={()=>speak(scenario.finding[language])} style={{marginTop:12}}>🔊 {language==="RU"?"Голос пациента":language==="EN"?"Patient voice":"Пациент дауысы"}</button></div></div>
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,margin:"18px 0"}}>
   <button type="button" onClick={()=>{setPath("mechanism");setExamStep(0);setDecision(null);setRevised(false)}} style={{padding:16,borderRadius:14,border:"1px solid #78aeca",background:path==="mechanism"?"#dff3ff":"white",fontWeight:700}}>{scenario.test[language]}</button>
   <button type="button" onClick={()=>{setPath("alternative");setExamStep(0);setDecision(null);setRevised(false)}} style={{padding:16,borderRadius:14,border:"1px solid #a993cf",background:path==="alternative"?"#eee6ff":"white",fontWeight:700}}>{scenario.alternative[language]}</button>
  </section>
  {path&&<>
   <section style={{padding:18,borderRadius:16,background:"#f5fbf7",border:"1px solid #b9d8c4",marginBottom:18}}>
    <h2 style={{marginTop:0}}>{language==="RU"?"Динамика обследования":language==="EN"?"Examination dynamics":"Тексеру динамикасы"}</h2>
    <p>{pathResult}</p>
    <ExamScene moduleId={moduleId} step={examStep} path={path} language={language} />
    <div aria-label={stateLabels[examStep]} style={{height:18,borderRadius:99,background:"#dce8ef",overflow:"hidden"}}><div style={{height:"100%",width:`${stateValues[examStep]}%`,background:"linear-gradient(90deg,#3b82f6,#22c55e)",transition:"width .5s ease"}} /></div>
    <p><strong>{stateLabels[examStep]}</strong> · {stateValues[examStep]}%</p>
    <button type="button" disabled={examStep>=2} onClick={()=>setExamStep(v=>Math.min(2,v+1))}>{language==="RU"?"Следующий этап обследования":language==="EN"?"Next examination step":"Тексерудің келесі кезеңі"}</button>
    {examStep>0&&<button type="button" onClick={()=>setExamStep(v=>Math.max(0,v-1))} style={{marginLeft:8}}>{language==="RU"?"Назад":language==="EN"?"Back":"Артқа"}</button>}
    {examStep===2&&<div style={{marginTop:18,paddingTop:16,borderTop:"1px solid #cbded2"}}>
     <strong>{language==="RU"?"Как вы интерпретируете результат?":language==="EN"?"How do you interpret the result?":"Нәтижені қалай түсіндіресіз?"}</strong>
     <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10,marginTop:10}}>
      <button type="button" onClick={()=>setDecision("support")} style={{padding:12,borderRadius:10}}>{language==="RU"?"Данные поддерживают механизм":language==="EN"?"Data support the mechanism":"Дерек тетікті қолдайды"}</button>
      <button type="button" onClick={()=>setDecision("challenge")} style={{padding:12,borderRadius:10}}>{language==="RU"?"Нужно проверить альтернативу":language==="EN"?"Test an alternative":"Баламаны тексеру керек"}</button>
     </div>
     {decision&&<div style={{marginTop:12,padding:12,borderRadius:10,background:"#fff7dc"}}>
      <strong>{language==="RU"?"Комментарий преподавателя":language==="EN"?"Teacher feedback":"Оқытушы пікірі"}</strong><p>{decisionFeedback}</p>
      <button type="button" onClick={()=>speak(decisionFeedback)}>🔊 {language==="RU"?"Озвучить":language==="EN"?"Speak":"Дыбыстау"}</button>
      <button type="button" onClick={()=>{setDecision(null);setExamStep(1);setRevised(true)}} style={{marginLeft:8}}>{language==="RU"?"Вернуться и исправить решение":language==="EN"?"Go back and revise":"Артқа оралып, шешімді түзету"}</button>
      {revised&&<p><strong>{language==="RU"?"Повторная попытка отмечена: сравните новое решение с первым.":language==="EN"?"Revision recorded: compare the new decision with your first one.":"Қайталау белгіленді: жаңа шешімді алғашқы шешіммен салыстырыңыз."}</strong></p>}
     </div>}
    </div>}
   </section>
   <aside style={{padding:14,borderRadius:14,background:"#fff7dc",border:"1px solid #e8cf75",marginBottom:18}}><strong>{language==="RU"?"Комментарий преподавателя":language==="EN"?"Teacher feedback":"Оқытушы пікірі"}</strong><p>{teacher}</p><button type="button" onClick={()=>speak(teacher)}>🔊 {language==="RU"?"Озвучить комментарий":language==="EN"?"Speak feedback":"Пікірді дыбыстау"}</button></aside>
  </>}
  {c.stage.map((title,i)=><section key={title} style={{margin:"18px 0",padding:18,border:"1px solid #dce8ef",borderRadius:16}}>
   <h2 style={{marginTop:0}}>{title}</h2><p>{c.prompt[i]}</p>
   <VoiceTextarea language={language} aria-label={c.prompt[i]} placeholder={c.note} value={answers[i]} onValue={value=>setAnswers(v=>v.map((x,j)=>j===i?value:x))} style={{width:"100%",minHeight:100,padding:12,border:"1px solid #bfd0dc",borderRadius:10}} />
   <button type="button" onClick={()=>setOpen(v=>v.map((x,j)=>j===i?!x:x))} style={{marginTop:10,padding:"9px 13px",fontWeight:700}}>{open[i]?c.hide:c.show}</button>
   {open[i]&&<div style={{marginTop:12,padding:12,background:"#eef6fa",borderRadius:10}}><strong>{c.answer}</strong><p>{guides[i]}</p></div>}
  </section>)}
 </section>;
}
