"use client";

import {useState,type ReactNode} from "react";
import type {Language} from "../content/course";
import styles from "./GuidedLabFrame.module.css";

const prompts={
 10:{RU:"Как изменение сенсорного входа повлияет на восходящую ретикулярную активацию и почему?",KZ:"Сенсорлық кірістің өзгеруі жоғарылаушы ретикулярлық белсендіруге қалай және неліктен әсер етеді?",EN:"How will changing sensory input affect ascending reticular activation, and why?"},
 11:{RU:"Как сенсорная обратная связь изменит ошибку движения при неизменной нисходящей команде?",KZ:"Төмендейтін команда өзгермегенде сенсорлық кері байланыс қозғалыс қатесін қалай өзгертеді?",EN:"How will sensory feedback change movement error while descending drive is held constant?"},
 12:{RU:"Как снижение дофаминовой модуляции изменит баланс прямого и непрямого путей?",KZ:"Дофаминдік модуляцияның төмендеуі тікелей және жанама жолдардың теңгерімін қалай өзгертеді?",EN:"How will reduced dopaminergic modulation change the balance of the direct and indirect pathways?"},
 13:{RU:"Как качество сенсорной обратной связи повлияет на коррекцию и остаточную ошибку?",KZ:"Сенсорлық кері байланыс сапасы түзетуге және қалдық қатеге қалай әсер етеді?",EN:"How will sensory-feedback quality affect correction and residual error?"},
 14:{RU:"Как изменение таламического воротного контроля повлияет на передачу сигнала к коре?",KZ:"Таламустық қақпалық бақылаудың өзгеруі сигналдың қыртысқа берілуіне қалай әсер етеді?",EN:"How will changing thalamic gating affect signal relay to cortex?"},
 15:{RU:"Как усиление отрицательной обратной связи изменит отклонение регулируемой величины?",KZ:"Теріс кері байланыстың күшеюі реттелетін шаманың ауытқуын қалай өзгертеді?",EN:"How will stronger negative feedback change deviation of the regulated variable?"},
 16:{RU:"Как контекст изменит поведенческую значимость эмоционального сигнала?",KZ:"Контекст эмоциялық сигналдың мінез-құлықтық маңыздылығын қалай өзгертеді?",EN:"How will context alter the behavioral significance of an emotional signal?"},
 17:{RU:"Как обучение безопасности и угасание изменят условный ответ на угрозу?",KZ:"Қауіпсіздікті үйрену мен сөну қауіпке шартты жауапты қалай өзгертеді?",EN:"How will safety learning and extinction alter a conditioned threat response?"},
 18:{RU:"Как торможение окружения изменит контраст популяционного коркового ответа?",KZ:"Айналаның тежелуі қыртыстық популяциялық жауап контрастын қалай өзгертеді?",EN:"How will surround inhibition alter the contrast of a cortical population response?"},
 19:{RU:"Как размер рецептивного поля повлияет на двухточечное различение?",KZ:"Рецептивтік өріс өлшемі екі нүктені ажыратуға қалай әсер етеді?",EN:"How will receptive-field size affect two-point discrimination?"},
 20:{RU:"Как изменение яркости и контраста повлияет на адаптированный сигнал сетчатки?",KZ:"Жарықтылық пен контрасттың өзгеруі торқабықтың бейімделген сигналына қалай әсер етеді?",EN:"How will changes in luminance and contrast affect the adapted retinal signal?"},
 21:{RU:"Как адаптация или конкурирующий вход изменят ответ выбранной сенсорной системы?",KZ:"Бейімделу немесе бәсекелес кіріс таңдалған сенсорлық жүйенің жауабын қалай өзгертеді?",EN:"How will adaptation or competing input change the response of the selected sensory system?"},
 22:{RU:"Почему усиление симпатического влияния нельзя считать универсальным ослаблением парасимпатического во всех органах?",KZ:"Неліктен симпатикалық ықпалдың күшеюін барлық мүшеде парасимпатикалық ықпалдың әмбебап әлсіреуі деп санауға болмайды?",EN:"Why can increased sympathetic drive not be treated as universal suppression of parasympathetic activity in every organ?"}
} as const;
const clinical={
 10:{RU:"Клиническая связь: двустороннее повреждение восходящих систем активации может глубоко нарушать бодрствование, но уровень сознания определяется распределённой сетью.",KZ:"Клиникалық байланыс: жоғарылаушы белсендіру жүйелерінің екіжақты зақымы сергектікті ауыр бұзуы мүмкін, бірақ сана деңгейін таралған желі анықтайды.",EN:"Clinical link: bilateral injury to ascending arousal systems can profoundly impair wakefulness, although consciousness depends on a distributed network."},
 11:{RU:"Клиническая связь: дефицит нисходящего контроля и сенсорной обратной связи по-разному нарушает точность движения.",KZ:"Клиникалық байланыс: төмендейтін бақылау мен сенсорлық кері байланыс тапшылығы қозғалыс дәлдігін әртүрлі бұзады.",EN:"Clinical link: deficits of descending control and sensory feedback impair movement accuracy in different ways."},
 12:{RU:"Клиническая связь: при болезни Паркинсона потеря нигростриарного дофамина смещает сетевой баланс в сторону снижения облегчения движения.",KZ:"Клиникалық байланыс: Паркинсон ауруында нигростриарлық дофаминнің азаюы желілік теңгерімді қозғалысты жеңілдетудің төмендеуіне ығыстырады.",EN:"Clinical link: in Parkinson disease, loss of nigrostriatal dopamine shifts network balance toward reduced facilitation of movement."},
 13:{RU:"Клиническая связь: мозжечковые поражения вызывают дисметрию и нарушение коррекции текущего движения, а не первичный паралич.",KZ:"Клиникалық байланыс: мишық зақымы бастапқы салдануды емес, дисметрияны және ағымдағы қозғалысты түзетудің бұзылуын туғызады.",EN:"Clinical link: cerebellar lesions cause dysmetria and impaired online correction rather than primary paralysis."},
 14:{RU:"Клиническая связь: таламические поражения могут нарушать сенсорную передачу, внимание и состояние сознания в зависимости от локализации.",KZ:"Клиникалық байланыс: таламус зақымы орналасуына қарай сенсорлық берілісті, зейінді және сана күйін бұзуы мүмкін.",EN:"Clinical link: depending on location, thalamic lesions can disrupt sensory relay, attention, and consciousness."},
 15:{RU:"Клиническая связь: нарушения гипоталамической регуляции могут затрагивать температуру, водный баланс, питание и эндокринные оси.",KZ:"Клиникалық байланыс: гипоталамустық реттелудің бұзылыстары температураға, су теңгеріміне, тамақтануға және эндокриндік осьтерге әсер етуі мүмкін.",EN:"Clinical link: hypothalamic dysregulation may affect temperature, water balance, feeding, and endocrine axes."},
 16:{RU:"Клиническая связь: нарушения лимбико-корковых сетей могут менять мотивацию, эмоциональное обучение и контекстную регуляцию поведения.",KZ:"Клиникалық байланыс: лимбиялық-қыртыстық желілер бұзылса, мотивация, эмоциялық үйрену және мінез-құлықтың контекстік реттелуі өзгеруі мүмкін.",EN:"Clinical link: disruption of limbic–cortical networks may alter motivation, emotional learning, and contextual regulation of behavior."},
 17:{RU:"Клиническая связь: нарушение угасания страха и префронтальной регуляции миндалины связано с тревожными и травматическими расстройствами.",KZ:"Клиникалық байланыс: қорқыныштың сөнуі мен миндалинаның префронталдық реттелуінің бұзылысы мазасыздық және жарақаттық бұзылыстармен байланысты.",EN:"Clinical link: impaired fear extinction and prefrontal regulation of the amygdala are relevant to anxiety and trauma-related disorders."},
 18:{RU:"Клиническая связь: очаговое поражение коры вызывает дефицит, зависящий от локализации и сетевых связей, а не единый корковый синдром.",KZ:"Клиникалық байланыс: қыртыстың ошақтық зақымы бірыңғай синдромды емес, орналасу мен желілік байланыстарға тәуелді тапшылықты туғызады.",EN:"Clinical link: focal cortical injury causes deficits determined by location and network connections rather than one uniform cortical syndrome."},
 19:{RU:"Клиническая связь: двухточечное различение зависит от участка тела, периферической иннервации и центральной обработки; это не самостоятельный диагноз.",KZ:"Клиникалық байланыс: екі нүктені ажырату дене аймағына, шеткі иннервацияға және орталық өңдеуге тәуелді; ол жеке диагноз емес.",EN:"Clinical link: two-point discrimination depends on body region, peripheral innervation, and central processing; it is not a diagnosis by itself."},
 20:{RU:"Клиническая связь: нарушения фоторецепторов, сетчатки, зрительного нерва и коры дают разные дефекты; единый индекс не локализует поражение.",KZ:"Клиникалық байланыс: фоторецепторлар, торқабық, көру жүйкесі және қыртыс зақымдары әртүрлі тапшылық береді; бір индекс зақымды локализацияламайды.",EN:"Clinical link: photoreceptor, retinal, optic-nerve, and cortical disorders produce different deficits; one response index cannot localize a lesion."},
 21:{RU:"Клиническая связь: слух, равновесие, вкус и обоняние используют разные рецепторы и пути, поэтому адаптацию интерпретируют по модальности.",KZ:"Клиникалық байланыс: есту, тепе-теңдік, дәм және иіс әртүрлі рецепторлар мен жолдарды қолданады, сондықтан бейімделу модальдық бойынша түсіндіріледі.",EN:"Clinical link: hearing, balance, taste, and smell use distinct receptors and pathways, so adaptation must be interpreted by modality."},
 22:{RU:"Клиническая связь: автономная недостаточность может проявляться ортостатической гипотензией и нарушениями потоотделения, моторики ЖКТ и мочеиспускания.",KZ:"Клиникалық байланыс: автономдық жеткіліксіздік ортостатикалық гипотензиямен, терлеу, асқазан-ішек моторикасы және зәр шығару бұзылыстарымен көрінуі мүмкін.",EN:"Clinical link: autonomic failure may cause orthostatic hypotension and disturbances of sweating, gastrointestinal motility, and urination."}
} as const;
const ui={RU:{heading:"Прогноз → эксперимент → объяснение",label:"Ваш причинно-следственный прогноз",start:"Перейти к эксперименту",replay:"Новый прогноз",result:"Сопоставьте наблюдаемый результат с прогнозом и объясните механизм."},KZ:{heading:"Болжам → тәжірибе → түсіндіру",label:"Себеп-салдарлық болжамыңыз",start:"Тәжірибеге өту",replay:"Жаңа болжам",result:"Бақыланған нәтижені болжаммен салыстырып, механизмді түсіндіріңіз."},EN:{heading:"Prediction → experiment → explanation",label:"Your cause-and-effect prediction",start:"Proceed to experiment",replay:"New prediction",result:"Compare the observed result with your prediction and explain the mechanism."}} as const;

export default function GuidedLabFrame({moduleId,language,children}:{moduleId:keyof typeof prompts;language:Language;children:ReactNode}){const t=ui[language],[prediction,setPrediction]=useState(""),[started,setStarted]=useState(false);return <div className={styles.frame} data-testid={`guided-lab-${moduleId}`}><section className={styles.predict}><h2>{t.heading}</h2><p>{prompts[moduleId][language]}</p><label>{t.label}<textarea rows={3} value={prediction} onChange={event=>setPrediction(event.target.value)}/></label><button type="button" disabled={!prediction.trim()} onClick={()=>setStarted(true)}>{t.start}</button></section>{started&&<><div className={styles.experiment}>{children}</div><aside className={styles.result}><strong>{t.result}</strong><p>{clinical[moduleId][language]}</p><button type="button" onClick={()=>{setStarted(false);setPrediction("")}}>{t.replay}</button></aside></>}</div>}
