"use client";

import {useState,type ReactNode} from "react";
import type {Language} from "../content/course";
import styles from "./GuidedLabFrame.module.css";

const prompts={
 10:{RU:"Как изменение сенсорного входа повлияет на восходящую ретикулярную активацию и почему?",KZ:"Сенсорлық кірістің өзгеруі жоғарылаушы ретикулярлық белсендіруге қалай және неліктен әсер етеді?",EN:"How will changing sensory input affect ascending reticular activation, and why?"},
 11:{RU:"Как сенсорная обратная связь изменит ошибку движения при неизменной нисходящей команде?",KZ:"Төмендейтін команда өзгермегенде сенсорлық кері байланыс қозғалыс қатесін қалай өзгертеді?",EN:"How will sensory feedback change movement error while descending drive is held constant?"},
 12:{RU:"Как снижение дофаминовой модуляции изменит баланс прямого и непрямого путей?",KZ:"Дофаминдік модуляцияның төмендеуі тікелей және жанама жолдардың теңгерімін қалай өзгертеді?",EN:"How will reduced dopaminergic modulation change the balance of the direct and indirect pathways?"},
 13:{RU:"Как качество сенсорной обратной связи повлияет на коррекцию и остаточную ошибку?",KZ:"Сенсорлық кері байланыс сапасы түзетуге және қалдық қатеге қалай әсер етеді?",EN:"How will sensory-feedback quality affect correction and residual error?"},
 14:{RU:"Как изменение таламического воротного контроля повлияет на передачу сигнала к коре?",KZ:"Таламустық қақпалық бақылаудың өзгеруі сигналдың қыртысқа берілуіне қалай әсер етеді?",EN:"How will changing thalamic gating affect signal relay to cortex?"},
 15:{RU:"Как усиление отрицательной обратной связи изменит отклонение регулируемой величины?",KZ:"Теріс кері байланыстың күшеюі реттелетін шаманың ауытқуын қалай өзгертеді?",EN:"How will stronger negative feedback change deviation of the regulated variable?"}
} as const;
const clinical={
 10:{RU:"Клиническая связь: двустороннее повреждение восходящих систем активации может глубоко нарушать бодрствование, но уровень сознания определяется распределённой сетью.",KZ:"Клиникалық байланыс: жоғарылаушы белсендіру жүйелерінің екіжақты зақымы сергектікті ауыр бұзуы мүмкін, бірақ сана деңгейін таралған желі анықтайды.",EN:"Clinical link: bilateral injury to ascending arousal systems can profoundly impair wakefulness, although consciousness depends on a distributed network."},
 11:{RU:"Клиническая связь: дефицит нисходящего контроля и сенсорной обратной связи по-разному нарушает точность движения.",KZ:"Клиникалық байланыс: төмендейтін бақылау мен сенсорлық кері байланыс тапшылығы қозғалыс дәлдігін әртүрлі бұзады.",EN:"Clinical link: deficits of descending control and sensory feedback impair movement accuracy in different ways."},
 12:{RU:"Клиническая связь: при болезни Паркинсона потеря нигростриарного дофамина смещает сетевой баланс в сторону снижения облегчения движения.",KZ:"Клиникалық байланыс: Паркинсон ауруында нигростриарлық дофаминнің азаюы желілік теңгерімді қозғалысты жеңілдетудің төмендеуіне ығыстырады.",EN:"Clinical link: in Parkinson disease, loss of nigrostriatal dopamine shifts network balance toward reduced facilitation of movement."},
 13:{RU:"Клиническая связь: мозжечковые поражения вызывают дисметрию и нарушение коррекции текущего движения, а не первичный паралич.",KZ:"Клиникалық байланыс: мишық зақымы бастапқы салдануды емес, дисметрияны және ағымдағы қозғалысты түзетудің бұзылуын туғызады.",EN:"Clinical link: cerebellar lesions cause dysmetria and impaired online correction rather than primary paralysis."},
 14:{RU:"Клиническая связь: таламические поражения могут нарушать сенсорную передачу, внимание и состояние сознания в зависимости от локализации.",KZ:"Клиникалық байланыс: таламус зақымы орналасуына қарай сенсорлық берілісті, зейінді және сана күйін бұзуы мүмкін.",EN:"Clinical link: depending on location, thalamic lesions can disrupt sensory relay, attention, and consciousness."},
 15:{RU:"Клиническая связь: нарушения гипоталамической регуляции могут затрагивать температуру, водный баланс, питание и эндокринные оси.",KZ:"Клиникалық байланыс: гипоталамустық реттелудің бұзылыстары температураға, су теңгеріміне, тамақтануға және эндокриндік осьтерге әсер етуі мүмкін.",EN:"Clinical link: hypothalamic dysregulation may affect temperature, water balance, feeding, and endocrine axes."}
} as const;
const ui={RU:{heading:"Прогноз → эксперимент → объяснение",label:"Ваш причинно-следственный прогноз",start:"Перейти к эксперименту",replay:"Новый прогноз",result:"Сопоставьте наблюдаемый результат с прогнозом и объясните механизм."},KZ:{heading:"Болжам → тәжірибе → түсіндіру",label:"Себеп-салдарлық болжамыңыз",start:"Тәжірибеге өту",replay:"Жаңа болжам",result:"Бақыланған нәтижені болжаммен салыстырып, механизмді түсіндіріңіз."},EN:{heading:"Prediction → experiment → explanation",label:"Your cause-and-effect prediction",start:"Proceed to experiment",replay:"New prediction",result:"Compare the observed result with your prediction and explain the mechanism."}} as const;

export default function GuidedLabFrame({moduleId,language,children}:{moduleId:10|11|12|13|14|15;language:Language;children:ReactNode}){const t=ui[language],[prediction,setPrediction]=useState(""),[started,setStarted]=useState(false);return <div className={styles.frame} data-testid={`guided-lab-${moduleId}`}><section className={styles.predict}><h2>{t.heading}</h2><p>{prompts[moduleId][language]}</p><label>{t.label}<textarea rows={3} value={prediction} onChange={event=>setPrediction(event.target.value)}/></label><button type="button" disabled={!prediction.trim()} onClick={()=>setStarted(true)}>{t.start}</button></section>{started&&<><div className={styles.experiment}>{children}</div><aside className={styles.result}><strong>{t.result}</strong><p>{clinical[moduleId][language]}</p><button type="button" onClick={()=>{setStarted(false);setPrediction("")}}>{t.replay}</button></aside></>}</div>}
