"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
import AnatomyReference from "./AnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Гипоталамический гомеостаз",a:"Отклонение от установочной точки",b:"Коэффициент обратной связи",c:"Корригирующий ответ",d:"Остаточное отклонение",task:"Сформулируйте прогноз. Измените один параметр, сохранив второй постоянным; затем поменяйте второй и сравните результаты.",save:"Записать опыт",prediction:"Прогноз перед опытом",note:"Физиологическое объяснение",limit:"Отрицательная обратная связь обычно уменьшает ошибку регулируемой величины, но не все гипоталамические контуры имеют одну фиксированную «установочную точку». Температура, осмоляльность, энергетический баланс и эндокринные оси используют разные датчики, эффекторные пути и динамические диапазоны; некоторые регулируемые уровни меняются с циркадным состоянием и контекстом. Здесь показан общий принцип обратной связи, а не универсальная формула гипоталамуса; проценты условны."},EN:{title:"Hypothalamic homeostasis",a:"Set-point deviation",b:"Feedback gain",c:"Corrective response",d:"Residual deviation",task:"Make a prediction. Change one parameter while holding the other constant, then change the second and compare results.",save:"Record trial",prediction:"Prediction before trial",note:"Physiological explanation",limit:"Negative feedback commonly reduces error in a regulated variable, but hypothalamic control cannot be reduced to one fixed universal “set point.” Temperature, osmolality, energy balance, and endocrine axes use different sensors, effectors, and dynamic ranges, and some regulated levels vary with circadian state and context. This model shows a general feedback principle, not a universal hypothalamic equation; percentages are modeled."},KZ:{title:"Гипоталамустық гомеостаз",a:"Орнату нүктесінен ауытқу",b:"Кері байланыс коэффициенті",c:"Түзетуші жауап",d:"Қалдық ауытқу",task:"Алдымен болжам жасаңыз. Бір параметрді тұрақты екіншісінде өзгертіңіз, кейін екіншісін өзгертіп нәтижелерді салыстырыңыз.",save:"Тәжірибені жазу",prediction:"Тәжірибеге дейінгі болжам",note:"Физиологиялық түсіндірме",limit:"Теріс кері байланыс әдетте реттелетін шаманың қатесін азайтады, бірақ гипоталамустық реттелуді бір ғана тұрақты әмбебап «орнату нүктесіне» келтіруге болмайды. Температура, осмолялдық, энергия теңгерімі және эндокриндік осьтер әртүрлі сенсорлар, эффекторлар және динамикалық диапазондарды қолданады; кейбір реттелетін деңгейлер циркадтық күй мен контекстке қарай өзгереді. Бұл модель гипоталамустың әмбебап формуласын емес, кері байланыстың жалпы қағидасын көрсетеді; пайыздар шартты."}} as const;
function calc(a:number,b:number){return Math.max(0,Math.round(a*(1-b/125)));}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(60),[b,setB]=useState(50),[prediction,setPrediction]=useState(""),[rows,setRows]=useState<Row[]>([]);const out=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AnatomyReference moduleId={15} language={language}/><p><strong>{t.task}</strong></p><label>{t.prediction}<textarea value={prediction} onChange={e=>setPrediction(e.target.value)} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a}%<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b}%<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 190" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><defs><marker id="arr15" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8Z" fill="currentColor"/></marker></defs><circle cx="80" cy="90" r={18+a/7} fill="none" stroke="currentColor" strokeWidth="3"/><path d="M115 90 H290" stroke="currentColor" strokeWidth={2+a/30} markerEnd="url(#arr15)"/><rect x="300" y="52" width="130" height="76" rx="22" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M430 90 H575" stroke="currentColor" strokeWidth={2+out/30} markerEnd="url(#arr15)"/><circle cx="610" cy="90" r={12+out/8} fill="none" stroke="currentColor" strokeWidth="3"/><text x="315" y="82">{t.c}</text><text x="315" y="108">{out}%</text><text x="475" y="55">{t.d}</text></svg><button disabled={!prediction.trim()} onClick={()=>{recordOutcome(15,"interactive",1,1);recordOutcome(15,"criterion:application:lab",1,1);setRows(r=>[...r,{id:Date.now(),a,b,out,note:""}])}}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.c}</th><th>{t.note}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}</td><td>{r.b}</td><td>{r.out}%</td><td><input value={r.note} onChange={e=>{const note=e.target.value;setRows(xs=>xs.map(q=>q.id===r.id?{...q,note}:q));if(note.trim().length>=30)recordOutcome(15,"criterion:justification:lab",1,1)}}/></td></tr>)}</tbody></table></div><ExperimentReflection language={language} theoryHref={`/modules/15/theory?lang=${language}`}/><p><small>{t.limit}</small></p></section>}
