"use client";

import {useEffect,useRef,useState} from "react";
import type {Language} from "../content/course";
import VoiceIcon from "./VoiceIcon";
import styles from "./InteractiveVoiceDock.module.css";

type Editable=HTMLTextAreaElement|HTMLInputElement;
type Result={isFinal:boolean;[index:number]:{transcript:string}};
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onstart:(()=>void)|null;onresult:((event:{resultIndex:number;results:ArrayLike<Result>})=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null;start():void;stop():void;abort():void};
type RecognitionWindow=Window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
type Status="idle"|"listening"|"recognising"|"done"|"error"|"denied"|"unsupported";

const copy={
 RU:{title:"Голосовой ответ",target:"Поле ответа",draft:"Черновик голосового ответа",hint:"Сначала установите курсор в поле прогноза или объяснения. Если поле не выбрано, текст останется в редактируемом черновике.",start:"Включить микрофон",stop:"Выключить микрофон",idle:"Готово к вводу",listening:"Слушает…",recognising:"Распознаёт…",done:"Готово — проверьте и исправьте текст.",error:"Ошибка распознавания. Проверьте микрофон, соединение и язык.",denied:"Нет доступа к микрофону. Разрешите его в браузере или введите текст вручную.",unsupported:"SpeechRecognition недоступен. Поля остаются доступными для ручного ввода.",none:"черновик"},
 EN:{title:"Voice answer",target:"Answer field",draft:"Voice-answer draft",hint:"Place the cursor in a prediction or explanation field first. Without a selected field, text stays in the editable draft.",start:"Turn microphone on",stop:"Turn microphone off",idle:"Ready for input",listening:"Listening…",recognising:"Recognising…",done:"Done — review and correct the text.",error:"Recognition error. Check the microphone, connection, and language.",denied:"Microphone access is unavailable. Allow it in the browser or type manually.",unsupported:"SpeechRecognition is unavailable. All fields remain available for manual input.",none:"draft"},
 KZ:{title:"Дауыстық жауап",target:"Жауап өрісі",draft:"Дауыстық жауаптың нобайы",hint:"Алдымен болжам немесе түсіндіру өрісіне курсорды қойыңыз. Өріс таңдалмаса, мәтін түзетілетін нобайда қалады.",start:"Микрофонды қосу",stop:"Микрофонды өшіру",idle:"Енгізуге дайын",listening:"Тыңдап тұр…",recognising:"Танып жатыр…",done:"Дайын — мәтінді тексеріп, түзетіңіз.",error:"Тану қатесі. Микрофонды, байланысты және тілді тексеріңіз.",denied:"Микрофонға рұқсат жоқ. Браузерде рұқсат беріңіз немесе қолмен жазыңыз.",unsupported:"SpeechRecognition қолжетімсіз. Өрістерге қолмен мәтін енгізуге болады.",none:"нобай"}
} as const;

function fieldName(field:Editable|null,fallback:string){if(!field)return fallback;const labelled=field.getAttribute("aria-label");if(labelled)return labelled;const id=field.id;const label=id?document.querySelector(`label[for="${CSS.escape(id)}"]`)?.textContent:null;return label?.trim()||field.closest("label")?.textContent?.trim().slice(0,80)||fallback}
function updateField(field:Editable,value:string){const prototype=field instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,"value")?.set?.call(field,value);field.dispatchEvent(new Event("input",{bubbles:true}));field.focus()}

export default function InteractiveVoiceDock({language,contentId}:{language:Language;contentId:string}){
 const c=copy[language],recognition=useRef<Recognition|null>(null),target=useRef<Editable|null>(null),[targetLabel,setTargetLabel]=useState<string>(c.none),[draft,setDraft]=useState(""),[status,setStatus]=useState<Status>("idle"),[supported,setSupported]=useState<boolean|null>(null);
 useEffect(()=>{const browser=window as RecognitionWindow;setSupported(Boolean(browser.SpeechRecognition||browser.webkitSpeechRecognition));const root=document.getElementById(contentId);const focus=(event:FocusEvent)=>{const node=event.target;if(node instanceof HTMLTextAreaElement||(node instanceof HTMLInputElement&&["text","search"].includes(node.type))){target.current=node;setTargetLabel(fieldName(node,c.none))}};root?.addEventListener("focusin",focus);return()=>{root?.removeEventListener("focusin",focus);recognition.current?.abort();recognition.current=null}},[contentId,c.none,language]);
 function toggle(){if(recognition.current){recognition.current.stop();setStatus("recognising");return}const browser=window as RecognitionWindow,Constructor=browser.SpeechRecognition||browser.webkitSpeechRecognition;if(!Constructor){setStatus("unsupported");return}window.dispatchEvent(new Event("neuro-speech-stop"));window.dispatchEvent(new Event("neuro-dictation-stop"));const instance=new Constructor();recognition.current=instance;instance.lang={RU:"ru-RU",KZ:"kk-KZ",EN:"en-US"}[language];instance.continuous=false;instance.interimResults=true;let finalText="";instance.onstart=()=>setStatus("listening");instance.onresult=event=>{setStatus("recognising");for(let i=event.resultIndex;i<event.results.length;i++)if(event.results[i].isFinal)finalText+=`${event.results[i][0].transcript} `};instance.onerror=event=>{if(event.error!=="aborted")setStatus(event.error==="not-allowed"||event.error==="service-not-allowed"?"denied":"error")};instance.onend=()=>{recognition.current=null;const text=finalText.trim();if(text){const field=target.current;if(field){const next=`${field.value.trimEnd()}${field.value.trim()?" ":""}${text}`;updateField(field,next)}else setDraft(value=>`${value.trimEnd()}${value.trim()?" ":""}${text}`);setStatus("done")}else setStatus(value=>value==="error"||value==="denied"?value:"idle")};try{instance.start()}catch{recognition.current=null;setStatus("error")}}
 const active=status==="listening"||status==="recognising";
 return <section className={styles.dock} aria-label={c.title} data-testid="interactive-voice-dock" data-no-narration><div className={styles.heading}><strong>{c.title}</strong><span>{c.target}: {targetLabel}</span></div><p>{c.hint}</p><textarea aria-label={c.draft} rows={2} value={draft} onFocus={()=>{target.current=null;setTargetLabel(c.none)}} onChange={event=>setDraft(event.target.value)}/><button type="button" aria-pressed={active} disabled={supported===false} onClick={toggle}><VoiceIcon kind="microphone"/>{active?c.stop:c.start}</button><p role="status" aria-live="polite">{supported===false?c.unsupported:c[status]}</p></section>
}
