"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import AdvancedAnatomyReference from "./AdvancedAnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Лаборатория обучения и памяти",a:"Повторения обучения",b:"Интерференция",out:"Условный индекс сохранения",predict:"Прогноз",task:"Сначала сформулируйте прогноз. Затем изменяйте только один параметр за опыт, запишите результат и объясните механизм.",save:"Записать опыт",explain:"Объяснение",limit:"Концептуальная учебная модель иллюстрирует влияние повторения и интерференции, но не измеряет объём памяти конкретного человека; индекс является условным."},EN:{title:"Learning and memory laboratory",a:"Training repetitions",b:"Interference",out:"Modeled retention index",predict:"Prediction",task:"Make a prediction first. Then change only one parameter per trial, record the result, and explain the mechanism.",save:"Record trial",explain:"Explanation",limit:"This conceptual teaching model illustrates repetition and interference; it does not quantify an individual's memory capacity, and the index is modeled."},KZ:{title:"Оқу және жады зертханасы",a:"Оқу қайталанымдары",b:"Интерференция",out:"Шартты сақтау индексі",predict:"Болжам",task:"Алдымен болжам жасаңыз. Әр тәжірибеде тек бір параметрді өзгертіп, нәтижені жазып, механизмді түсіндіріңіз.",save:"Тәжірибені жазу",explain:"Түсіндірме",limit:"Тұжырымдамалық оқу моделі қайталау мен интерференция ықпалын көрсетеді, бірақ нақты адамның жады көлемін өлшемейді; индекс шартты."}} as const;
function calc(a:number,b:number){return Math.max(0,Math.min(100,Math.round(a*.9-b*.55)));}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(60),[b,setB]=useState(40),[prediction,setPrediction]=useState(""),[rows,setRows]=useState<Row[]>([]);const value=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AdvancedAnatomyReference moduleId={23} language={language}/><p><strong>{t.task}</strong></p><label>{t.predict}<textarea value={prediction} onChange={e=>setPrediction(e.target.value)} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a}%<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b}%<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 180" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><path d="M60 90 H250" stroke="currentColor" strokeWidth={2+a/25}/><circle cx="310" cy="90" r="42" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M352 90 H555" stroke="currentColor" strokeWidth={2+value/25}/><circle cx="600" cy="90" r={12+value/9} fill="none" stroke="currentColor" strokeWidth="3"/><text x="255" y="155">{t.out}: {value}%</text></svg><button disabled={!prediction.trim()} onClick={()=>setRows(r=>[...r,{id:Date.now(),a,b,out:value,note:""}])}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.out}</th><th>{t.explain}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}</td><td>{r.b}</td><td>{r.out}%</td><td><input value={r.note} onChange={e=>setRows(xs=>xs.map(q=>q.id===r.id?{...q,note:e.target.value}:q))}/></td></tr>)}</tbody></table></div><ExperimentReflection language={language} theoryHref={`/modules/23/theory?lang=${language}`}/><p><small>{t.limit}</small></p></section>}
