"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
import AdvancedAnatomyReference from "./AdvancedAnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Лаборатория обучения и памяти",a:"Повторения обучения",b:"Интерференция",out:"Условный индекс сохранения",predict:"Прогноз",task:"Сначала сформулируйте прогноз. Затем изменяйте только один параметр за опыт, запишите результат и объясните механизм.",save:"Записать опыт",explain:"Объяснение",limit:"Повторение само по себе не гарантирует долговременное сохранение: результат зависит от распределения повторений во времени, извлечения из памяти, глубины обработки, сна и консолидации, а интерференция может быть проактивной или ретроактивной. Разные виды памяти опираются на частично разные нейронные системы. Поэтому индекс показывает только учебное взаимодействие повторения и интерференции и не измеряет «объём памяти» человека."},EN:{title:"Learning and memory laboratory",a:"Training repetitions",b:"Interference",out:"Modeled retention index",predict:"Prediction",task:"Make a prediction first. Then change only one parameter per trial, record the result, and explain the mechanism.",save:"Record trial",explain:"Explanation",limit:"Repetition alone does not guarantee long-term retention: outcome depends on spacing, retrieval practice, depth of processing, sleep and consolidation, while interference can be proactive or retroactive. Different forms of memory rely on partly distinct neural systems. The index therefore illustrates only a teaching interaction between repetition and interference; it does not measure a person’s “memory capacity.”"},KZ:{title:"Оқу және жады зертханасы",a:"Оқу қайталанымдары",b:"Интерференция",out:"Шартты сақтау индексі",predict:"Болжам",task:"Алдымен болжам жасаңыз. Әр тәжірибеде тек бір параметрді өзгертіп, нәтижені жазып, механизмді түсіндіріңіз.",save:"Тәжірибені жазу",explain:"Түсіндірме",limit:"Қайталау өздігінен ұзақ мерзімді сақталуға кепіл болмайды: нәтиже қайталаудың уақыт бойынша бөлінуіне, жадтан белсенді еске түсіруге, өңдеу тереңдігіне, ұйқы мен консолидацияға тәуелді; интерференция проактивті немесе ретроактивті болуы мүмкін. Жадтың әр түрі ішінара әртүрлі нейрондық жүйелерге сүйенеді. Сондықтан индекс тек қайталау мен интерференцияның оқу үлгісіндегі өзара әсерін көрсетеді және адамның «жад көлемін» өлшемейді."}} as const;
function calc(a:number,b:number){return Math.max(0,Math.min(100,Math.round(a*.9-b*.55)));}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(60),[b,setB]=useState(40),[prediction,setPrediction]=useState(""),[rows,setRows]=useState<Row[]>([]);const value=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AdvancedAnatomyReference moduleId={23} language={language}/><p><strong>{t.task}</strong></p><label>{t.predict}<textarea value={prediction} onChange={e=>setPrediction(e.target.value)} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a}%<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b}%<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 180" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><path d="M60 90 H250" stroke="currentColor" strokeWidth={2+a/25}/><circle cx="310" cy="90" r="42" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M352 90 H555" stroke="currentColor" strokeWidth={2+value/25}/><circle cx="600" cy="90" r={12+value/9} fill="none" stroke="currentColor" strokeWidth="3"/><text x="255" y="155">{t.out}: {value}%</text></svg><button disabled={!prediction.trim()} onClick={()=>{setRows(r=>[...r,{id:Date.now(),a,b,out:value,note:""}]);recordOutcome(23,"interactive",prediction.trim().length>=20?1:0,1);recordOutcome(23,"criterion:mechanism:lab-prediction",prediction.trim().length>=20?1:0,1)}}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.out}</th><th>{t.explain}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}</td><td>{r.b}</td><td>{r.out}%</td><td><input value={r.note} onChange={e=>{const note=e.target.value;setRows(xs=>xs.map(q=>q.id===r.id?{...q,note}:q));if(note.trim().length>=30){recordOutcome(23,"criterion:justification:lab",1,1);recordOutcome(23,"criterion:correction:experiment-reflection",rows.length>=2?1:0,1)}}}/></td></tr>)}</tbody></table></div><ExperimentReflection language={language} theoryHref={`/modules/23/theory?lang=${language}`}/><p><small>{t.limit}</small></p></section>}
