"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import AnatomyReference from "./AnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Лимбическая интеграция",a:"Эмоциональная значимость",b:"Сила контекста",c:"Интегрированная значимость",d:"Поведенческая мотивация",task:"Сформулируйте прогноз. Измените один параметр, сохранив второй постоянным; затем поменяйте второй и сравните результаты.",save:"Записать опыт",prediction:"Прогноз перед опытом",note:"Физиологическое объяснение",limit:"Контекст и значимость взаимодействуют в распределённых лимбико-корковых сетях; единого измеримого «лимбического выхода» in vivo не существует. Это концептуальная учебная модель."},EN:{title:"Limbic integration",a:"Emotional salience",b:"Context strength",c:"Integrated salience",d:"Behavioral drive",task:"Make a prediction. Change one parameter while holding the other constant, then change the second and compare results.",save:"Record trial",prediction:"Prediction before trial",note:"Physiological explanation",limit:"Context and salience interact across distributed limbic-cortical networks; there is no single measurable 'limbic output' in vivo. This is a conceptual teaching model."},KZ:{title:"Лимбиялық интеграция",a:"Эмоциялық маңыздылық",b:"Контекст күші",c:"Біріктірілген маңыздылық",d:"Мінез-құлықтық түрткі",task:"Алдымен болжам жасаңыз. Бір параметрді тұрақты екіншісінде өзгертіңіз, кейін екіншісін өзгертіп нәтижелерді салыстырыңыз.",save:"Тәжірибені жазу",prediction:"Тәжірибеге дейінгі болжам",note:"Физиологиялық түсіндірме",limit:"Контекст пен маңыздылық таралған лимбиялық-қыртыстық желілерде өзара әрекеттеседі; in vivo бірыңғай өлшенетін «лимбиялық шығыс» жоқ. Бұл — тұжырымдамалық оқу моделі."}} as const;
function calc(a:number,b:number){return Math.min(100,Math.round(a*.65+b*.45));}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(60),[b,setB]=useState(50),[prediction,setPrediction]=useState(""),[rows,setRows]=useState<Row[]>([]);const out=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AnatomyReference moduleId={16} language={language}/><p><strong>{t.task}</strong></p><label>{t.prediction}<textarea value={prediction} onChange={e=>setPrediction(e.target.value)} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a}%<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b}%<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 190" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><defs><marker id="arr16" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8Z" fill="currentColor"/></marker></defs><circle cx="80" cy="90" r={18+a/7} fill="none" stroke="currentColor" strokeWidth="3"/><path d="M115 90 H290" stroke="currentColor" strokeWidth={2+a/30} markerEnd="url(#arr16)"/><rect x="300" y="52" width="130" height="76" rx="22" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M430 90 H575" stroke="currentColor" strokeWidth={2+out/30} markerEnd="url(#arr16)"/><circle cx="610" cy="90" r={12+out/8} fill="none" stroke="currentColor" strokeWidth="3"/><text x="315" y="82">{t.c}</text><text x="315" y="108">{out}%</text><text x="475" y="55">{t.d}</text></svg><button disabled={!prediction.trim()} onClick={()=>setRows(r=>[...r,{id:Date.now(),a,b,out,note:""}])}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.c}</th><th>{t.note}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}</td><td>{r.b}</td><td>{r.out}%</td><td><input value={r.note} onChange={e=>setRows(xs=>xs.map(q=>q.id===r.id?{...q,note:e.target.value}:q))}/></td></tr>)}</tbody></table></div><ExperimentReflection language={language} theoryHref={`/modules/16/theory?lang=${language}`}/><p><small>{t.limit}</small></p></section>}
