"use client";

import {useEffect,useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import styles from "./MembraneElectrophysiologyLab.module.css";

type Prediction="depolarize"|"hyperpolarize"|"noSpike";
const R=8.314,F=96485;
const nernst=(outside:number,inside:number,temp:number,z=1)=>1000*R*(temp+273.15)/(z*F)*Math.log(outside/inside);
const ghk=(ko:number,ki:number,nao:number,nai:number,pk:number,pna:number,temp:number)=>1000*R*(temp+273.15)/F*Math.log((pk*ko+pna*nao)/(pk*ki+pna*nai));
const copy={
 RU:{title:"Виртуальная электрофизиологическая лаборатория",intro:"Сначала сравните равновесные потенциалы, затем сформулируйте прогноз и запустите потенциал действия.",part1:"Часть 1 — Ионные градиенты и потенциал покоя",part2:"Часть 2 — Потенциал действия",ko:"[K⁺] снаружи",ki:"[K⁺] внутри",nao:"[Na⁺] снаружи",nai:"[Na⁺] внутри",temp:"Температура",pk:"P(K)",pna:"P(Na)",stim:"Сила стимула",interval:"Интервал после предыдущего ПД",predict:"Прогноз",depolarize:"Vm станет менее отрицательным",hyperpolarize:"Vm станет более отрицательным",noSpike:"ПД не возникнет",run:"Запустить эксперимент",pause:"Пауза",replay:"Повтор",rest:"Покой",threshold:"Порог",rise:"Деполяризация",fall:"Реполяризация",after:"Следовая гиперполяризация",absolute:"Абсолютная рефрактерность",relative:"Относительная рефрактерность",ready:"Возбудимость восстановлена",result:"Результат",correct:"Прогноз согласуется с моделью.",retry:"Сопоставьте стимул с порогом и интервал — с рефрактерностью.",clinical:"Клиническая связь",clinicalText:"Повышение внеклеточного K⁺ уменьшает калиевый градиент и обычно деполяризует Vm. Выраженная деполяризация может инактивировать Na⁺-каналы и снижать возбудимость — простой вывод «деполяризация всегда усиливает возбуждение» неверен.",teacher:"Объяснение преподавателя",model:"Учебная модель: Nernst и двухионное уравнение Goldman рассчитываются явно; форма ПД является динамической аппроксимацией, а не численным решением Hodgkin–Huxley.",ek:"E(K)",ena:"E(Na)",vm:"Vm по Goldman",phase:"Фаза"},
 KZ:{title:"Виртуалды электрофизиология зертханасы",intro:"Алдымен тепе-теңдік потенциалдарын салыстырып, кейін болжам жасап, әрекет потенциалын іске қосыңыз.",part1:"1-бөлім — Иондық градиенттер және тыныштық потенциалы",part2:"2-бөлім — Әрекет потенциалы",ko:"Сыртқы [K⁺]",ki:"Ішкі [K⁺]",nao:"Сыртқы [Na⁺]",nai:"Ішкі [Na⁺]",temp:"Температура",pk:"P(K)",pna:"P(Na)",stim:"Стимул күші",interval:"Алдыңғы ӘП-дан кейінгі аралық",predict:"Болжам",depolarize:"Vm азырақ теріс болады",hyperpolarize:"Vm көбірек теріс болады",noSpike:"ӘП пайда болмайды",run:"Тәжірибені бастау",pause:"Үзіліс",replay:"Қайталау",rest:"Тыныштық",threshold:"Табалдырық",rise:"Деполяризация",fall:"Реполяризация",after:"Іздік гиперполяризация",absolute:"Абсолютті рефрактерлік",relative:"Салыстырмалы рефрактерлік",ready:"Қозғыштық қалпына келді",result:"Нәтиже",correct:"Болжам модельге сәйкес.",retry:"Стимулды табалдырықпен, аралықты рефрактерлікпен салыстырыңыз.",clinical:"Клиникалық байланыс",clinicalText:"Жасушадан тыс K⁺ жоғарылауы калий градиентін азайтып, Vm-ды әдетте деполяризациялайды. Айқын деполяризация Na⁺ арналарының инактивациясын туғызып, қозғыштықты төмендетуі мүмкін.",teacher:"Оқытушы түсіндірмесі",model:"Оқу моделі: Nernst және екі ионды Goldman теңдеулері тікелей есептеледі; ӘП пішіні Hodgkin–Huxley сандық шешімі емес, динамикалық жуықтау.",ek:"E(K)",ena:"E(Na)",vm:"Goldman бойынша Vm",phase:"Фаза"},
 EN:{title:"Virtual electrophysiology laboratory",intro:"Compare equilibrium potentials, make a prediction, and then run an action potential experiment.",part1:"Part 1 — Ion gradients and resting potential",part2:"Part 2 — Action potential",ko:"Outside [K⁺]",ki:"Inside [K⁺]",nao:"Outside [Na⁺]",nai:"Inside [Na⁺]",temp:"Temperature",pk:"P(K)",pna:"P(Na)",stim:"Stimulus strength",interval:"Interval after the previous AP",predict:"Prediction",depolarize:"Vm becomes less negative",hyperpolarize:"Vm becomes more negative",noSpike:"No AP occurs",run:"Run experiment",pause:"Pause",replay:"Replay",rest:"Rest",threshold:"Threshold",rise:"Depolarization",fall:"Repolarization",after:"After-hyperpolarization",absolute:"Absolute refractory",relative:"Relative refractory",ready:"Excitability restored",result:"Result",correct:"The prediction agrees with the model.",retry:"Compare stimulus with threshold and interval with refractoriness.",clinical:"Clinical connection",clinicalText:"Raising extracellular K⁺ reduces the potassium gradient and usually depolarizes Vm. Marked depolarization can inactivate Na⁺ channels and reduce excitability, so depolarization does not always mean greater excitability.",teacher:"Teacher explanation",model:"Teaching model: Nernst and a two-ion Goldman equation are calculated explicitly; the AP waveform is a dynamic approximation, not a numerical Hodgkin–Huxley solution.",ek:"E(K)",ena:"E(Na)",vm:"Goldman Vm",phase:"Phase"},
} as const;

export default function MembraneElectrophysiologyLab({language}:{language:Language}){
 const c=copy[language];
 const[ko,setKo]=useState(4),[ki,setKi]=useState(140),[nao,setNao]=useState(145),[nai,setNai]=useState(12),[temp,setTemp]=useState(37),[pk,setPk]=useState(1),[pna,setPna]=useState(.04),[stim,setStim]=useState(12),[interval,setInterval]=useState(5),[prediction,setPrediction]=useState<Prediction|null>(null),[running,setRunning]=useState(false),[progress,setProgress]=useState(0);
 const values=useMemo(()=>({ek:nernst(ko,ki,temp),ena:nernst(nao,nai,temp),vm:ghk(ko,ki,nao,nai,pk,pna,temp)}),[ko,ki,nao,nai,temp,pk,pna]);
 const refractory=interval<2?"absolute":interval<5?"relative":"ready",effective=stim*(refractory==="absolute"?0:refractory==="relative"?.55:1),spike=effective>=10;
 useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>setProgress(p=>{const n=Math.min(1,p+.018);if(n>=1)setRunning(false);return n}),40);return()=>window.clearInterval(timer)},[running]);
 const waveform=useMemo(()=>Array.from({length:101},(_,i)=>{const x=i/100,y=!spike?values.vm+Math.max(0,effective)*.5*Math.exp(-(((x-.25)/.12)**2)):x<.2?values.vm:x<.34?values.vm+(35-values.vm)*(x-.2)/.14:x<.58?35-(35-values.vm)*(x-.34)/.24:x<.76?values.vm-12*Math.sin((x-.58)/.18*Math.PI):values.vm;return `${20+i*5.5},${125-(y+90)*.82}`}).join(" "),[effective,spike,values.vm]);
 const phase=!running&&progress===0?c.rest:!spike?c.threshold:progress<.34?c.rise:progress<.58?c.fall:progress<.76?c.after:c.rest;
 const actual:Prediction=!spike?"noSpike":values.vm>-65?"depolarize":"hyperpolarize";
 const start=()=>{if(!prediction)return;setProgress(0);setRunning(true)};
 return <section className={styles.lab} data-testid="membrane-electrophysiology-lab" data-run-state={running?"running":progress>=1?"done":"idle"}><header><h1>{c.title}</h1><p>{c.intro}</p></header>
  <section className={styles.panel}><h2>{c.part1}</h2><div className={styles.controls}>{[{label:c.ko,value:ko,set:setKo,min:1,max:20,step:1},{label:c.ki,value:ki,set:setKi,min:80,max:180,step:5},{label:c.nao,value:nao,set:setNao,min:100,max:170,step:5},{label:c.nai,value:nai,set:setNai,min:5,max:30,step:1},{label:c.temp,value:temp,set:setTemp,min:20,max:42,step:1},{label:c.pk,value:pk,set:setPk,min:.1,max:2,step:.1},{label:c.pna,value:pna,set:setPna,min:.01,max:.3,step:.01}].map(control=><label key={control.label}>{control.label}: <b>{control.value.toFixed(control.step<1?2:0)}</b><input type="range" min={control.min} max={control.max} step={control.step} value={control.value} onChange={e=>control.set(+e.target.value)}/></label>)}</div><div className={styles.meters}><span><b>{c.ek}</b>{values.ek.toFixed(1)} mV</span><span><b>{c.ena}</b>{values.ena.toFixed(1)} mV</span><span><b>{c.vm}</b>{values.vm.toFixed(1)} mV</span></div></section>
  <section className={styles.panel}><h2>{c.part2}</h2><div className={styles.experiment}><div><label>{c.stim}: <b>{stim}</b><input type="range" min="0" max="25" value={stim} onChange={e=>setStim(+e.target.value)}/></label><label>{c.interval}: <b>{interval} ms</b><input type="range" min="0" max="12" step=".5" value={interval} onChange={e=>setInterval(+e.target.value)}/></label><p className={styles.refractory}>{c[refractory]}</p><fieldset><legend>{c.predict}</legend>{(["depolarize","hyperpolarize","noSpike"] as Prediction[]).map(p=><button key={p} aria-pressed={prediction===p} onClick={()=>setPrediction(p)}>{c[p]}</button>)}</fieldset><div className={styles.actions}><button disabled={!prediction||running} onClick={start}>{c.run}</button><button disabled={!running} onClick={()=>setRunning(false)}>{c.pause}</button><button disabled={!prediction} onClick={start}>{c.replay}</button></div></div><div className={styles.graph}><svg viewBox="0 0 600 170" role="img" aria-label={`${c.vm}: ${values.vm.toFixed(1)} mV`}><path d="M20 72H570" className={styles.threshold}/><polyline points={waveform}/><line x1={20+progress*550} x2={20+progress*550} y1="10" y2="155" className={styles.cursor}/></svg><p><b>{c.phase}:</b> {phase}</p></div></div>{progress>=1&&prediction&&<div className={prediction===actual?styles.correct:styles.retry}><b>{c.result}:</b> {spike?`${c.rise} → ${c.fall} → ${c.after}`:c.noSpike}. {prediction===actual?c.correct:c.retry}</div>}</section>
  <div className={styles.notes}><section><h2>{c.clinical}</h2><p>{c.clinicalText}</p></section><section><h2>{c.teacher}</h2><p>{c.model}</p></section></div><ExperimentReflection language={language} theoryHref={`/modules/4/theory?lang=${language}`}/>
 </section>
}
