"use client";

import Image from "next/image";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { Language } from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
import styles from "./NerveFiberLab.module.css";

type FiberId = "Aα" | "Aβ" | "Aγ" | "Aδ" | "B" | "C";
type Tab = "lab" | "micro" | "clinical" | "history" | "teacher";
type Prediction = "faster" | "slower" | "same";
type RunState = "idle" | "running" | "paused" | "done";

type Fiber = { velocity: number; diameter: number; myelinated: boolean; color: string; path: string };
type RecordItem = { id: number; fiber: FiberId; conditions: string; prediction: Prediction; velocity: number; time: number };

const fibers: Record<FiberId, Fiber> = {
  "Aα": { velocity: 100, diameter: 16, myelinated: true, color: "#006eb7", path: "M60 280 C170 245 225 210 310 190 C405 165 480 205 575 135 C650 80 735 70 840 55" },
  "Aβ": { velocity: 55, diameter: 9, myelinated: true, color: "#168b72", path: "M60 280 C180 250 245 205 320 188 C430 162 515 125 610 92 C700 62 770 70 840 55" },
  "Aγ": { velocity: 25, diameter: 6, myelinated: true, color: "#6a63b8", path: "M405 180 C500 215 610 250 735 286 C780 298 815 286 850 260" },
  "Aδ": { velocity: 15, diameter: 3, myelinated: true, color: "#d37818", path: "M55 285 C175 245 250 220 330 188 C410 155 505 120 590 82 C670 45 755 60 840 55" },
  B: { velocity: 7, diameter: 2, myelinated: true, color: "#ba4774", path: "M405 180 C480 220 555 245 620 250 C700 258 760 238 850 205" },
  C: { velocity: 1.2, diameter: 1, myelinated: false, color: "#c43d3d", path: "M55 285 C175 258 260 230 335 190 C420 145 505 132 590 105 C680 76 755 82 840 55" },
};

const copy = {
  RU: {
    title:"Интерактивная лаборатория типов нервных волокон", subtitle:"Проследите анатомический маршрут и проверьте, как физические свойства меняют проведение.", tabs:["Лаборатория","Макро / Микро","Клинический режим","История","Преподаватель"], route:"Анатомический маршрут", prediction:"Прогноз", faster:"Быстрее", slower:"Медленнее", same:"Без изменений", experiment:"Эксперимент", result:"Результат", start:"▶ Play", pause:"⏸ Pause", replay:"↻ Replay", compare:"Сравнить волокна", distance:"Расстояние", temperature:"Температура", diameter:"Диаметр", myelin:"Миелинизация", normal:"Норма", partial:"Частичная демиелинизация", severe:"Выраженная демиелинизация", speed:"Расчётная скорость", latency:"Время проведения", choose:"Сначала выберите прогноз.", macro:"Макро", micro:"Микро", microText:"При миелинизации возбуждение перескакивает между узлами Ранвье. Потеря миелина уменьшает эффективность и скорость проведения; в C-волокнах проведение непрерывное.", clinical:"У пациента повреждён миелин периферического нерва. Что произойдёт со скоростью?", correct:"Верно: потеря миелина снижает скорость и может вызвать блок проведения.", retry:"Сравните сопротивление мембраны и утечку тока при демиелинизации.", history:"История экспериментов", empty:"Проведите первый эксперимент — результаты появятся здесь.", teacher:"Пошаговое физиологическое объяснение", explain:"🔊 Озвучить объяснение", voiceOn:"🔊 Голос включён", voiceOff:"🔇 Голос выключен", voice:"Системный голос", auto:"Автоматически", volume:"Громкость", reduced:"Уменьшенное движение", normalMotion:"Обычное движение", conditions:"Условия", function:"Функция", graph:"Скорость и импульс", anatomy:["Рецептор / источник","Периферический нерв","Спинной мозг","Восходящий путь / эффектор","Центральная цель"], functions:{"Aα":"проприоцепция и α-моторная функция","Aβ":"тонкое осязание, давление и вибрация","Aγ":"γ-моторная регуляция мышечного веретена","Aδ":"быстрая боль и холод","B":"преганглионарная вегетативная передача","C":"медленная боль, тепло и постганглионарная симпатическая передача"}, routes:{"Aα":"Мышечное веретено → задний корешок → спинной мозг → α-мотонейрон → мышца","Aβ":"Кожа → задний корешок → задние канатики → ствол → таламус → соматосенсорная кора","Aγ":"Передний рог → периферический нерв → интрафузальные волокна","Aδ":"Кожа → спинномозговой узел → задний рог → перекрёст → восходящий путь → таламус/кора","B":"ЦНС → преганглионарное волокно → вегетативный ганглий","C":"Кожа → задний рог / вегетативный ганглий → орган-мишень"}
  },
  KZ: {
    title:"Жүйке талшықтары түрлерінің интерактивті зертханасы", subtitle:"Анатомиялық жолды бақылап, физикалық қасиеттердің өткізгіштікке әсерін тексеріңіз.", tabs:["Зертхана","Макро / Микро","Клиникалық режим","Тарих","Оқытушы"], route:"Анатомиялық маршрут", prediction:"Болжам", faster:"Жылдамырақ", slower:"Баяуырақ", same:"Өзгеріссіз", experiment:"Эксперимент", result:"Нәтиже", start:"▶ Ойнату", pause:"⏸ Үзіліс", replay:"↻ Қайталау", compare:"Талшықтарды салыстыру", distance:"Қашықтық", temperature:"Температура", diameter:"Диаметр", myelin:"Миелиндену", normal:"Қалыпты", partial:"Жартылай демиелинизация", severe:"Айқын демиелинизация", speed:"Есептік жылдамдық", latency:"Өткізу уақыты", choose:"Алдымен болжамды таңдаңыз.", macro:"Макро", micro:"Микро", microText:"Миелинденген талшықта қозу Ранвье түйіндері арасында секірмелі таралады. Миелиннің жоғалуы өткізуді баяулатады; C талшықтарында өткізу үздіксіз.", clinical:"Науқаста шеткі жүйке миелині зақымдалған. Жылдамдық қалай өзгереді?", correct:"Дұрыс: миелиннің жоғалуы жылдамдықты төмендетіп, өткізу блогын туғызуы мүмкін.", retry:"Демиелинизация кезіндегі мембрана кедергісі мен токтың жоғалуын салыстырыңыз.", history:"Тәжірибелер тарихы", empty:"Алғашқы тәжірибені өткізіңіз — нәтижелер осында көрінеді.", teacher:"Физиологиялық қадамдық түсіндірме", explain:"🔊 Түсіндірмені дыбыстау", voiceOn:"🔊 Дауыс қосулы", voiceOff:"🔇 Дауыс өшірулі", voice:"Жүйелік дауыс", auto:"Автоматты", volume:"Дыбыс деңгейі", reduced:"Қозғалыс азайтылған", normalMotion:"Қалыпты қозғалыс", conditions:"Шарттар", function:"Қызметі", graph:"Жылдамдық және импульс", anatomy:["Рецептор / бастау","Шеткі жүйке","Жұлын","Жоғарылаушы жол / эффектор","Орталық нысана"], functions:{"Aα":"проприоцепция және α-моторлық қызмет","Aβ":"нәзік жанасу, қысым және діріл","Aγ":"бұлшықет ұршығының γ-моторлық реттелуі","Aδ":"жылдам ауырсыну және суық","B":"преганглионарлық вегетативтік өткізу","C":"баяу ауырсыну, жылу және постганглионарлық симпатикалық өткізу"}, routes:{"Aα":"Бұлшықет ұршығы → артқы түбір → жұлын → α-мотонейрон → бұлшықет","Aβ":"Тері → артқы түбір → артқы бағандар → ми бағаны → таламус → соматосенсорлық қыртыс","Aγ":"Алдыңғы мүйіз → шеткі жүйке → интрафузальды талшықтар","Aδ":"Тері → жұлын түйіні → артқы мүйіз → айқасу → жоғарылаушы жол → таламус/қыртыс","B":"ОЖЖ → преганглионарлық талшық → вегетативтік ганглий","C":"Тері → артқы мүйіз / вегетативтік ганглий → нысана-мүше"}
  },
  EN: {
    title:"Interactive laboratory: nerve fiber types", subtitle:"Trace each anatomical route and test how physical properties change conduction.", tabs:["Laboratory","Macro / Micro","Clinical mode","History","Teacher"], route:"Anatomical route", prediction:"Prediction", faster:"Faster", slower:"Slower", same:"No change", experiment:"Experiment", result:"Result", start:"▶ Play", pause:"⏸ Pause", replay:"↻ Replay", compare:"Compare fibers", distance:"Distance", temperature:"Temperature", diameter:"Diameter", myelin:"Myelination", normal:"Normal", partial:"Partial demyelination", severe:"Severe demyelination", speed:"Calculated velocity", latency:"Conduction time", choose:"Choose a prediction first.", macro:"Macro", micro:"Micro", microText:"In myelinated fibers, excitation jumps between nodes of Ranvier. Myelin loss reduces conduction efficiency and speed; C fibers conduct continuously.", clinical:"A patient has peripheral nerve myelin damage. What happens to conduction velocity?", correct:"Correct: myelin loss reduces velocity and may produce conduction block.", retry:"Compare membrane resistance and current leakage during demyelination.", history:"Experiment history", empty:"Run the first experiment and its result will appear here.", teacher:"Step-by-step physiological explanation", explain:"🔊 Narrate explanation", voiceOn:"🔊 Voice on", voiceOff:"🔇 Voice off", voice:"System voice", auto:"Automatic", volume:"Volume", reduced:"Reduced motion", normalMotion:"Normal motion", conditions:"Conditions", function:"Function", graph:"Velocity and impulse", anatomy:["Receptor / source","Peripheral nerve","Spinal cord","Ascending pathway / effector","Central target"], functions:{"Aα":"proprioception and α-motor function","Aβ":"fine touch, pressure, and vibration","Aγ":"γ-motor regulation of muscle spindle","Aδ":"fast pain and cold","B":"preganglionic autonomic transmission","C":"slow pain, warmth, and postganglionic sympathetic transmission"}, routes:{"Aα":"Muscle spindle → dorsal root → spinal cord → α-motoneuron → muscle","Aβ":"Skin → dorsal root → dorsal columns → brainstem → thalamus → somatosensory cortex","Aγ":"Ventral horn → peripheral nerve → intrafusal fibers","Aδ":"Skin → dorsal root ganglion → dorsal horn → decussation → ascending pathway → thalamus/cortex","B":"CNS → preganglionic fiber → autonomic ganglion","C":"Skin → dorsal horn / autonomic ganglion → target organ"}
  }
} as const;

const tabs: Tab[] = ["lab","micro","clinical","history","teacher"];
const ids = Object.keys(fibers) as FiberId[];
const referencePaths = [
  "M 760 470 C 650 430 570 390 505 350 C 455 315 430 350 390 440",
  "M 760 470 C 650 430 560 390 505 350 C 500 260 505 170 500 90",
  "M 505 350 C 580 390 650 430 725 510",
  "M 780 480 C 665 440 570 390 505 350 C 515 265 525 170 505 85",
  "M 505 350 C 580 360 645 400 700 430",
  "M 780 500 C 665 455 570 405 505 355 C 520 270 525 175 505 90",
] as const;
const reactionCopy = {
  RU: ["Проприоцепция: мышца стабилизирует положение руки", "Прикосновение и вибрация распознаются корой", "Мышечное веретено регулирует тонус", "Быстрая боль: защитная реакция отдёргивания", "Вегетативный ганглий меняет работу органа", "Медленная жгучая боль и локальное тепло"],
  KZ: ["Проприоцепция: бұлшықет қол қалпын тұрақтандырады", "Жанасу мен дірілді қыртыс таниды", "Бұлшықет ұршығы тонусты реттейді", "Жылдам ауырсыну: қорғаныштық тартып алу", "Вегетативтік ганглий мүше жұмысын өзгертеді", "Баяу күйдіріп ауырсыну және жергілікті жылу"],
  EN: ["Proprioception: muscle stabilizes the arm", "Touch and vibration reach conscious cortex", "Muscle spindle adjusts muscle tone", "Fast pain triggers protective withdrawal", "Autonomic ganglion changes organ activity", "Slow burning pain and local warmth"],
} as const;
const classificationData: Record<FiberId,{group:string;diameter:string;velocity:string;myelin:"heavy"|"medium"|"light"|"none";conduction:"saltatory"|"continuous"}> = {
  "Aα":{group:"A",diameter:"12–20",velocity:"70–120",myelin:"heavy",conduction:"saltatory"},
  "Aβ":{group:"A",diameter:"6–12",velocity:"35–75",myelin:"heavy",conduction:"saltatory"},
  "Aγ":{group:"A",diameter:"3–8",velocity:"15–35",myelin:"medium",conduction:"saltatory"},
  "Aδ":{group:"A",diameter:"1–5",velocity:"5–30",myelin:"light",conduction:"saltatory"},
  B:{group:"B",diameter:"1–3",velocity:"3–15",myelin:"light",conduction:"saltatory"},
  C:{group:"C",diameter:"0.2–1.5",velocity:"0.5–2",myelin:"none",conduction:"continuous"},
};
const classificationCopy = {
  RU:{part1:"Часть 1 — Классификация нервных волокон",intro:"Сравните типичные свойства периферических волокон. Диапазоны перекрываются и зависят от нерва, температуры и метода измерения.",principle:"Больший диаметр уменьшает внутреннее сопротивление аксона, а миелин обеспечивает скачкообразное проведение между узлами Ранвье. Поэтому толстые, хорошо миелинизированные волокна обычно проводят быстрее.",fast:"Толстые и быстрые",slow:"Тонкие и медленные",part2:"Часть 2 — Виртуальный эксперимент",labels:{fiber:"Тип",group:"Группа",myelin:"Миелинизация",diameter:"Диаметр, мкм",velocity:"Скорость, м/с",function:"Функция",division:"Принадлежность",meaning:"Физиологическое значение",conduction:"Проведение"},myelin:{heavy:"Выраженная",medium:"Умеренная",light:"Тонкая",none:"Нет"},conduction:{saltatory:"Скачкообразное",continuous:"Непрерывное"},profiles:{"Aα":{function:"Проприоцепция; α-моторная иннервация",division:"Сенсорные и моторные",meaning:"Положение тела, сухожильные рефлексы и сокращение экстрафузальных мышц"},"Aβ":{function:"Тонкое осязание, давление, вибрация",division:"Преимущественно сенсорные",meaning:"Быстрое точное распознавание механических стимулов"},"Aγ":{function:"γ-моторная иннервация мышечного веретена",division:"Моторные",meaning:"Настройка чувствительности веретена и поддержание мышечного тонуса"},"Aδ":{function:"Быстрая боль, холод, часть грубого осязания",division:"Сенсорные",meaning:"Ранняя локализованная боль и быстрая защитная реакция"},B:{function:"Преганглионарная вегетативная передача",division:"Вегетативные эфферентные",meaning:"Связь ЦНС с автономными ганглиями"},C:{function:"Медленная боль, тепло, зуд; постганглионарная передача",division:"Сенсорные и вегетативные",meaning:"Поздняя жгучая боль и регуляция органов-мишеней"}}},
  KZ:{part1:"1-бөлім — Жүйке талшықтарының жіктелуі",intro:"Шеткі талшықтардың типтік қасиеттерін салыстырыңыз. Аралықтар қабаттасады және жүйкеге, температураға әрі өлшеу әдісіне тәуелді.",principle:"Үлкен диаметр аксонның ішкі кедергісін азайтады, ал миелин қозудың Ранвье түйіндері арасында секірмелі өтуін қамтамасыз етеді. Сондықтан жуан, жақсы миелинденген талшықтар әдетте жылдамырақ өткізеді.",fast:"Жуан және жылдам",slow:"Жіңішке және баяу",part2:"2-бөлім — Виртуалды тәжірибе",labels:{fiber:"Түрі",group:"Тобы",myelin:"Миелинденуі",diameter:"Диаметрі, мкм",velocity:"Жылдамдығы, м/с",function:"Қызметі",division:"Тиістілігі",meaning:"Физиологиялық маңызы",conduction:"Өткізу түрі"},myelin:{heavy:"Айқын",medium:"Орташа",light:"Жұқа",none:"Жоқ"},conduction:{saltatory:"Секірмелі",continuous:"Үздіксіз"},profiles:{"Aα":{function:"Проприоцепция; α-моторлық иннервация",division:"Сенсорлық және моторлық",meaning:"Дене қалпы, сіңір рефлекстері және экстрафузальды бұлшықет жиырылуы"},"Aβ":{function:"Нәзік жанасу, қысым, діріл",division:"Негізінен сенсорлық",meaning:"Механикалық тітіркендіргіштерді жылдам әрі дәл тану"},"Aγ":{function:"Бұлшықет ұршығының γ-моторлық иннервациясы",division:"Моторлық",meaning:"Ұршық сезімталдығын баптау және бұлшықет тонусын сақтау"},"Aδ":{function:"Жылдам ауырсыну, суық, дөрекі жанасудың бір бөлігі",division:"Сенсорлық",meaning:"Ерте локализацияланған ауырсыну және жылдам қорғаныш жауабы"},B:{function:"Преганглионарлық вегетативтік өткізу",division:"Вегетативтік эфференттік",meaning:"ОЖЖ мен автономды ганглийлер арасындағы байланыс"},C:{function:"Баяу ауырсыну, жылу, қышу; постганглионарлық өткізу",division:"Сенсорлық және вегетативтік",meaning:"Кейінгі күйдіріп ауырсыну және нысана-мүшелерді реттеу"}}},
  EN:{part1:"Part 1 — Classification of nerve fibers",intro:"Compare typical properties of peripheral fibers. Ranges overlap and vary with the nerve, temperature, and measurement method.",principle:"A larger diameter lowers internal axonal resistance, while myelin enables saltatory conduction between nodes of Ranvier. Thick, well-myelinated fibers therefore usually conduct faster.",fast:"Thick and fast",slow:"Thin and slow",part2:"Part 2 — Virtual experiment",labels:{fiber:"Type",group:"Group",myelin:"Myelination",diameter:"Diameter, µm",velocity:"Velocity, m/s",function:"Function",division:"Division",meaning:"Physiological significance",conduction:"Conduction"},myelin:{heavy:"Heavy",medium:"Moderate",light:"Light",none:"None"},conduction:{saltatory:"Saltatory",continuous:"Continuous"},profiles:{"Aα":{function:"Proprioception; α-motor innervation",division:"Sensory and motor",meaning:"Body position, tendon reflexes, and extrafusal muscle contraction"},"Aβ":{function:"Fine touch, pressure, vibration",division:"Predominantly sensory",meaning:"Fast, precise discrimination of mechanical stimuli"},"Aγ":{function:"γ-motor innervation of muscle spindles",division:"Motor",meaning:"Sets spindle sensitivity and supports muscle tone"},"Aδ":{function:"Fast pain, cold, some crude touch",division:"Sensory",meaning:"Early localized pain and a rapid protective response"},B:{function:"Preganglionic autonomic transmission",division:"Autonomic efferent",meaning:"Links the CNS to autonomic ganglia"},C:{function:"Slow pain, warmth, itch; postganglionic transmission",division:"Sensory and autonomic",meaning:"Delayed burning pain and regulation of target organs"}}},
} as const;

export default function NerveFiberLab({ language }: { language: Language }) {
  const t=copy[language];
  const modelNotice={RU:"Модельная скорость и модельное время проведения — результаты упрощённого учебного расчёта, а не физиологические измерения.",EN:"Modelled velocity and modelled conduction time are outputs of a simplified teaching calculation, not physiological measurements.",KZ:"Модельдік жылдамдық пен модельдік өткізу уақыты — физиологиялық өлшем емес, оңайлатылған оқу есебінің нәтижелері."}[language];
  const [tab,setTab]=useState<Tab>("lab"),[fiber,setFiber]=useState<FiberId>("Aδ"),[overviewFiber,setOverviewFiber]=useState<FiberId>("Aα"),[distance,setDistance]=useState(1),[temperature,setTemperature]=useState(37),[diameter,setDiameter]=useState(100),[myelin,setMyelin]=useState(1),[prediction,setPrediction]=useState<Prediction|"">(""),[runState,setRunState]=useState<RunState>("idle"),[progress,setProgress]=useState(0),[history,setHistory]=useState<RecordItem[]>([]),[compare,setCompare]=useState(false),[clinical,setClinical]=useState<"correct"|"retry"|"">(""),[micro,setMicro]=useState(false),[voiceOn,setVoiceOn]=useState(true),[volume,setVolume]=useState(1),[voices,setVoices]=useState<SpeechSynthesisVoice[]>([]),[voiceName,setVoiceName]=useState(""),[reduced,setReduced]=useState(false);
  const frame=useRef<number|null>(null),last=useRef(0);
  const current=fibers[fiber];
  const classification=classificationCopy[language];
  const fiberIndex=ids.indexOf(fiber),referencePath=referencePaths[fiberIndex],reaction=reactionCopy[language][fiberIndex];
  const calc=useCallback((id=fiber)=>{const f=fibers[id],tempFactor=Math.max(.45,1-(37-temperature)*.025),diameterFactor=Math.sqrt(diameter/100),myelinFactor=f.myelinated?myelin:1;const velocity=f.velocity*tempFactor*diameterFactor*myelinFactor;return {velocity,time:distance/velocity*1000};},[fiber,distance,temperature,diameter,myelin]);
  const result=calc();
  const speak=useCallback((text:string)=>{if(!voiceOn||typeof window==="undefined"||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=language==="RU"?"ru-RU":language==="KZ"?"kk-KZ":"en-US";utterance.volume=volume;const selected=voices.find(v=>v.name===voiceName);if(selected)utterance.voice=selected;window.speechSynthesis.speak(utterance);},[language,voiceName,voiceOn,voices,volume]);
  useEffect(()=>{if(typeof window==="undefined"||!("speechSynthesis" in window))return;const load=()=>setVoices(window.speechSynthesis.getVoices());load();window.speechSynthesis.addEventListener("voiceschanged",load);return()=>window.speechSynthesis.removeEventListener("voiceschanged",load);},[]);
  useEffect(()=>{if(typeof window==="undefined")return;const media=window.matchMedia("(prefers-reduced-motion: reduce)");setReduced(media.matches);},[]);
  useEffect(()=>{if(runState!=="running")return;const step=(now:number)=>{if(!last.current)last.current=now;const increment=reduced?1:(now-last.current)/2400;last.current=now;setProgress(value=>{const next=Math.min(1,value+increment);if(next>=1)setRunState("done");return next;});if(runState==="running")frame.current=requestAnimationFrame(step)};frame.current=requestAnimationFrame(step);return()=>{if(frame.current)cancelAnimationFrame(frame.current);last.current=0;};},[runState,reduced]);
  useEffect(()=>{if(runState!=="done")return;recordOutcome(3,"interactive",1,1);recordOutcome(3,"criterion:mechanism:nerve-conduction-prediction",1,1);const item:RecordItem={id:Date.now(),fiber,conditions:`${distance.toFixed(1)} m · ${temperature} °C · ${diameter}% · ${Math.round(myelin*100)}%`,prediction:prediction||"same",velocity:result.velocity,time:result.time};setHistory(items=>items.some(x=>x.id===item.id)?items:[item,...items].slice(0,12));speak(`${fiber}. ${t.speed}: ${result.velocity.toFixed(1)}. ${t.latency}: ${result.time.toFixed(0)}.`);},[runState]); // eslint-disable-line react-hooks/exhaustive-deps
  function play(){if(!prediction){speak(t.choose);return}if(runState==="done"){setProgress(0)}setRunState("running")}
  function replay(){setProgress(0);setRunState("running")}
  const teacherText=`${fiber}: ${t.functions[fiber]}. ${t.routes[fiber]}. ${current.myelinated?t.microText:"C: "+t.microText} ${t.speed}: ${result.velocity.toFixed(1)} m/s.`;
  const graphPoints=useMemo(()=>ids.map((id,index)=>{const value=calc(id).velocity;return {id,value,x:25+index*55,y:112-Math.min(100,value)};}),[calc]);

  return <section className={styles.lab} data-testid="nerve-fiber-lab" data-language={language} data-run-state={runState}>
    <p>{modelNotice}</p>
    <header className={styles.header}><div><span className={styles.eyebrow}>Module 3 · Lab</span><h2>{t.title}</h2><p>{t.subtitle}</p></div><div className={styles.audio}><button type="button" onClick={()=>{setVoiceOn(v=>!v);window.speechSynthesis?.cancel()}}>{voiceOn?t.voiceOn:t.voiceOff}</button><label>{t.volume}<input aria-label={t.volume} type="range" min="0" max="1" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/><b>{Math.round(volume*100)}%</b></label><label>{t.voice}<select value={voiceName} onChange={e=>setVoiceName(e.target.value)}><option value="">{t.auto}</option>{voices.filter(v=>v.lang.toLowerCase().startsWith(language==="RU"?"ru":language==="KZ"?"kk":"en")).map(v=><option key={`${v.name}-${v.lang}`} value={v.name}>{v.name} ({v.lang})</option>)}</select></label></div></header>
    <nav className={styles.tabs} aria-label={t.title}>{tabs.map((id,i)=><button type="button" key={id} aria-selected={tab===id} onClick={()=>setTab(id)}>{t.tabs[i]}</button>)}</nav>
    {tab==="lab"&&<>
    <section className={styles.classification} aria-labelledby="fiber-classification-title">
      <div className={styles.classificationIntro}><div><span className={styles.partLabel}>01</span><h3 id="fiber-classification-title">{classification.part1}</h3><p>{classification.intro}</p></div><p className={styles.principle}><strong>{classification.labels.diameter} + {classification.labels.myelin} → {classification.labels.velocity}</strong><span>{classification.principle}</span></p></div>
      <div className={styles.fiberScale} aria-label={`${classification.fast} — ${classification.slow}`}><strong>{classification.fast}</strong><div className={styles.scaleTrack}>{ids.map((id,index)=><button type="button" key={id} aria-pressed={overviewFiber===id} onClick={()=>setOverviewFiber(id)} style={{"--fiber":fibers[id].color,"--scale":1-index*.11} as React.CSSProperties}><i/><span>{id}</span></button>)}</div><strong>{classification.slow}</strong></div>
      <div className={styles.classificationTable} role="table" aria-label={classification.part1}>
        <div className={styles.classificationHead} role="row"><span>{classification.labels.fiber}</span><span>{classification.labels.group}</span><span>{classification.labels.myelin}</span><span>{classification.labels.diameter}</span><span>{classification.labels.velocity}</span><span>{classification.labels.function}</span><span>{classification.labels.division}</span><span>{classification.labels.meaning}</span><span>{classification.labels.conduction}</span></div>
        {ids.map(id=>{const data=classificationData[id],profile=classification.profiles[id],selected=overviewFiber===id;return <button type="button" role="row" key={id} className={styles.classificationRow} aria-pressed={selected} onClick={()=>setOverviewFiber(id)} style={{"--fiber":fibers[id].color} as React.CSSProperties}>
          <span role="cell" data-label={classification.labels.fiber}><b>{id}</b></span><span role="cell" data-label={classification.labels.group}>{data.group}</span><span role="cell" data-label={classification.labels.myelin}>{classification.myelin[data.myelin]}</span><span role="cell" data-label={classification.labels.diameter}>{data.diameter} µm</span><span role="cell" data-label={classification.labels.velocity}>{data.velocity} m/s</span><span role="cell" data-label={classification.labels.function}>{profile.function}</span><span role="cell" data-label={classification.labels.division}>{profile.division}</span><span role="cell" data-label={classification.labels.meaning}>{profile.meaning}</span><span role="cell" data-label={classification.labels.conduction}>{classification.conduction[data.conduction]}</span>
        </button>})}
      </div>
    </section>
    <div className={styles.partDivider}><span className={styles.partLabel}>02</span><h3>{classification.part2}</h3></div>
    <div className={styles.workspace}>
      <main className={styles.stage}>
        <div className={styles.fibers} role="group" aria-label="Fiber type">{ids.map(id=><button type="button" key={id} data-fiber={id} aria-pressed={fiber===id} style={{"--fiber":fibers[id].color} as React.CSSProperties} onClick={()=>{setFiber(id);setProgress(0);setRunState("idle")}}>{id}<small>{fibers[id].velocity} m/s</small></button>)}</div>
        <div className={styles.anatomy} data-scene-fiber={fiber} data-reaction={reaction} style={{"--fiber":current.color,"--progress":progress} as React.CSSProperties}>
          <div className={styles.patientScene}>
            <Image className={styles.patientImage} src="/images/module3/nerve-fiber-woman-reference.png" alt="" fill priority sizes="(max-width: 760px) 760px, (max-width: 1100px) 65vw, 900px"/>
            <svg viewBox="0 0 1000 667" role="img" aria-label={`${fiber}: ${t.routes[fiber]}`}>
              <path d={referencePath} className={styles.routeShadow}/><path d={referencePath} className={styles.route} style={{stroke:current.color}}/>
              <circle r="11" fill={current.color} className={reduced?styles.pulseStill:styles.pulse} style={{offsetPath:`path('${referencePath}')`,offsetDistance:`${progress*100}%`}}/>
            </svg>
            <div className={`${styles.reaction} ${styles[`reaction${fiberIndex}`]}`} aria-live="polite"><i/><span>{reaction}</span></div>
            <div className={styles.sceneStatus}><b>{fiber}</b><span>{runState==="running"?`${Math.round(progress*100)}%`:runState==="done"?"✓":"●"}</span></div>
          </div>
          <div className={styles.routeText}><strong>{t.route}: {fiber}</strong><span>{t.routes[fiber]}</span></div>
        </div>
        <div className={styles.chart} aria-label={t.graph}><svg viewBox="0 0 360 135"><path d="M20 115H345M20 15V115"/><polyline points={graphPoints.map(p=>`${p.x},${p.y}`).join(" ")} /><path d={`M20,112 C80,${105-progress*65} 130,${110-progress*92} 185,${108-progress*20} S280,${110-progress*84} 345,${110-progress*30}`} className={styles.trace}/>{graphPoints.map(p=><g key={p.id}><circle cx={p.x} cy={p.y} r={fiber===p.id?6:4}/><text x={p.x} y="130" textAnchor="middle">{p.id}</text></g>)}</svg><div><b>{t.speed}: {result.velocity.toFixed(1)} m/s</b><span>{t.latency}: {result.time.toFixed(0)} ms</span></div></div>
      </main>
      <aside className={styles.controls}><div><h3>{fiber}</h3><span className={styles.badge}>{t.functions[fiber]}</span><p>{t.routes[fiber]}</p></div><label>{t.distance}: <b>{distance.toFixed(1)} m</b><input type="range" min=".2" max="2" step=".1" value={distance} onChange={e=>setDistance(Number(e.target.value))}/></label><label>{t.temperature}: <b>{temperature} °C</b><input type="range" min="20" max="42" value={temperature} onChange={e=>setTemperature(Number(e.target.value))}/></label><label>{t.diameter}: <b>{diameter}%</b><input type="range" min="30" max="170" value={diameter} onChange={e=>setDiameter(Number(e.target.value))}/></label><label>{t.myelin}<select disabled={!current.myelinated} value={myelin} onChange={e=>setMyelin(Number(e.target.value))}><option value="1">{t.normal}</option><option value=".6">{t.partial}</option><option value=".3">{t.severe}</option></select></label><fieldset><legend>{t.prediction}</legend><div className={styles.predictions}>{(["faster","slower","same"] as Prediction[]).map((p,i)=><button type="button" key={p} aria-pressed={prediction===p} onClick={()=>setPrediction(p)}>{[t.faster,t.slower,t.same][i]}</button>)}</div></fieldset><div className={styles.transport}><button type="button" onClick={play}>{t.start}</button><button type="button" disabled={runState!=="running"} onClick={()=>setRunState("paused")}>{t.pause}</button><button type="button" onClick={replay}>{t.replay}</button></div>{!prediction&&<p className={styles.hint}>{t.choose}</p>}<div className={styles.result}><b>{t.result}</b><span>{runState==="done"?`${result.velocity.toFixed(1)} m/s · ${result.time.toFixed(0)} ms`:runState==="running"?`${Math.round(progress*100)}%`:"—"}</span></div><button type="button" className={styles.compare} aria-pressed={compare} onClick={()=>setCompare(v=>!v)}>{t.compare}</button>{compare&&<div className={styles.comparison}>{ids.map(id=><div key={id}><b>{id}</b><span style={{width:`${Math.max(4,calc(id).velocity)}%`,background:fibers[id].color}}/><em>{calc(id).velocity.toFixed(1)}</em></div>)}</div>}</aside>
    </div></>}
    {tab==="micro"&&<div className={styles.modePanel}><div className={styles.modeToggle}><button aria-pressed={!micro} onClick={()=>setMicro(false)}>{t.macro}</button><button aria-pressed={micro} onClick={()=>setMicro(true)}>{t.micro}</button></div><div className={`${styles.axon} ${micro?styles.zoomed:""}`}><div className={styles.axonCore}/>{current.myelinated&&[8,26,44,62,80].map(x=><i key={x} style={{left:`${x}%`,opacity:myelin}}/>)}<span className={styles.microPulse} style={{left:`${5+progress*88}%`,background:current.color}}/></div><p>{t.microText}</p><div className={styles.transport}><button onClick={play}>{t.start}</button><button onClick={()=>setRunState("paused")}>{t.pause}</button><button onClick={replay}>{t.replay}</button></div></div>}
    {tab==="clinical"&&<div className={styles.modePanel}><h3>{t.tabs[2]}</h3><p>{t.clinical}</p><div className={styles.clinicalButtons}><button onClick={()=>{setClinical("correct");recordOutcome(3,"criterion:clinical:demyelination",1,1);recordOutcome(3,"criterion:application:nerve-fiber",1,1);speak(t.correct)}}>{t.slower}</button><button onClick={()=>{setClinical("retry");recordOutcome(3,"criterion:clinical:demyelination",0,1);recordOutcome(3,"criterion:application:nerve-fiber",0,1);speak(t.retry)}}>{t.same}</button></div>{clinical&&<div role="status" className={clinical==="correct"?styles.correct:styles.retry}>{clinical==="correct"?t.correct:t.retry}</div>}</div>}
    {tab==="history"&&<div className={styles.modePanel}><h3>{t.history}</h3>{history.length===0?<p>{t.empty}</p>:<div className={styles.tableWrap}><table><thead><tr><th>№</th><th>{t.function}</th><th>{t.conditions}</th><th>{t.prediction}</th><th>{t.speed}</th><th>{t.latency}</th></tr></thead><tbody>{history.map((row,i)=><tr key={row.id}><td>{history.length-i}</td><td>{row.fiber}</td><td>{row.conditions}</td><td>{row.prediction}</td><td>{row.velocity.toFixed(1)} m/s</td><td>{row.time.toFixed(0)} ms</td></tr>)}</tbody></table></div>}</div>}
    {tab==="teacher"&&<div className={styles.modePanel}><h3>{t.teacher}</h3><div className={styles.teacherGrid}>{ids.map(id=><button key={id} aria-pressed={fiber===id} onClick={()=>setFiber(id)}>{id}<small>{t.functions[id]}</small></button>)}</div><p className={styles.teacherText}>{teacherText}</p><button onClick={()=>speak(teacherText)}>{t.explain}</button></div>}
    <ExperimentReflection language={language} theoryHref={`/modules/3/theory?lang=${language}`} moduleId={3}/>
    <footer className={styles.footer}><button type="button" aria-pressed={reduced} onClick={()=>setReduced(v=>!v)}>{reduced?t.reduced:t.normalMotion}</button><span>Aα · Aβ · Aγ · Aδ · B · C</span></footer>
  </section>;
}
