"use client";
import {useState} from "react";
import type {Language} from "../content/course";
import styles from "./NeuroPracticalStation.module.css";
import ExperimentReflection from "./ExperimentReflection";

type Station={title:Record<Language,string>;goal:Record<Language,string>;steps:Record<Language,string[]>;observe:Record<Language,string[]>;interpret:Record<Language,string[]>};
const S:Record<number,Station>={
3:{title:{RU:"Практическая станция: проведение по нерву",KZ:"Практикалық станция: жүйке бойымен өткізу",EN:"Practical station: nerve conduction"},goal:{RU:"Сопоставьте стимуляцию, регистрацию и параметры ответа.",KZ:"Стимуляцияны, тіркеуді және жауап параметрлерін салыстырыңыз.",EN:"Link stimulation, recording, and response parameters."},steps:{RU:["Разместить стимулирующие и регистрирующие электроды","Выбрать интенсивность стимула выше пороговой","Записать латентность и амплитуду ответа","Изменить расстояние или состояние миелина","Сравнить скорость и форму ответа"],KZ:["Стимулдаушы және тіркеуші электродтарды орналастыру","Табалдырықтан жоғары стимул таңдау","Латенттілік пен амплитуданы жазу","Қашықтықты немесе миелин күйін өзгерту","Жылдамдық пен жауап пішінін салыстыру"],EN:["Place stimulating and recording electrodes","Choose a suprathreshold stimulus","Record response latency and amplitude","Change distance or myelin state","Compare conduction speed and waveform"]},observe:{RU:["Латентность","Амплитуда","Скорость проведения"],KZ:["Латенттілік","Амплитуда","Өткізу жылдамдығы"],EN:["Latency","Amplitude","Conduction velocity"]},interpret:{RU:["Увеличение латентности указывает на замедление проведения.","Снижение амплитуды отражает потерю или недостаточную активацию проводящих волокон."],KZ:["Латенттіліктің артуы өткізудің баяулағанын көрсетеді.","Амплитуданың төмендеуі өткізгіш талшықтардың азаюын немесе жеткіліксіз белсенуін көрсетеді."],EN:["Longer latency indicates slower conduction.","Lower amplitude reflects fewer or insufficiently activated conducting fibers."]}},
11:{title:{RU:"Практическая станция: ЭМГ",KZ:"Практикалық станция: ЭМГ",EN:"Practical station: EMG"},goal:{RU:"Свяжите уровень мышечной активации с электрической активностью.",KZ:"Бұлшықет белсену деңгейін электрлік белсенділікпен байланыстырыңыз.",EN:"Relate muscle activation level to electrical activity."},steps:{RU:["Выбрать мышцу и положение конечности","Записать фон при расслаблении","Выполнить слабое произвольное сокращение","Увеличить силу сокращения","Сравнить рекрутирование"],KZ:["Бұлшықет пен аяқ-қол қалпын таңдау","Босаңсу кезіндегі фонды жазу","Әлсіз ерікті жиырылу жасау","Жиырылу күшін арттыру","Рекруттеуді салыстыру"],EN:["Choose a muscle and limb position","Record resting baseline","Perform a weak voluntary contraction","Increase contraction force","Compare recruitment"]},observe:{RU:["Фоновая активность","Число моторных единиц","Плотность интерференционного паттерна"],KZ:["Фондық белсенділік","Моторлық бірліктер саны","Интерференциялық паттерн тығыздығы"],EN:["Resting activity","Motor-unit recruitment","Interference-pattern density"]},interpret:{RU:["При усилении произвольного сокращения рекрутируется больше моторных единиц.","Характер ЭМГ интерпретируют вместе с клиническим контекстом, а не по одному признаку."],KZ:["Ерікті жиырылу күшейгенде көбірек моторлық бірлік рекруттеледі.","ЭМГ сипаты бір белгімен емес, клиникалық контекспен бірге түсіндіріледі."],EN:["Stronger voluntary contraction recruits more motor units.","EMG features should be interpreted with clinical context, not from one sign alone."]}},
19:{title:{RU:"Практическая станция: сенсорное обследование",KZ:"Практикалық станция: сезімталдықты тексеру",EN:"Practical station: sensory examination"},goal:{RU:"Сравните разные виды чувствительности и локализуйте возможный уровень нарушения.",KZ:"Сезімталдық түрлерін салыстырып, ықтимал зақым деңгейін анықтаңыз.",EN:"Compare sensory modalities and localize a possible lesion level."},steps:{RU:["Объяснить процедуру и закрыть пациенту глаза","Сравнить симметричные участки","Проверить лёгкое прикосновение","Проверить боль/температуру или вибрацию","Сопоставить рисунок нарушения с проводящим путём"],KZ:["Процедураны түсіндіріп, науқастың көзін жабу","Симметриялы аймақтарды салыстыру","Жеңіл жанасуды тексеру","Ауырсыну/температураны немесе вибрацияны тексеру","Бұзылыс үлгісін өткізгіш жолмен салыстыру"],EN:["Explain the procedure and ask the patient to close the eyes","Compare symmetric areas","Test light touch","Test pain/temperature or vibration","Match the deficit pattern to a pathway"]},observe:{RU:["Модальность","Сторона","Граница нарушения"],KZ:["Модальдық","Жақ","Бұзылыс шекарасы"],EN:["Modality","Side","Deficit boundary"]},interpret:{RU:["Разные модальности могут расходиться при поражении разных проводящих систем.","Точная локализация требует сопоставления нескольких находок."],KZ:["Әртүрлі өткізгіш жүйелер зақымданғанда сезімталдық модальдықтары әртүрлі бұзылуы мүмкін.","Нақты локализация бірнеше табылымды салыстыруды талап етеді."],EN:["Different sensory modalities can dissociate when different pathways are affected.","Accurate localization requires combining multiple findings."]}},
20:{title:{RU:"Практическая станция: зрительная функция",KZ:"Практикалық станция: көру қызметі",EN:"Practical station: visual function"},goal:{RU:"Разделите остроту зрения, поля зрения и цветоощущение как разные функции.",KZ:"Көру өткірлігін, көру өрісін және түсті ажыратуды бөлек функциялар ретінде қарастырыңыз.",EN:"Separate visual acuity, visual fields, and color vision as distinct functions."},steps:{RU:["Проверить каждый глаз отдельно","Оценить остроту зрения","Сравнить поля зрения","Проверить цветоощущение","Связать тип дефекта с уровнем зрительного пути"],KZ:["Әр көзді бөлек тексеру","Көру өткірлігін бағалау","Көру өрістерін салыстыру","Түсті ажыратуды тексеру","Ақау түрін көру жолының деңгейімен байланыстыру"],EN:["Test each eye separately","Assess visual acuity","Compare visual fields","Test color vision","Relate the defect type to the visual pathway level"]},observe:{RU:["Острота","Поле зрения","Цветоощущение"],KZ:["Өткірлік","Көру өрісі","Түсті ажырату"],EN:["Acuity","Visual field","Color vision"]},interpret:{RU:["Острота зрения и поле зрения отражают разные аспекты функции зрительной системы.","Характер выпадения поля помогает локализовать поражение по ходу зрительного пути."],KZ:["Көру өткірлігі мен көру өрісі көру жүйесінің әртүрлі қызметтерін көрсетеді.","Көру өрісінің ақау үлгісі зақымды көру жолы бойымен локализациялауға көмектеседі."],EN:["Visual acuity and visual fields reflect different aspects of visual function.","The field-defect pattern helps localize lesions along the visual pathway."]}},
21:{title:{RU:"Практическая станция: слух и специальные чувства",KZ:"Практикалық станция: есту және арнайы сезімдер",EN:"Practical station: hearing and special senses"},goal:{RU:"Сравните периферический стимул, рецептор и центральный путь.",KZ:"Перифериялық стимулды, рецепторды және орталық жолды салыстырыңыз.",EN:"Compare peripheral stimulus, receptor, and central pathway."},steps:{RU:["Выбрать модальность","Проверить функцию одного органа отдельно","Сравнить правую и левую стороны","Проследить путь до центрального представительства","Объяснить возможный уровень нарушения"],KZ:["Модальдықты таңдау","Бір мүшенің қызметін жеке тексеру","Оң және сол жақты салыстыру","Орталық өкілдікке дейінгі жолды қадағалау","Ықтимал зақым деңгейін түсіндіру"],EN:["Choose the modality","Test one organ separately","Compare right and left sides","Trace the pathway to central representation","Explain a possible lesion level"]},observe:{RU:["Симметрия","Порог восприятия","Качество восприятия"],KZ:["Симметрия","Қабылдау табалдырығы","Қабылдау сапасы"],EN:["Symmetry","Perceptual threshold","Quality of perception"]},interpret:{RU:["Нарушение может возникать на уровне рецептора, нерва, стволовых/таламических структур или коры.","Одинаковая жалоба может иметь разную локализацию, поэтому сравнивают несколько признаков."],KZ:["Бұзылыс рецептор, жүйке, ми бағаны/таламус немесе қыртыс деңгейінде пайда болуы мүмкін.","Бірдей шағым әртүрлі локализацияға байланысты болуы мүмкін, сондықтан бірнеше белгіні салыстырады."],EN:["Dysfunction may arise at receptor, nerve, brainstem/thalamic, or cortical levels.","The same complaint can have different localizations, so multiple findings are compared."]}},
22:{title:{RU:"Практическая станция: автономная регуляция",KZ:"Практикалық станция: автономдық реттелу",EN:"Practical station: autonomic regulation"},goal:{RU:"Оцените автономный ответ как изменение регулируемой функции во времени.",KZ:"Автономдық жауапты реттелетін функцияның уақыт бойынша өзгеруі ретінде бағалаңыз.",EN:"Assess an autonomic response as a time-dependent change in a regulated function."},steps:{RU:["Записать исходное состояние","Выбрать стандартный функциональный стимул","Наблюдать изменение показателя","Оценить восстановление","Сопоставить результат с механизмом обратной связи"],KZ:["Бастапқы күйді жазу","Стандартты функционалдық стимул таңдау","Көрсеткіш өзгерісін бақылау","Қалпына келуді бағалау","Нәтижені кері байланыс механизмімен салыстыру"],EN:["Record baseline","Choose a standard functional stimulus","Observe the response","Assess recovery","Relate the result to feedback control"]},observe:{RU:["Исходное значение","Величина ответа","Время восстановления"],KZ:["Бастапқы мән","Жауап шамасы","Қалпына келу уақыты"],EN:["Baseline","Response magnitude","Recovery time"]},interpret:{RU:["Автономный тест оценивают по динамике, а не по одной точке.","Результат зависит от состояния нескольких звеньев регуляции."],KZ:["Автономдық тест бір нүктемен емес, динамикамен бағаланады.","Нәтиже реттелудің бірнеше буынына тәуелді."],EN:["Autonomic tests are interpreted from dynamics, not a single value.","The result depends on several levels of regulation."]}}
};

export default function NeuroPracticalStation({moduleId,language}:{moduleId:number;language:Language}){
 const s=S[moduleId]; const[step,setStep]=useState(0); const[done,setDone]=useState<boolean[]>([false,false,false,false,false]);
 if(!s)return null;
 const complete=done.filter(Boolean).length;
 return <section className={styles.station}>
  <header><div><span className={styles.badge}>Practical</span><h2>{s.title[language]}</h2><p>{s.goal[language]}</p></div><div className={styles.score}>{complete}/5</div></header>
  <progress value={complete} max={5} aria-label="progress"/>
  <div className={styles.steps}>{s.steps[language].map((x,i)=><button type="button" key={x} data-active={i===step} data-done={done[i]} onClick={()=>setStep(i)}><b>{i+1}</b><span>{x}</span></button>)}</div>
  <div className={styles.work}>
   <article><h3>{language==="RU"?"Текущий шаг":language==="KZ"?"Ағымдағы қадам":"Current step"}</h3><p>{s.steps[language][step]}</p><button type="button" onClick={()=>setDone(v=>v.map((x,i)=>i===step?true:x))}>{language==="RU"?"Отметить выполненным":language==="KZ"?"Орындалды деп белгілеу":"Mark complete"}</button></article>
   <article><h3>{language==="RU"?"Что наблюдаем":language==="KZ"?"Нені бақылаймыз":"What to observe"}</h3><ul>{s.observe[language].map(x=><li key={x}>{x}</li>)}</ul></article>
   <article><h3>{language==="RU"?"Физиологическая интерпретация":language==="KZ"?"Физиологиялық түсіндіру":"Physiological interpretation"}</h3><ul>{s.interpret[language].map(x=><li key={x}>{x}</li>)}</ul></article>
  </div>
  {complete===5&&<ExperimentReflection language={language} theoryHref={`/modules/${moduleId}/theory?lang=${language}`} moduleId={moduleId}/>} 
 </section>
}