"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
import {isMeaningfulResponse} from "../lib/meaningfulResponse";
import AdvancedAnatomyReference from "./AdvancedAnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Лаборатория нейропластичности",a:"Синхронность пре- и постсинаптической активности",b:"Временное рассогласование активности",out:"Условное изменение эффективности синапса",predict:"Прогноз",task:"Сначала сформулируйте прогноз. Затем изменяйте только один параметр за опыт, запишите результат и объясните механизм.",save:"Записать опыт",explain:"Объяснение",limit:"Синаптическая пластичность не сводится к правилу «больше повторений — сильнее синапс». Направление изменения зависит от относительного времени пре- и постсинаптической активности, паттерна стимуляции, рецепторов и состояния сети; возможны как потенциация, так и депрессия. Эта модель показывает принцип зависимости от совпадения во времени, а не количественную STDP-кривую; проценты условны."},EN:{title:"Neuroplasticity laboratory",a:"Pre/post activity coincidence",b:"Activity timing mismatch",out:"Modeled change in synaptic efficacy",predict:"Prediction",task:"Make a prediction first. Then change only one parameter per trial, record the result, and explain the mechanism.",save:"Record trial",explain:"Explanation",limit:"Synaptic plasticity is not simply “more repetition means a stronger synapse.” Its direction depends on relative pre/post timing, stimulation pattern, receptors, and network state; both potentiation and depression can occur. This model illustrates timing dependence rather than a quantitative STDP curve; percentages are modeled."},KZ:{title:"Нейропластикалылық зертханасы",a:"Пре- және постсинапстық белсенділіктің сәйкестігі",b:"Белсенділіктің уақыттық сәйкессіздігі",out:"Синапс тиімділігінің шартты өзгерісі",predict:"Болжам",task:"Алдымен болжам жасаңыз. Әр тәжірибеде тек бір параметрді өзгертіп, нәтижені жазып, механизмді түсіндіріңіз.",save:"Тәжірибені жазу",explain:"Түсіндірме",limit:"Синапстық пластикалылық «қайталау көп болса, синапс күшейеді» деген қарапайым ережеге келмейді. Өзгеріс бағыты пре- және постсинапстық белсенділіктің салыстырмалы уақытына, стимуляция үлгісіне, рецепторларға және желі күйіне тәуелді; потенциация да, депрессия да болуы мүмкін. Бұл модель сандық STDP қисығын емес, уақыттық сәйкестік қағидасын көрсетеді; пайыздар шартты."}} as const;
function calc(a:number,b:number){return Math.max(-40,Math.min(100,Math.round((a-b)*.85)));}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(60),[b,setB]=useState(40),[prediction,setPrediction]=useState(""),[revealed,setRevealed]=useState(false),[rows,setRows]=useState<Row[]>([]);const value=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AdvancedAnatomyReference moduleId={25} language={language}/><p><strong>{t.task}</strong></p><label>{t.predict}<textarea value={prediction} onChange={e=>{setPrediction(e.target.value);setRevealed(false)}} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a}%<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b}%<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 180" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><path d="M60 90 H250" stroke="currentColor" strokeWidth={2+a/25}/><circle cx="310" cy="90" r="42" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M352 90 H555" stroke="currentColor" strokeWidth={Math.max(1,2+value/25)}/><circle cx="600" cy="90" r={12+value/9} fill="none" stroke="currentColor" strokeWidth="3"/>{revealed&&<text x="255" y="155">{t.out}: {value}%</text>}</svg><button disabled={!isMeaningfulResponse(prediction,20,3)} onClick={()=>{setRevealed(true);recordOutcome(25,"interactive",1,1);recordOutcome(25,"criterion:application:lab",1,1);setRows(r=>[...r,{id:Date.now(),a,b,out:value,note:""}])}}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.out}</th><th>{t.explain}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}</td><td>{r.b}</td><td>{r.out}%</td><td><input value={r.note} onChange={e=>{const note=e.target.value;setRows(xs=>xs.map(q=>q.id===r.id?{...q,note}:q));if(isMeaningfulResponse(note,30,4))recordOutcome(25,"criterion:justification:lab",1,1)}}/></td></tr>)}</tbody></table></div><ExperimentReflection language={language} theoryHref={`/modules/25/theory?lang=${language}`}/><p><small>{t.limit}</small></p></section>}
