"use client";
import {useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import styles from "./SensorySystemsLab.module.css";

type Analyzer={id:string;icon:string;ru:string;en:string;kz:string;receptor:string;stimulus:string;path:string;center:string;cortex:string;clinic:string};
const A:Analyzer[]=[
{id:"visual",icon:"👁️",ru:"Зрительный",en:"Visual",kz:"Көру",receptor:"Палочки и колбочки сетчатки",stimulus:"Свет, цвет, интенсивность",path:"Сетчатка → зрительный нерв II → хиазма → тракт → ЛКТ → зрительная лучистость",center:"Латеральное коленчатое тело, верхние холмики",cortex:"Поле 17, затылочная кора",clinic:"Миопия, гиперметропия, астигматизм, катаракта, глаукома, отслойка сетчатки, неврит зрительного нерва, дальтонизм"},
{id:"auditory",icon:"👂",ru:"Слуховой",en:"Auditory",kz:"Есту",receptor:"Волосковые клетки органа Корти",stimulus:"Звук и вибрация",path:"Улитковый нерв → улитковые ядра → верхняя олива → латеральная петля → нижний холмик → МКТ",center:"Медиальное коленчатое тело, нижний холмик",cortex:"Поля 41–42, верхняя височная извилина",clinic:"Кондуктивная/нейросенсорная тугоухость, тиннитус, болезнь Меньера"},
{id:"vestibular",icon:"🧭",ru:"Вестибулярный",en:"Vestibular",kz:"Вестибулярлық",receptor:"Волосковые клетки полукружных каналов, маточки и мешочка",stimulus:"Угловое/линейное ускорение, положение головы",path:"Вестибулярный нерв → вестибулярные ядра → МПП, вестибулоспинальные пути → таламус/кора; связи с мозжечком",center:"Вестибулярные ядра, мозжечок, таламус",cortex:"Теменно-островковая вестибулярная кора",clinic:"Головокружение, ДППГ, болезнь Меньера, вестибулярный неврит, укачивание"},
{id:"olfactory",icon:"👃",ru:"Обонятельный",en:"Olfactory",kz:"Иіс сезу",receptor:"Обонятельные рецепторные нейроны эпителия",stimulus:"Пахучие химические вещества",path:"I нерв → обонятельная луковица → тракт → первичная обонятельная кора",center:"Луковица, миндалина и лимбические структуры",cortex:"Пириформная кора/крючок",clinic:"Аносмия, гипосмия, паросмия, фантосмия"},
{id:"gustatory",icon:"👅",ru:"Вкусовой",en:"Gustatory",kz:"Дәм сезу",receptor:"Вкусовые рецепторные клетки вкусовых почек",stimulus:"Растворённые химические вещества",path:"VII, IX, X → ядро одиночного пути → VPM таламуса → кора",center:"Ядро одиночного пути, VPM",cortex:"Островок и фронтальный оперкулум",clinic:"Агевзия, гипогевзия, дисгевзия"},
{id:"touch",icon:"✋",ru:"Тонкое осязание / давление",en:"Fine touch / pressure",kz:"Жанасу / қысым",receptor:"Мейсснер, Меркель, Пачини, Руффини",stimulus:"Прикосновение, давление, вибрация, растяжение кожи",path:"Рецептор → спинномозговой ганглий → задние столбы → ядра Голля/Бурдаха → медиальная петля → VPL",center:"VPL таламуса",cortex:"Поля 3,1,2 постцентральной извилины",clinic:"Полинейропатия, поражение задних столбов, сенсорная атаксия"},
{id:"pain",icon:"⚡",ru:"Болевой",en:"Pain",kz:"Ауырсыну",receptor:"Свободные нервные окончания / ноцицепторы",stimulus:"Повреждение ткани, экстремальная температура, механические/химические стимулы",path:"Aδ/C → задний рог → спиноталамический тракт → таламус → кора",center:"Таламус, ретикулярная формация, PAG",cortex:"Соматосенсорная кора, островок, передняя поясная кора",clinic:"Гипералгезия, аллодиния, нейропатическая и хроническая боль"},
{id:"temperature",icon:"🌡️",ru:"Температурный",en:"Temperature",kz:"Температура",receptor:"Свободные нервные окончания кожи и глубоких тканей",stimulus:"Тепло и холод",path:"Периферический нерв → задний рог → спиноталамический тракт → таламус → кора",center:"Таламус; гипоталамус участвует в терморегуляции",cortex:"Соматосенсорная/островковая кора",clinic:"Термоанестезия, гипо-/гиперестезия, полинейропатия"},
{id:"proprio",icon:"🦵",ru:"Проприоцептивный",en:"Proprioceptive",kz:"Проприоцептивтік",receptor:"Мышечные веретёна, органы Гольджи, суставные рецепторы",stimulus:"Длина мышцы, натяжение, положение сустава",path:"Периферический нерв → спинной мозг → спинно-мозжечковые пути; сознательная проприоцепция → медиальная петля → таламус",center:"Мозжечок, таламус",cortex:"Поля 3,1,2",clinic:"Сенсорная атаксия, поражение задних столбов, мозжечковая дисфункция"},
{id:"visceral",icon:"🫀",ru:"Висцеральный / интероцептивный",en:"Visceral / interoceptive",kz:"Висцералдық / интероцептивтік",receptor:"Рецепторы растяжения, давления и хеморецепторы внутренних органов и сосудов",stimulus:"Растяжение, химические изменения, АД, состояние внутренних органов",path:"Висцеральные афференты IX/X и спинальных нервов → ствол/спинной мозг → таламус/гипоталамус",center:"Ядро одиночного пути, гипоталамус, таламус",cortex:"Островок и поясная кора",clinic:"Висцеральная и отражённая боль, автономная дисфункция"}
];

const L={RU:{title:"Интерактивная лаборатория анализаторов",intro:"Выберите анализатор. Нажимайте этапы по порядку, чтобы увидеть, где возникает сигнал и как он достигает коры. Затем попробуйте отключить один участок пути и посмотрите, что изменится.",modes:["Путь сигнала","Повреждение пути","Сравнение"],stages:["Рецептор","Стимул","Проводящий путь","Подкорковый центр","Кора"],next:"Следующий этап",reset:"Сначала",lesion:"Что произойдёт, если повредить этот участок?",choose:"Выберите участок пути",compare:"Сравнить с"},EN:{title:"Interactive analyzer laboratory",intro:"Choose a sensory analyzer. Step through the pathway to see where the signal begins and how it reaches cortex. Then disable one part of the pathway and observe what changes.",modes:["Signal pathway","Pathway lesion","Compare"],stages:["Receptor","Stimulus","Pathway","Subcortical center","Cortex"],next:"Next stage",reset:"Reset",lesion:"What happens if this part is damaged?",choose:"Choose a pathway segment",compare:"Compare with"},KZ:{title:"Анализаторлардың интерактивті зертханасы",intro:"Анализаторды таңдаңыз. Сигналдың қай жерде пайда болып, қыртысқа қалай жететінін көру үшін кезеңдерді ретімен басыңыз. Кейін жолдың бір бөлігін өшіріп, не өзгеретінін бақылаңыз.",modes:["Сигнал жолы","Жолдың зақымдануы","Салыстыру"],stages:["Рецептор","Стимул","Өткізгіш жол","Қыртысасты орталық","Қыртыс"],next:"Келесі кезең",reset:"Бастау",lesion:"Бұл бөлік зақымдалса не болады?",choose:"Жол бөлігін таңдаңыз",compare:"Салыстыру"}} as const;

const name=(a:Analyzer,l:Language)=>l==="RU"?a.ru:l==="KZ"?a.kz:a.en;
export default function SensorySystemsLab({language}:{language:Language}){
 const t=L[language]; const[selected,setSelected]=useState(0); const[step,setStep]=useState(0); const[mode,setMode]=useState(0); const[compare,setCompare]=useState(1); const[answer,setAnswer]=useState<string|null>(null);
 const a=A[selected]; const b=A[compare];
 const stageValues=[a.receptor,a.stimulus,a.path,a.center,a.cortex];

 return <section className={styles.lab}>
   <div className={styles.header}><div><h2>{t.title}</h2><p>{t.intro}</p></div><div className={styles.progress} aria-label="progress"><span style={{width:`${(step+1)*20}%`}}/></div></div>
   <div className={styles.mode}>{t.modes.map((m,i)=><button type="button" key={m} data-active={mode===i} onClick={()=>{setMode(i);setAnswer(null)}}>{m}</button>)}</div>
   <div className={styles.grid}>
    <div className={styles.list}>{A.map((x,i)=><button type="button" className={styles.analyzer} data-active={selected===i} key={x.id} onClick={()=>{setSelected(i);setStep(0);setAnswer(null)}}><span className={styles.icon}>{x.icon}</span><span>{name(x,language)}</span></button>)}</div>
    <div className={styles.main}>
      {mode===0&&<><div className={styles.stageMap}>{t.stages.map((s,i)=><button type="button" className={styles.stage} data-active={step===i} key={s} onClick={()=>setStep(i)}><b>{i+1}. {s}</b><small>{stageValues[i]}</small></button>)}</div><div className={styles.detail}><strong>{t.stages[step]}</strong><p>{stageValues[step]}</p></div><div className={styles.actions}><button type="button" onClick={()=>setStep(s=>Math.min(4,s+1))} disabled={step===4}>{t.next}</button><button type="button" onClick={()=>setStep(0)}>{t.reset}</button></div></>}
      {mode===1&&<div className={styles.clinical}><div className={styles.card}><h3>{t.choose}</h3><p className={styles.muted}>{a.path}</p><div className={styles.quizOptions}>{[0,2,3,4].map(i=><button type="button" key={i} onClick={()=>setAnswer(String(i))}>{t.stages[i]}</button>)}</div></div><div className={styles.card}><h3>{t.lesion}</h3>{!answer&&<p className={styles.muted}>{language==="RU"?"Нажмите один из участков слева.":language==="KZ"?"Сол жақтағы бөліктердің бірін басыңыз.":"Select one segment on the left."}</p>}{answer&&<p>{answer==="0"?(language==="RU"?"Сигнал не сформируется или резко ослабнет уже на входе.":language==="KZ"?"Сигнал кіреберісте пайда болмайды немесе қатты әлсірейді.":"The signal will fail to form or be greatly reduced at the input."):answer==="2"?(language==="RU"?"Сигнал возникнет в рецепторе, но не достигнет вышележащих центров по этому пути.":language==="KZ"?"Сигнал рецепторда пайда болады, бірақ осы жолмен жоғары орталықтарға жетпейді.":"The signal forms at the receptor but cannot reach higher centers through this pathway."):answer==="3"?(language==="RU"?"Нарушатся переключение и интеграция сигнала перед его передачей к коре.":language==="KZ"?"Сигналды қыртысқа жеткізер алдындағы ауысу мен интеграция бұзылады.":"Relay and integration before cortical transmission will be disrupted."):language==="RU"?"Периферический сигнал может дойти до подкорковых структур, но осознанное восприятие или распознавание будет нарушено.":language==="KZ"?"Перифериялық сигнал қыртысасты құрылымдарға жетуі мүмкін, бірақ саналы қабылдау немесе тану бұзылады.":"Peripheral input may reach subcortical structures, but conscious perception or recognition will be impaired."}</p>}</div></div>}
      {mode===2&&<><label>{t.compare}: <select value={compare} onChange={e=>setCompare(+e.target.value)}>{A.map((x,i)=><option value={i} key={x.id}>{name(x,language)}</option>)}</select></label><div className={styles.compare}><div className={styles.card}><h3>{a.icon} {name(a,language)}</h3><p><b>{t.stages[0]}:</b> {a.receptor}</p><p><b>{t.stages[2]}:</b> {a.path}</p><p><b>{t.stages[4]}:</b> {a.cortex}</p></div><div className={styles.card}><h3>{b.icon} {name(b,language)}</h3><p><b>{t.stages[0]}:</b> {b.receptor}</p><p><b>{t.stages[2]}:</b> {b.path}</p><p><b>{t.stages[4]}:</b> {b.cortex}</p></div></div></>}
    </div>
   </div>
   <ExperimentReflection language={language} theoryHref={`/modules/21/theory?lang=${language}`}/>
 </section>
}