"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
import AdvancedAnatomyReference from "./AdvancedAnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Лаборатория сна и циркадных ритмов",a:"Гомеостатическое давление сна",b:"Циркадный сигнал бодрствования",out:"Условная склонность ко сну",predict:"Прогноз",task:"Сначала сформулируйте прогноз. Затем изменяйте только один параметр за опыт, запишите результат и объясните механизм.",save:"Записать опыт",explain:"Объяснение",limit:"Модель иллюстрирует двухпроцессную концепцию регуляции сна: гомеостатическое давление сна (Process S) нарастает при бодрствовании и снижается во сне, а циркадный компонент (Process C), связанный с супрахиазматическим ядром, меняет склонность ко сну в зависимости от биологического времени. Эти процессы взаимодействуют нелинейно; результат нельзя трактовать как стадию сна, ЭЭГ-паттерн или диагноз."},EN:{title:"Sleep and circadian laboratory",a:"Homeostatic sleep pressure",b:"Circadian wake drive",out:"Modeled sleep propensity",predict:"Prediction",task:"Make a prediction first. Then change only one parameter per trial, record the result, and explain the mechanism.",save:"Record trial",explain:"Explanation",limit:"This model illustrates the two-process concept of sleep regulation: homeostatic sleep pressure (Process S) rises during wakefulness and falls during sleep, while the circadian component (Process C), linked to the suprachiasmatic nucleus, changes sleep propensity with biological time. Their interaction is not simply linear; the output is not a sleep stage, EEG pattern, or diagnosis."},KZ:{title:"Ұйқы және циркадтық ырғақтар зертханасы",a:"Ұйқының гомеостатикалық қысымы",b:"Сергектіктің циркадтық сигналы",out:"Ұйқыға шартты бейімділік",predict:"Болжам",task:"Алдымен болжам жасаңыз. Әр тәжірибеде тек бір параметрді өзгертіп, нәтижені жазып, механизмді түсіндіріңіз.",save:"Тәжірибені жазу",explain:"Түсіндірме",limit:"Бұл модель ұйқы реттелуінің екі үдерістік тұжырымдамасын көрсетеді: гомеостатикалық ұйқы қысымы (S үдерісі) сергектік кезінде өсіп, ұйқыда төмендейді, ал супрахиазмалық ядромен байланысты циркадтық компонент (C үдерісі) биологиялық уақытқа қарай ұйқыға бейімділікті өзгертеді. Олардың өзара әсері жай сызықтық емес; нәтиже ұйқы сатысы, ЭЭГ үлгісі немесе диагноз емес."}} as const;
function calc(a:number,b:number){return Math.max(0,Math.min(100,Math.round(50+a*.55-b*.45)));}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(60),[b,setB]=useState(40),[prediction,setPrediction]=useState(""),[rows,setRows]=useState<Row[]>([]);const value=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AdvancedAnatomyReference moduleId={24} language={language}/><p><strong>{t.task}</strong></p><label>{t.predict}<textarea value={prediction} onChange={e=>setPrediction(e.target.value)} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a}%<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b}%<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 180" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><path d="M60 90 H250" stroke="currentColor" strokeWidth={2+a/25}/><circle cx="310" cy="90" r="42" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M352 90 H555" stroke="currentColor" strokeWidth={2+value/25}/><circle cx="600" cy="90" r={12+value/9} fill="none" stroke="currentColor" strokeWidth="3"/><text x="255" y="155">{t.out}: {value}%</text></svg><button disabled={!prediction.trim()} onClick={()=>{setRows(r=>[...r,{id:Date.now(),a,b,out:value,note:""}]);recordOutcome(24,"interactive",prediction.trim().length>=20?1:0,1);recordOutcome(24,"criterion:mechanism:lab-prediction",prediction.trim().length>=20?1:0,1)}}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.out}</th><th>{t.explain}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}</td><td>{r.b}</td><td>{r.out}%</td><td><input value={r.note} onChange={e=>{const note=e.target.value;setRows(xs=>xs.map(q=>q.id===r.id?{...q,note}:q));if(note.trim().length>=30){recordOutcome(24,"criterion:justification:lab",1,1);recordOutcome(24,"criterion:correction:experiment-reflection",rows.length>=2?1:0,1)}}}/></td></tr>)}</tbody></table></div><ExperimentReflection language={language} theoryHref={`/modules/24/theory?lang=${language}`}/><p><small>{t.limit}</small></p></section>}
