"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
import AnatomyReference from "./AnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Пространственное разрешение соматосенсорной системы",a:"Модельное расстояние между точками",b:"Условный размер рецептивного поля",c:"Условный индекс различения",d:"Прогноз двухточечного различения",task:"Сформулируйте прогноз. Измените один параметр, сохранив второй постоянным; затем поменяйте второй и сравните результаты.",save:"Записать опыт",prediction:"Прогноз перед опытом",note:"Физиологическое объяснение",limit:"Меньшие рецептивные поля, высокая плотность афферентов и латеральное торможение обычно улучшают пространственное различение. Миллиметры — параметры учебной модели, а не измеренный размер поля или нормативный двухточечный порог. Используйте безразмерный индекс только для сравнения условий, не для диагностики."},EN:{title:"Somatosensory spatial resolution",a:"Modelled point separation",b:"Conditional receptive-field size",c:"Conditional discrimination index",d:"Predicted two-point resolution",task:"Make a prediction. Change one parameter while holding the other constant, then change the second and compare results.",save:"Record trial",prediction:"Prediction before trial",note:"Physiological explanation",limit:"Smaller receptive fields, higher afferent density, and lateral inhibition generally support finer spatial discrimination. Millimetres are teaching-model parameters, not a measured field size or normative two-point threshold. Use the dimensionless index only to compare conditions, not for diagnosis."},KZ:{title:"Соматосенсорлық кеңістіктік айырымдылық",a:"Нүктелердің модельдік аралығы",b:"Рецептивтік өрістің шартты өлшемі",c:"Шартты ажырату индексі",d:"Екі нүктені ажырату болжамы",task:"Алдымен болжам жасаңыз. Бір параметрді тұрақты екіншісінде өзгертіңіз, кейін екіншісін өзгертіп нәтижелерді салыстырыңыз.",save:"Тәжірибені жазу",prediction:"Тәжірибеге дейінгі болжам",note:"Физиологиялық түсіндірме",limit:"Кіші рецептивтік өрістер, афференттердің жоғары тығыздығы және латералдық тежелу кеңістіктік ажыратуды жақсартады. Миллиметрлер — өлшенген өріс өлшемі немесе нормативтік табалдырық емес, оқу моделінің параметрлері. Өлшемсіз индексті тек жағдайларды салыстыру үшін қолданыңыз."}} as const;
function calc(a:number,b:number){return Math.max(0,Math.min(100,Math.round(100-(b-a)*1.25)))}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(20),[b,setB]=useState(35),[prediction,setPrediction]=useState(""),[revealed,setRevealed]=useState(false),[rows,setRows]=useState<Row[]>([]);const out=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AnatomyReference moduleId={19} language={language}/><p><strong>{t.task}</strong></p><label>{t.prediction}<textarea value={prediction} onChange={e=>{setPrediction(e.target.value);setRevealed(false)}} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a} mm<input type="range" min="2" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b} mm<input type="range" min="2" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 190" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><circle cx="90" cy="95" r={12+b/4} fill="none" stroke="currentColor" strokeWidth="3"/><circle cx={90+a} cy="95" r="6"/><circle cx="520" cy="95" r={12+out/8} fill="none" stroke="currentColor" strokeWidth="3"/><path d="M160 95 H470" stroke="currentColor" strokeWidth="4"/><text x="260" y="70">{t.c}</text>{revealed&&<text x="290" y="120">{out}/100</text>}</svg><button type="button" disabled={!prediction.trim()} onClick={()=>{setRevealed(true);recordOutcome(19,"interactive",prediction.trim().length>=20?1:0,1);recordOutcome(19,"criterion:application:lab",1,1);setRows(r=>[...r,{id:Date.now(),a,b,out,note:""}])}}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.c}</th><th>{t.note}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a} mm</td><td>{r.b} mm</td><td>{r.out}/100</td><td><input aria-label={t.note} value={r.note} onChange={e=>{const note=e.target.value;setRows(xs=>xs.map(q=>q.id===r.id?{...q,note}:q));if(note.trim().length>=30)recordOutcome(19,"criterion:justification:lab",1,1)}}/></td></tr>)}</tbody></table></div><p><small>{t.limit}</small></p><ExperimentReflection language={language} theoryHref={`/modules/19/theory?lang=${language}`}/></section>}
