"use client";
import {useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
type Row={id:number;input:number;gate:number;relay:number;cortex:number;note:string};
const T={
 RU:{title:"Лаборатория таламо-кортикального пропускания",intro:"Изменяйте силу сенсорного входа и условную степень таламического пропускания.",input:"Сенсорный вход",gate:"Условное таламическое пропускание",relay:"Условная эффективность релейной передачи",cortex:"Условный индекс коркового ответа",save:"Записать опыт",note:"Объясните роль таламического контроля",task:"Сравните одинаковый сенсорный вход при низком и высоком пропускании.",model:"Оба показателя — безразмерные индексы учебной модели (0–100), а не физиологические измерения.",limit:"Это упрощённая модель таламо-кортикальной передачи, а не универсальный «регулятор громкости». Таламические релейные нейроны работают в тоническом и пачечном режимах; возбудимость зависит от мембранного потенциала и T-типа Ca²⁺-каналов. Передачу также изменяют ретикулярное ядро таламуса, кортико-таламическая обратная связь, внимание и состояние сон–бодрствование."},
 EN:{title:"Thalamocortical gating laboratory",intro:"Change sensory input strength and modelled thalamic gating.",input:"Sensory input",gate:"Modelled thalamic gating",relay:"Conditional relay-efficiency index",cortex:"Conditional cortical-response index",save:"Record trial",note:"Explain thalamic control",task:"Compare the same sensory input with low and high transmission.",model:"Both values are dimensionless teaching-model indices (0–100), not physiological measurements.",limit:"This is a simplified model of thalamocortical transmission, not a universal volume control. Thalamic relay neurons can operate in tonic and burst modes; excitability depends on membrane potential and T-type Ca²⁺ channels. The thalamic reticular nucleus, corticothalamic feedback, attention, and sleep–wake state also shape transmission."},
 KZ:{title:"Таламо-қыртыстық өткізу зертханасы",intro:"Сенсорлық кіріс күшін және таламустық өткізудің шартты деңгейін өзгертіңіз.",input:"Сенсорлық кіріс",gate:"Модельдік таламустық өткізу",relay:"Релейлік берілістің шартты тиімділік индексі",cortex:"Қыртыстық жауаптың шартты индексі",save:"Тәжірибені жазу",note:"Таламустық бақылауды түсіндіріңіз",task:"Бірдей сенсорлық кірісті төмен және жоғары өткізу жағдайында салыстырыңыз.",model:"Екі көрсеткіш те оқу моделінің өлшемсіз индекстері (0–100), физиологиялық өлшемдер емес.",limit:"Бұл таламо-қыртыстық берілістің жеңілдетілген моделі, әмбебап «дыбыс реттегіші» емес. Таламустың релейлік нейрондары тоникалық және топтық разряд режимдерінде жұмыс істейді; қозғыштық мембраналық потенциал мен T-типті Ca²⁺ арналарына тәуелді. Беріліске ретикулярлық ядро, кортико-таламустық кері байланыс, зейін және ұйқы–сергектік күйі де әсер етеді."},
} as const;
export default function ThalamusLab({language}:{language:Language}){
 const c=T[language];const[input,setInput]=useState(70),[gate,setGate]=useState(60),[rows,setRows]=useState<Row[]>([]);const relay=Math.round(input*gate/100),cortex=Math.min(100,Math.round(relay*.9+5));
 return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{c.title}</h2><p>{c.intro}</p><p><strong>{c.task}</strong></p><label>{c.input}: {input}<input type="range" min="0" max="100" value={input} onChange={e=>setInput(+e.target.value)} style={{width:"100%"}}/></label><label>{c.gate}: {gate}<input type="range" min="0" max="100" value={gate} onChange={e=>setGate(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 190" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={c.title}><circle cx="70" cy="85" r="28" fill="none" stroke="currentColor" strokeWidth="3"/><ellipse cx="335" cy="85" rx="65" ry="42" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M98 85 H270" stroke="currentColor" strokeWidth={2+input/25}/><path d="M400 85 H585" stroke="currentColor" strokeWidth={2+relay/25}/><path d="M585 85 C620 55 630 40 650 30" fill="none" stroke="currentColor" strokeWidth={2+cortex/25}/><text x="295" y="90">Thalamus</text><text x="410" y="145">{relay}</text><text x="590" y="145">{cortex}</text></svg><p><strong>{c.relay}: {relay}/100</strong><br/>{c.cortex}: {cortex}/100</p><p><small>{c.model}</small></p><button type="button" onClick={()=>{recordOutcome(14,"interactive",1,1);recordOutcome(14,"criterion:application:lab",1,1);setRows(x=>[...x,{id:Date.now(),input,gate,relay,cortex,note:""}])}}>{c.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{c.input}</th><th>{c.gate}</th><th>{c.relay}</th><th>{c.cortex}</th><th>{c.note}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.input}</td><td>{r.gate}</td><td>{r.relay}/100</td><td>{r.cortex}/100</td><td><input aria-label={c.note} value={r.note} onChange={e=>{const note=e.target.value;setRows(xs=>xs.map(x=>x.id===r.id?{...x,note}:x));if(note.trim().length>=30)recordOutcome(14,"criterion:justification:lab",1,1)}}/></td></tr>)}</tbody></table></div><p><small>{c.limit}</small></p><ExperimentReflection language={language} theoryHref={`/modules/14/theory?lang=${language}`}/></section>
}
