"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import AnatomyReference from "./AnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Зрительная адаптация",a:"Условная яркость",b:"Условный контраст",c:"Условный индекс зрительного ответа",task:"Сформулируйте прогноз. Измените один параметр, сохранив второй постоянным; затем поменяйте второй и сравните результаты.",save:"Записать опыт",prediction:"Прогноз перед опытом",note:"Физиологическое объяснение",limit:"Модель объединяет адаптацию к среднему уровню освещения и чувствительность к контрасту. Фоторецепторы гиперполяризуются на свет, а контраст кодируется также сетчаточными цепями. Безразмерный индекс 0–100 — не сила фоторецептора, острота зрения или клиническое измерение."},EN:{title:"Visual adaptation",a:"Conditional luminance",b:"Conditional contrast",c:"Conditional visual-response index",task:"Make a prediction. Change one parameter while holding the other constant, then change the second and compare results.",save:"Record trial",prediction:"Prediction before trial",note:"Physiological explanation",limit:"The model combines adaptation to mean luminance with contrast sensitivity. Photoreceptors hyperpolarize to light, while retinal circuits also encode contrast. The dimensionless 0–100 index is not photoreceptor strength, visual acuity, or a clinical measurement."},KZ:{title:"Көру бейімделуі",a:"Шартты жарықтылық",b:"Шартты контраст",c:"Көру жауабының шартты индексі",task:"Алдымен болжам жасаңыз. Бір параметрді тұрақты екіншісінде өзгертіңіз, кейін екіншісін өзгертіп нәтижелерді салыстырыңыз.",save:"Тәжірибені жазу",prediction:"Тәжірибеге дейінгі болжам",note:"Физиологиялық түсіндірме",limit:"Модель орташа жарықтылыққа бейімделу мен контраст сезімталдығын біріктіреді. Фоторецепторлар жарыққа гиперполяризацияланады, контрастты торқабық тізбектері де кодтайды. Өлшемсіз 0–100 индексі фоторецептор күші, көру өткірлігі немесе клиникалық өлшем емес."}} as const;
function calc(a:number,b:number){return Math.max(0,Math.min(100,Math.round((Math.log10(a+1)/2.01)*65+b*.35)))}
export default function Lab({language}:{language:Language}){const t=C[language];const[a,setA]=useState(60),[b,setB]=useState(50),[prediction,setPrediction]=useState(""),[rows,setRows]=useState<Row[]>([]);const out=useMemo(()=>calc(a,b),[a,b]);return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AnatomyReference moduleId={20} language={language}/><p><strong>{t.task}</strong></p><label>{t.prediction}<textarea value={prediction} onChange={e=>setPrediction(e.target.value)} rows={2} style={{width:"100%"}}/></label><label>{t.a}: {a}/100<input type="range" min="0" max="100" value={a} onChange={e=>setA(+e.target.value)} style={{width:"100%"}}/></label><label>{t.b}: {b}/100<input type="range" min="0" max="100" value={b} onChange={e=>setB(+e.target.value)} style={{width:"100%"}}/></label><svg viewBox="0 0 680 190" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><circle cx="90" cy="95" r={18+a/7} fill="none" stroke="currentColor" strokeWidth="3"/><path d="M130 95 H500" stroke="currentColor" strokeWidth={2+out/30}/><circle cx="560" cy="95" r={12+out/8} fill="none" stroke="currentColor" strokeWidth="3"/><text x="245" y="70">{t.c}</text><text x="300" y="120">{out}/100</text></svg><button type="button" disabled={!prediction.trim()} onClick={()=>setRows(r=>[...r,{id:Date.now(),a,b,out,note:""}])}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.c}</th><th>{t.note}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}/100</td><td>{r.b}/100</td><td>{r.out}/100</td><td><input aria-label={t.note} value={r.note} onChange={e=>setRows(xs=>xs.map(q=>q.id===r.id?{...q,note:e.target.value}:q))}/></td></tr>)}</tbody></table></div><p><small>{t.limit}</small></p><ExperimentReflection language={language} theoryHref={`/modules/20/theory?lang=${language}`}/></section>}
