"use client";
import {useMemo,useState} from "react";
import type {Language} from "../content/course";
import ExperimentReflection from "./ExperimentReflection";
import {recordOutcome} from "../lib/courseProgress";
import AnatomyReference from "./AnatomyReference";
type Row={id:number;a:number;b:number;out:number;note:string};
const C={RU:{title:"Зрительная адаптация",a:"Условная яркость",b:"Условный контраст",c:"Условный индекс зрительного ответа",task:"Сформулируйте прогноз. Измените один параметр, сохранив второй постоянным; затем поменяйте второй и сравните результаты.",save:"Записать опыт",prediction:"Прогноз перед опытом",note:"Физиологическое объяснение",limit:"Модель объединяет адаптацию к среднему уровню освещения и чувствительность к контрасту. Фоторецепторы гиперполяризуются на свет, а контраст кодируется также сетчаточными цепями. Безразмерный индекс 0–100 — не сила фоторецептора, острота зрения или клиническое измерение."},EN:{title:"Visual adaptation",a:"Conditional luminance",b:"Conditional contrast",c:"Conditional visual-response index",task:"Make a prediction. Change one parameter while holding the other constant, then change the second and compare results.",save:"Record trial",prediction:"Prediction before trial",note:"Physiological explanation",limit:"The model combines adaptation to mean luminance with contrast sensitivity. Photoreceptors hyperpolarize to light, while retinal circuits also encode contrast. The dimensionless 0–100 index is not photoreceptor strength, visual acuity, or a clinical measurement."},KZ:{title:"Көру бейімделуі",a:"Шартты жарықтылық",b:"Шартты контраст",c:"Көру жауабының шартты индексі",task:"Алдымен болжам жасаңыз. Бір параметрді тұрақты екіншісінде өзгертіңіз, кейін екіншісін өзгертіп нәтижелерді салыстырыңыз.",save:"Тәжірибені жазу",prediction:"Тәжірибеге дейінгі болжам",note:"Физиологиялық түсіндірме",limit:"Модель орташа жарықтылыққа бейімделу мен контраст сезімталдығын біріктіреді. Фоторецепторлар жарыққа гиперполяризацияланады, контрастты торқабық тізбектері де кодтайды. Өлшемсіз 0–100 индексі фоторецептор күші, көру өткірлігі немесе клиникалық өлшем емес."}} as const;
function calc(a:number,b:number){return Math.max(0,Math.min(100,Math.round((Math.log10(a+1)/2.01)*65+b*.35)))}
const P={RU:{prompt:"Выберите, какой параметр измените первым, и предскажите направление изменения условного индекса зрительного ответа при неизменном втором параметре.",parameter:"Изменяемый параметр",direction:"Прогноз индекса",luminance:"Яркость",contrast:"Контраст",up:"Увеличится",down:"Уменьшится",same:"Не изменится"},EN:{prompt:"Choose the parameter to change first and predict the direction of the conditional visual-response index while the other parameter remains fixed.",parameter:"Parameter changed",direction:"Index prediction",luminance:"Luminance",contrast:"Contrast",up:"Increase",down:"Decrease",same:"No change"},KZ:{prompt:"Алдымен өзгертілетін параметрді таңдап, екінші параметр тұрақты кезде көру жауабының шартты индексі қай бағытта өзгеретінін болжаңыз.",parameter:"Өзгертілетін параметр",direction:"Индекс болжамы",luminance:"Жарықтылық",contrast:"Контраст",up:"Жоғарылайды",down:"Төмендейді",same:"Өзгермейді"}} as const;
type Target="luminance"|"contrast";type Direction="up"|"down"|"same";
export default function Lab({language}:{language:Language}){
 const t=C[language],p=P[language];const[a,setA]=useState(60),[b,setB]=useState(50),[target,setTarget]=useState<Target|null>(null),[direction,setDirection]=useState<Direction|null>(null),[revealed,setRevealed]=useState(false),[rows,setRows]=useState<Row[]>([]);const out=useMemo(()=>calc(a,b),[a,b]);const ready=target!==null&&direction!==null;
 return <section style={{margin:"28px 0",padding:20,border:"1px solid #cfe0ea",borderRadius:16}}><h2>{t.title}</h2><AnatomyReference moduleId={20} language={language}/><p><strong>{p.prompt}</strong></p>
 <fieldset><legend>{t.prediction}</legend><p><strong>{p.parameter}</strong></p>{(["luminance","contrast"] as Target[]).map(x=><label key={x} style={{display:"inline-flex",gap:6,marginRight:16,minHeight:44,alignItems:"center"}}><input type="radio" name="target" checked={target===x} onChange={()=>{setTarget(x);setRevealed(false)}}/>{p[x]}</label>)}<p><strong>{p.direction}</strong></p>{(["up","down","same"] as Direction[]).map(x=><label key={x} style={{display:"inline-flex",gap:6,marginRight:16,minHeight:44,alignItems:"center"}}><input type="radio" name="direction" checked={direction===x} onChange={()=>{setDirection(x);setRevealed(false)}}/>{p[x]}</label>)}</fieldset>
 <label>{t.a}: {a}/100<input type="range" min="0" max="100" value={a} onChange={e=>{setA(+e.target.value);setRevealed(false)}} style={{width:"100%"}}/></label><label>{t.b}: {b}/100<input type="range" min="0" max="100" value={b} onChange={e=>{setB(+e.target.value);setRevealed(false)}} style={{width:"100%"}}/></label>
 <svg viewBox="0 0 680 190" style={{width:"100%",background:"#fff",margin:"14px 0"}} role="img" aria-label={t.title}><circle cx="90" cy="95" r={18+a/7} fill="none" stroke="currentColor" strokeWidth="3"/><path d="M130 95 H500" stroke="currentColor" strokeWidth={2+out/30}/><circle cx="560" cy="95" r={12+out/8} fill="none" stroke="currentColor" strokeWidth="3"/><text x="245" y="70">{t.c}</text>{revealed&&<text x="300" y="120">{out}/100</text>}</svg>
 <button type="button" disabled={!ready} onClick={()=>{setRevealed(true);recordOutcome(20,"interactive",1,1);recordOutcome(20,"criterion:application:lab",1,1);recordOutcome(20,"criterion:mechanism:lab-prediction",1,1);setRows(r=>[...r,{id:Date.now(),a,b,out,note:""}])}}>{t.save}</button><div style={{overflowX:"auto"}}><table><thead><tr><th>#</th><th>{t.a}</th><th>{t.b}</th><th>{t.c}</th><th>{t.note}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.a}/100</td><td>{r.b}/100</td><td>{r.out}/100</td><td><input aria-label={t.note} value={r.note} onChange={e=>{const note=e.target.value;setRows(xs=>xs.map(q=>q.id===r.id?{...q,note}:q));if(note.trim().length>=30)recordOutcome(20,"criterion:justification:lab",1,1)}}/></td></tr>)}</tbody></table></div><p><small>{t.limit}</small></p><ExperimentReflection language={language} theoryHref={`/modules/20/theory?lang=${language}`}/></section>
}
