"use client";

import {useId,useState} from "react";
import type {Language} from "../content/course";
import styles from "./VisualPathwayLocalizer.module.css";

type Site="retina"|"nerve"|"chiasm"|"tract"|"radiation"|"cortex";
const sites:Site[]=["retina","nerve","chiasm","tract","radiation","cortex"];
const copy={
 RU:{title:"Локализация поражения зрительного пути",intro:"Сначала сравните поле зрения правого и левого глаза. Тёмная область — участок, который пациент не видит. Затем выберите место повреждения и проследите, какие волокна перестают проводить сигнал.",meridian:"Вертикальный меридиан — воображаемая вертикальная линия через центр поля зрения. Если выпадение заканчивается у этой линии в обоих глазах, это помогает локализовать повреждение после сетчатки.",choose:"Выберите место повреждения",eyes:["Левый глаз","Правый глаз"],field:"Поле зрения",lost:"Выпавший участок",cross:"В хиазме перекрещиваются волокна от носовых половин сетчатки; височные волокна остаются на своей стороне.",sites:{retina:"Левая сетчатка",nerve:"Левый зрительный нерв",chiasm:"Хиазма",tract:"Левый зрительный тракт",radiation:"Левая зрительная лучистость",cortex:"Левая зрительная кора"},results:{retina:"Небольшой дефект только в поле левого глаза: локальное поражение сетчатки создаёт скотому, положение которой зависит от участка сетчатки.",nerve:"Всё поле левого глаза выпадает: левый зрительный нерв несёт сигналы только от левого глаза.",chiasm:"Выпадают височные половины обоих полей зрения (битемпоральная гемианопсия): повреждены перекрещивающиеся носовые волокна сетчатки.",tract:"Выпадает правая половина поля зрения обоих глаз (правосторонняя гомонимная гемианопсия): после хиазмы левый путь несёт информацию о правом поле зрения.",radiation:"В этой упрощённой модели выпадает правая половина обоих полей. В клинике часть зрительной лучистости может давать квадрантный дефект.",cortex:"Выпадает правая половина обоих полей: левая зрительная кора получает информацию о правом поле зрения. Сохранность центра поля требует отдельной проверки."}},
 EN:{title:"Visual-pathway lesion localization",intro:"First compare the visual fields of the right and left eyes. A dark area is a region the patient cannot see. Then select a lesion site and trace which fibers stop carrying the signal.",meridian:"The vertical meridian is an imaginary vertical line through the center of the visual field. Loss that ends at this line in both eyes helps localize damage beyond the retina.",choose:"Select a lesion site",eyes:["Left eye","Right eye"],field:"Visual field",lost:"Missing region",cross:"At the chiasm, fibers from the nasal halves of both retinas cross; temporal retinal fibers remain on the same side.",sites:{retina:"Left retina",nerve:"Left optic nerve",chiasm:"Optic chiasm",tract:"Left optic tract",radiation:"Left optic radiation",cortex:"Left visual cortex"},results:{retina:"A small defect appears only in the left eye: a focal retinal lesion produces a scotoma whose position depends on the retinal site.",nerve:"The entire left-eye field is lost because the left optic nerve carries signals only from the left eye.",chiasm:"The temporal half of each visual field is lost (bitemporal hemianopia) because crossing nasal retinal fibers are affected.",tract:"The right half of both visual fields is lost (right homonymous hemianopia): beyond the chiasm, the left pathway carries the right visual field.",radiation:"In this simplified model, the right half of both fields is lost. Clinically, partial optic-radiation damage may cause a quadrantic defect.",cortex:"The right half of both fields is lost because left visual cortex receives the right visual field. Central-field sparing must be tested separately."}},
 KZ:{title:"Көру жолы зақымының орнын анықтау",intro:"Алдымен оң және сол көздің көру өрістерін салыстырыңыз. Қараңғы аймақ — пациент көрмейтін бөлік. Содан кейін зақым орнын таңдап, қай талшықтар сигнал өткізбейтінін қадағалаңыз.",meridian:"Тік меридиан — көру өрісінің ортасы арқылы өтетін ойша тік сызық. Екі көздегі жоғалу осы сызықта аяқталса, бұл торқабықтан кейінгі зақымды табуға көмектеседі.",choose:"Зақым орнын таңдаңыз",eyes:["Сол көз","Оң көз"],field:"Көру өрісі",lost:"Көрінбейтін аймақ",cross:"Хиазмада екі торқабықтың мұрын жақ жартысынан шығатын талшықтар айқасады; самай жақ талшықтар өз жағында қалады.",sites:{retina:"Сол торқабық",nerve:"Сол көру жүйкесі",chiasm:"Көру хиазмасы",tract:"Сол көру тракты",radiation:"Сол көру сәулеленуі",cortex:"Сол көру қыртысы"},results:{retina:"Шағын ақау тек сол көз өрісінде пайда болады: торқабықтың ошақты зақымы орны зақымдалған бөлікке тәуелді скотома туғызады.",nerve:"Сол көздің бүкіл өрісі жоғалады, себебі сол көру жүйкесі тек сол көзден сигнал тасымалдайды.",chiasm:"Екі көру өрісінің самай жақ жартысы жоғалады (битемпоралдық гемианопсия): айқасатын мұрындық торқабық талшықтары зақымданған.",tract:"Екі көздің де көру өрісінің оң жартысы жоғалады (оң жақ гомонимдік гемианопсия): хиазмадан кейін сол жол оң көру өрісін тасымалдайды.",radiation:"Бұл ықшам модельде екі өрістің оң жартысы жоғалады. Клиникада көру сәулеленуінің бір бөлігі зақымданса, квадранттық ақау болуы мүмкін.",cortex:"Екі өрістің оң жартысы жоғалады: сол көру қыртысы оң көру өрісін қабылдайды. Өріс ортасының сақталуын бөлек тексеру керек."}}
} as const;

export default function VisualPathwayLocalizer({language}:{language:Language}){
 const [site,setSite]=useState<Site>("chiasm");
 const uid=useId().replaceAll(":","");
 const t=copy[language];
 const fullLeft=site==="nerve", temporal=site==="chiasm", rightHalf=["tract","radiation","cortex"].includes(site);
 return <section className={styles.lab} aria-labelledby={`${uid}-title`}>
  <h2 id={`${uid}-title`}>{t.title}</h2><p>{t.intro}</p><p className={styles.definition}>{t.meridian}</p>
  <fieldset className={styles.controls}><legend>{t.choose}</legend>{sites.map(value=><button type="button" key={value} aria-pressed={site===value} onClick={()=>setSite(value)}>{t.sites[value]}</button>)}</fieldset>
  <svg className={styles.pathway} viewBox="0 0 940 290" role="img" aria-labelledby={`${uid}-svg-title ${uid}-svg-desc`}>
   <title id={`${uid}-svg-title`}>{t.title}</title><desc id={`${uid}-svg-desc`}>{t.cross} {t.results[site]}</desc>
   <defs><marker id={`${uid}-arrow`} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0 10 5 0 10Z"/></marker></defs>
   <g className={styles.route}><path d="M95 70C210 70 220 145 360 145S505 70 610 70H860"/><path d="M95 220C210 220 220 145 360 145S505 220 610 220H860"/></g>
   <g className={styles.crossed}><path d="M95 70C220 70 235 220 610 220H860"/><path d="M95 220C220 220 235 70 610 70H860"/></g>
   {[{x:70,y:145,key:"retina"},{x:190,y:145,key:"nerve"},{x:360,y:145,key:"chiasm"},{x:510,y:145,key:"tract"},{x:660,y:145,key:"radiation"},{x:850,y:145,key:"cortex"}].map(n=><g key={n.key} className={site===n.key?styles.selected:styles.node}><circle cx={n.x} cy={n.y} r="25"/><text x={n.x} y={n.y+5}>{sites.indexOf(n.key as Site)+1}</text></g>)}
   <g className={styles.signal}><circle r="7"><animateMotion dur="3s" repeatCount="indefinite" path="M95 70C220 70 235 220 610 220H860"/></circle></g>
  </svg>
  <div className={styles.fields}>{t.eyes.map((eye,index)=><figure key={eye}><figcaption>{eye} · {t.field}</figcaption><div className={styles.field}><span className={styles.meridian}/>{site==="retina"&&index===0&&<span className={styles.scotoma} aria-label={t.lost}/>} {fullLeft&&index===0&&<span className={styles.full} aria-label={t.lost}/>} {temporal&&<span className={index===0?styles.leftHalf:styles.rightHalf} aria-label={t.lost}/>} {rightHalf&&<span className={styles.rightHalf} aria-label={t.lost}/>}</div></figure>)}</div>
  <p className={styles.result} role="status"><strong>{t.sites[site]}:</strong> {t.results[site]}</p><p>{t.cross}</p>
 </section>;
}
