import type { Language } from "../../course";
import type { DiagramNode, InteractiveLesson } from "../../interactive";
import { getSectionTitle } from "../../sections";

type Copy = [string, string, string]; // RU, EN, KZ
export function createInteractiveLesson(language: Language): InteractiveLesson {
  const t = (copy: Copy) => copy[language === "RU" ? 0 : language === "EN" ? 1 : 2];
  const node = (id: string, label: Copy, explanation: Copy): DiagramNode => ({ id, label: t(label), explanation: t(explanation) });
  return {
    kind: "interactive",
    title: getSectionTitle("interactive", language),
    introduction: t(["Исследуйте организацию нервной системы, путь сигнала и взаимодействие нервных влияний. Схемы связаны с теорией Модуля 1; это учебные модели, а не анатомические изображения или количественные симуляции.", "Explore nervous system organisation, signal pathways and interacting neural inputs. These diagrams follow Module 1 theory: they are teaching models, not anatomical images or quantitative simulations.", "Жүйке жүйесінің ұйымдасуын, сигнал жолын және жүйкелік әсерлердің өзара әрекетін зерттеңіз. Сызбалар Модуль 1 теориясына негізделген: бұлар анатомиялық кескіндер немесе сандық симуляциялар емес, оқу модельдері."]),
    ui: {
      instructions: t(["Как работать со схемой", "How to use the diagram", "Сызбамен жұмыс істеу"]),
      select: t(["Выберите элемент", "Select an element", "Элементті таңдаңыз"]),
      explanation: t(["Пояснение", "Explanation", "Түсіндірме"]),
      previous: t(["Предыдущий этап", "Previous step", "Алдыңғы кезең"]),
      next: t(["Следующий этап", "Next step", "Келесі кезең"]),
      reset: t(["К началу схемы", "Reset diagram", "Сызбаның басына"]),
      step: t(["Этап", "Step", "Кезең"]),
      theory: t(["Открыть соответствующий фрагмент теории", "Open the related theory passage", "Теорияның тиісті бөлігін ашу"]),
      returnToCenter: t(["Вернуть информацию в ЦНС", "Return information to the CNS", "Ақпаратты ОЖЖ-ге қайтару"]),
      keyboard: t(["Клавиатура: Tab и Shift+Tab — переход между кнопками, Enter или пробел — выбор. Выбранный элемент отмечен рамкой и состоянием кнопки; пояснение находится под схемой.", "Keyboard: Tab and Shift+Tab move between buttons; Enter or Space selects. A border and button state identify the selected element; its explanation appears below the diagram.", "Пернетақта: Tab және Shift+Tab батырмалар арасында ауыстырады, Enter немесе бос орын таңдайды. Таңдалған элемент жиекпен және батырма күйімен белгіленеді; түсіндірме сызбаның астында беріледі."]),
      active: t(["Включено", "On", "Қосулы"]), inactive: t(["Выключено", "Off", "Өшірулі"]),
      result: t(["Что меняется в модели", "What changes in the model", "Модельде не өзгереді"]),
    },
    organization: {
      id: "organization", title: t(["1. Организация: ЦНС и ПНС", "1. Organisation: CNS and PNS", "1. Ұйымдасу: ОЖЖ және ШЖЖ"]), anchor: "cns-pns",
      instruction: t(["Выберите структуру в одной из двух ветвей. Сравните её принадлежность и функцию. Обе ветви — части единой нервной системы.", "Select a structure in either branch. Compare its division and function. Both branches belong to one nervous system.", "Екі тармақтың біріндегі құрылымды таңдаңыз. Оның қай бөлімге жататынын және қызметін салыстырыңыз. Екі тармақ та біртұтас жүйке жүйесіне жатады."]),
      root: t(["Нервная система", "Nervous system", "Жүйке жүйесі"]),
      groups: [
        { id: "cns", title: t(["Центральная нервная система (ЦНС)", "Central nervous system (CNS)", "Орталық жүйке жүйесі (ОЖЖ)"]), nodes: [
          node("brain", ["Головной мозг", "Brain", "Ми"], ["Относится к ЦНС. Обрабатывает и интегрирует сигналы, участвует в организации движений, регуляции органов и высших нервных функциях.", "Part of the CNS. Processes and integrates signals and contributes to movement, organ regulation and higher nervous functions.", "ОЖЖ-ге жатады. Сигналдарды өңдеп, біріктіреді; қимылды ұйымдастыруға, мүшелерді реттеуге және жоғары жүйке қызметтеріне қатысады."]),
          node("spinal", ["Спинной мозг", "Spinal cord", "Жұлын"], ["Относится к ЦНС. Проводит информацию и содержит нейронные сети, обеспечивающие ряд рефлексов: это не только проводящий путь.", "Part of the CNS. Conducts information and contains circuits that mediate a range of reflexes: it is more than a conduction pathway.", "ОЖЖ-ге жатады. Ақпаратты өткізеді және бірқатар рефлекстерді іске асыратын нейрондық желілерді қамтиды: ол тек өткізгіш жол емес."]),
        ] },
        { id: "pns", title: t(["Периферическая нервная система (ПНС)", "Peripheral nervous system (PNS)", "Шеткі жүйке жүйесі (ШЖЖ)"]), nodes: [
          node("nerves", ["Нервы", "Nerves", "Жүйкелер"], ["Относятся к ПНС. Это пучки нервных волокон. Афферентные пути несут информацию к ЦНС, эфферентные — команды к мышцам и железам.", "Part of the PNS. Nerves are bundles of nerve fibres. Afferent pathways carry information towards the CNS; efferent pathways carry commands towards muscles and glands.", "ШЖЖ-ге жатады. Жүйкелер — жүйке талшықтарының шоғырлары. Афференттік жолдар ақпаратты ОЖЖ-ге, эфференттік жолдар бұйрықтарды бұлшықеттер мен бездерге жеткізеді."]),
          node("ganglia", ["Ганглии", "Ganglia", "Ганглийлер"], ["Относятся к ПНС. Ганглии — скопления тел нейронов вне центральной нервной системы.", "Part of the PNS. Ganglia are clusters of neuronal cell bodies outside the central nervous system.", "ШЖЖ-ге жатады. Ганглийлер — орталық жүйке жүйесінен тыс орналасқан нейрон денелерінің шоғырлары."]),
          node("endings", ["Нервные окончания", "Nerve endings", "Жүйке ұштары"], ["Относятся к ПНС. Чувствительные и двигательные окончания участвуют в связи нервной системы с органами и тканями.", "Part of the PNS. Sensory and motor endings help connect the nervous system with organs and tissues.", "ШЖЖ-ге жатады. Сезімтал және қозғалтқыш ұштар жүйке жүйесінің мүшелермен және тіндермен байланысына қатысады."]),
        ] },
      ],
    },
    pathway: {
      id: "pathway", title: t(["2. Путь сигнала и обратная связь", "2. Signal pathway and feedback", "2. Сигнал жолы және кері байланыс"]), anchor: "cns-pns",
      instruction: t(["Проследите защитную реакцию на горячий предмет: выбирайте звенья или переходите по этапам. В конце верните информацию о результате в ЦНС кнопкой обратной связи.", "Follow a protective response to a hot object: select nodes or move through the steps. At the end, return outcome information to the CNS using the feedback button.", "Ыстық затқа қорғаныш реакциясын бақылаңыз: буындарды таңдаңыз немесе кезеңдермен өтіңіз. Соңында кері байланыс батырмасы арқылы нәтиже туралы ақпаратты ОЖЖ-ге қайтарыңыз."]),
      nodes: [
        node("receptor", ["Рецептор", "Receptor", "Рецептор"], ["Рецептор воспринимает воздействие горячего предмета и преобразует его в сигнал для нервной системы.", "A receptor detects the hot object's stimulus and converts it into a signal for the nervous system.", "Рецептор ыстық заттың әсерін қабылдап, оны жүйке жүйесіне арналған сигналға түрлендіреді."]),
        node("afferent", ["Афферентный путь", "Afferent pathway", "Афференттік жол"], ["Сенсорная информация идёт от рецептора к ЦНС. Направление к центру отличает афферентный путь от эфферентного.", "Sensory information travels from the receptor towards the CNS. This inward direction distinguishes an afferent pathway from an efferent one.", "Сенсорлық ақпарат рецептордан ОЖЖ-ге бағытталады. Орталыққа бағытталуы афференттік жолды эфференттік жолдан ажыратады."]),
        node("center", ["ЦНС: интеграция", "CNS: integration", "ОЖЖ: интеграция"], ["Сигналы обрабатываются в центральных сетях. Спинальные сети могут организовать отдёргивание руки, а обработка в головном мозге обеспечивает осознанное восприятие боли. Интеграция происходит в ЦНС, а не в отдельном органе после неё.", "Central circuits process the signals. Spinal circuits can organise hand withdrawal, while brain processing supports conscious pain perception. Integration takes place within the CNS, not in a separate organ after it.", "Орталық желілер сигналдарды өңдейді. Жұлын желілері қолды тартып алуды ұйымдастыра алады, ал мидағы өңдеу ауырсынуды саналы сезінуді қамтамасыз етеді. Интеграция ОЖЖ-ден кейінгі бөлек мүшеде емес, ОЖЖ ішінде жүреді."]),
        node("efferent", ["Эфферентный путь", "Efferent pathway", "Эфференттік жол"], ["Команда направляется от ЦНС к исполнительному органу. В этом примере она поступает к мышцам руки.", "A command travels from the CNS towards an effector. In this example it reaches the arm muscles.", "Бұйрық ОЖЖ-ден атқарушы мүшеге бағытталады. Бұл мысалда ол қол бұлшықеттеріне жетеді."]),
        node("effector", ["Эффектор и ответ", "Effector and response", "Эффектор және жауап"], ["Мышцы выполняют ответ: рука отдёргивается. В других реакциях эффекторами могут быть железы. Эффектор — исполнитель, а не сенсорный вход.", "Muscles carry out the response: the hand withdraws. Glands can be effectors in other responses. An effector produces an output rather than a sensory input.", "Бұлшықеттер жауапты орындайды: қол тартып алынады. Басқа реакцияларда бездер эффектор бола алады. Эффектор — сенсорлық кіріс емес, жауапты орындаушы."]),
        node("feedback", ["Обратная связь", "Feedback", "Кері байланыс"], ["Информация о результате действия возвращается к центральным сетям и позволяет корректировать ответ. Это поступление информации, а не повторная двигательная команда.", "Information about the action's outcome returns to central circuits and allows the response to be adjusted. This is incoming information, not another motor command.", "Әрекет нәтижесі туралы ақпарат орталық желілерге қайтып, жауапты түзетуге мүмкіндік береді. Бұл — қайталанған қимыл бұйрығы емес, ақпараттың келуі."]),
      ],
      loop: t(["Обратная связь → ЦНС: интеграция → уточнение ответа. Линейная схема упрощает работу взаимодействующих нервных сетей.", "Feedback → CNS integration → adjustment of the response. This linear diagram simplifies interacting neural networks.", "Кері байланыс → ОЖЖ-дегі интеграция → жауапты нақтылау. Сызықтық сызба өзара әрекеттесетін жүйкелік желілер жұмысын жеңілдетіп көрсетеді."]),
    },
    synapse: {
      id: "synapse", title: t(["3. Проведение и межклеточная передача", "3. Conduction and intercellular transmission", "3. Өткізу және жасушааралық берілу"]), anchor: "principles",
      instruction: t(["Сравните два этапа: проведение сигнала по нервному волокну и передачу влияния следующей клетке. Молекулярные механизмы синапса изучаются позже.", "Compare two stages: conduction along a nerve fibre and transmission of influence to the next cell. Molecular synaptic mechanisms are studied later.", "Екі кезеңді салыстырыңыз: жүйке талшығы бойымен сигнал өткізу және әсерді келесі жасушаға беру. Синапстың молекулалық тетіктері кейін оқытылады."]),
      modes: [
        { id: "chemical", title: t(["Химический синапс", "Chemical synapse", "Химиялық синапс"]), note: t(["Проследите последовательность от прихода потенциала действия до ответа постсинаптической клетки.", "Follow the sequence from action-potential arrival to the postsynaptic response.", "Әрекет потенциалы келгеннен постсинапстық жауапқа дейінгі ретті бақылаңыз."]), nodes: [
          node("arrival", ["Приход потенциала действия", "Action-potential arrival", "Әрекет потенциалының келуі"], ["Потенциал действия достигает пресинаптического окончания и деполяризует его мембрану.", "The action potential reaches the presynaptic terminal and depolarizes its membrane.", "Әрекет потенциалы пресинапстық ұшқа жетіп, оның мембранасын деполяризациялайды."]),
          node("calcium", ["Вход Ca²⁺", "Ca²⁺ entry", "Ca²⁺ кіруі"], ["Деполяризация открывает потенциал-зависимые кальциевые каналы; Ca²⁺ входит в пресинаптическое окончание.", "Depolarization opens voltage-gated calcium channels, allowing Ca²⁺ to enter the presynaptic terminal.", "Деполяризация потенциалға тәуелді кальций арналарын ашады да, Ca²⁺ пресинапстық ұшқа кіреді."]),
          node("transmitter", ["Слияние везикул и выделение медиатора", "Vesicle fusion and transmitter release", "Везикулалардың қосылуы және медиатор бөлінуі"], ["Повышение Ca²⁺ запускает слияние подготовленных везикул с мембраной и выделение медиатора в синаптическую щель.", "The rise in Ca²⁺ triggers fusion of primed vesicles with the membrane and transmitter release into the synaptic cleft.", "Ca²⁺ жоғарылауы дайын везикулалардың мембранамен қосылып, медиаторды синапстық саңылауға бөлуін іске қосады."]),
          node("binding", ["Связывание с рецепторами", "Receptor binding", "Рецепторлармен байланысу"], ["Медиатор диффундирует через щель и связывается с постсинаптическими рецепторами; затем его действие прекращается удалением, разрушением или обратным захватом.", "Transmitter diffuses across the cleft and binds postsynaptic receptors; its action then ends through removal, degradation, or reuptake.", "Медиатор саңылау арқылы диффузияланып, постсинапстық рецепторлармен байланысады; кейін оның әсері әкетілу, ыдырау немесе кері қармалу арқылы тоқтайды."]),
          node("response", ["Постсинаптический ответ", "Postsynaptic response", "Постсинапстық жауап"], ["Изменение работы рецепторов влияет на ионную проводимость или внутриклеточные сигналы и тем самым изменяет активность постсинаптической клетки.", "Receptor activation changes ion conductance or intracellular signaling and thereby alters postsynaptic-cell activity.", "Рецепторлардың белсенуі иондық өткізгіштікті немесе жасушаішілік сигналдарды өзгертіп, постсинапстық жасуша белсенділігіне әсер етеді."]),
        ] },
        { id: "electrical", title: t(["Электрический синапс", "Electrical synapse", "Электрлік синапс"]), note: t(["Проследите прямое прохождение ионного тока между электрически связанными клетками.", "Follow direct ionic-current flow between electrically coupled cells.", "Электрлік байланысқан жасушалар арасындағы иондық токтың тікелей өтуін бақылаңыз."]), nodes: [
          node("cell", ["Изменение потенциала первой клетки", "Potential change in the first cell", "Бірінші жасуша потенциалының өзгеруі"], ["Изменение мембранного потенциала одной клетки создаёт ток, способный пройти к соседней клетке.", "A membrane-potential change in one cell creates current that can pass to the neighboring cell.", "Бір жасушаның мембраналық потенциалының өзгеруі көрші жасушаға өте алатын ток тудырады."]),
          node("junction", ["Щелевые контакты", "Gap junctions", "Саңылаулы түйіспелер"], ["Каналы щелевых контактов образуют низкоомный путь между цитоплазмами клеток; направление и величина тока зависят от градиента потенциала.", "Gap-junction channels provide a low-resistance path between cell cytoplasms; current direction and magnitude depend on the voltage gradient.", "Саңылаулы түйіспе арналары жасуша цитоплазмалары арасында кедергісі төмен жол түзеді; ток бағыты мен шамасы потенциал градиентіне тәуелді."]),
          node("coupled", ["Ответ связанной клетки", "Response of the coupled cell", "Байланысқан жасушаның жауабы"], ["Ионный ток изменяет мембранный потенциал второй клетки без выделения химического медиатора; многие электрические контакты проводят ток в обоих направлениях.", "Ionic current changes the second cell's membrane potential without chemical-transmitter release; many electrical junctions conduct in both directions.", "Иондық ток химиялық медиатор бөлінбестен екінші жасушаның мембраналық потенциалын өзгертеді; көптеген электрлік түйіспелер токты екі бағытта өткізеді."]),
        ] },
      ],
    },
        integration: {
      id: "integration", title: t(["4. Центральная обработка сигналов", "4. Central processing of signals", "4. Сигналдарды орталық өңдеу"]), anchor: "principles",
      instruction: t(["Включайте и выключайте два источника информации и сравните результат. Цель — увидеть, что итоговый ответ зависит от сочетания входов, а не изучать клеточные механизмы интеграции.", "Turn two information sources on and off and compare the result. The goal is to see that the final response depends on the combination of inputs, not to study cellular integration mechanisms.", "Екі ақпарат көзін қосып-өшіріп, нәтижені салыстырыңыз. Мақсат — қорытынды жауаптың кірістер үйлесіміне тәуелді екенін көру; жасушалық интеграция тетіктерін зерттеу емес."]),
      excitation: t(["Источник информации A", "Information source A", "Ақпарат көзі A"]),
      inhibition: t(["Источник информации B", "Information source B", "Ақпарат көзі B"]),
      neuron: t(["ЦНС: совместная обработка", "CNS: combined processing", "ОЖЖ: бірлескен өңдеу"]),
      note: t(["Вводная качественная модель. Подробные механизмы возбуждения, торможения, суммации и порога рассматриваются в последующих модулях.", "An introductory qualitative model. Detailed mechanisms of excitation, inhibition, summation and threshold are covered in later modules.", "Кіріспе сапалық модель. Қозу, тежелу, суммация және табалдырықтың егжей-тегжейлі тетіктері кейінгі модульдерде қарастырылады."]),
      outcomes: [
        t(["Оба показанных источника выключены. В модели нет информации от этих двух источников; это не означает полного отсутствия активности нервной системы.", "Both displayed sources are off. The model contains no information from these two sources; this does not mean the nervous system is completely inactive.", "Көрсетілген екі көз де өшірулі. Модельде осы екі көзден ақпарат жоқ; бұл жүйке жүйесі мүлде белсенді емес дегенді білдірмейді."]),
        t(["Активен источник A. Его информация участвует в формировании ответа вместе с другими условиями системы.", "Source A is active. Its information contributes to the response together with other system conditions.", "A көзі белсенді. Оның ақпараты жүйенің басқа жағдайларымен бірге жауап қалыптастыруға қатысады."]),
        t(["Активен источник B. Изменение набора входной информации может изменить итоговый ответ.", "Source B is active. Changing the set of incoming information can alter the final response.", "B көзі белсенді. Кіріс ақпарат жиынтығының өзгеруі қорытынды жауапты өзгерте алады."]),
        t(["Активны оба источника. ЦНС обрабатывает их совместно; по наличию двух входов нельзя автоматически предсказать единственный неизменный ответ.", "Both sources are active. The CNS processes them together; the presence of two inputs does not automatically predict one fixed response.", "Екі көз де белсенді. ОЖЖ оларды бірге өңдейді; екі кірістің болуы бір ғана өзгермейтін жауапты автоматты түрде болжамайды."]),
      ],
    },
  };
}
