import type { Language } from "../../course";
import { getSectionTitle } from "../../sections";
import type { StudyLesson, StudyLink, StudyCard } from "../../study";
import testsRU from "./tests/ru";
import testsKZ from "./tests/kz";
import testsEN from "./tests/en";
import casesRU from "./cases/ru";

// Shared IDs and relationships; every teaching string has RU/KZ/EN copy.
type Copy = [string, string, string];
const pick = (copy: Copy, language: Language) => copy[language === "RU" ? 0 : language === "KZ" ? 1 : 2];
const theory = (anchor: string): StudyLink => ({ section: "theory", anchor });
const goals: { id: string; text: Copy; links: StudyLink[] }[] = [
  { id: "organization", text: ["Различить ЦНС и ПНС: отнести головной и спинной мозг к ЦНС, нервы и ганглии — к ПНС.", "ОЖЖ мен ШЖЖ-ні ажырату: ми мен жұлынды ОЖЖ-ге, жүйкелер мен ганглийлерді ШЖЖ-ге жатқызу.", "Distinguish CNS from PNS: classify the brain and spinal cord as CNS, and nerves and ganglia as PNS."], links: [theory("cns-pns"), { section: "practice" }] },
  { id: "pathways", text: ["Выбрать одно звено функциональной цепи нервной регуляции и предсказать, как его частичное нарушение изменит сенсорный вход, центральную интеграцию и конечный ответ; объяснить причинную связь.", "Жүйкелік реттелудің функциялық тізбегіндегі бір буынды таңдап, оның ішінара бұзылуы сезімтал кірісті, орталық интеграцияны және соңғы жауапты қалай өзгертетінін болжау; себептік байланысты түсіндіру.", "Select one link in the functional chain of neural regulation and predict how its partial impairment would alter sensory input, central integration, and the final response; explain the causal relationship."], links: [theory("cns-pns"), { section: "practice" }, { section: "cases" }] },
  { id: "principles", text: ["На вводном уровне различить проведение сигнала по нервному волокну и передачу между клетками; подробные мембранные и синаптические механизмы изучаются в следующих модулях.", "Кіріспе деңгейде жүйке талшығы бойымен сигнал өткізуді жасушалар арасындағы берілуден ажырату; мембраналық және синапстық тетіктер кейінгі модульдерде егжей-тегжейлі оқытылады.", "At an introductory level, distinguish signal conduction along a nerve fibre from transmission between cells; detailed membrane and synaptic mechanisms are developed in later modules."], links: [theory("principles"), { section: "questions" }, { section: "tests" }] },
  { id: "integration", text: ["На примере защитной реакции выделить сенсорный вход, интеграцию и двигательный ответ; объяснить, почему рефлекс не требует предварительного осознания боли.", "Қорғаныш реакциясынан сенсорлық кірісті, интеграцияны және қимыл жауабын бөліп көрсету; рефлекс үшін ауырсынуды алдын ала саналы сезіну неге қажет емес екенін түсіндіру.", "Identify sensory input, integration and motor output in a protective response, and explain why a reflex need not await conscious pain perception."], links: [theory("functions"), { section: "clinical" }, { section: "cases" }] },
  { id: "feedback", text: ["На одном примере объяснить, как обратная связь корректирует ответ и поддерживает гомеостаз; отличить коррекцию результата от простой передачи команды.", "Бір мысал арқылы кері байланыстың жауапты түзетіп, гомеостазды қалай қолдайтынын түсіндіру; нәтижені түзетуді жай бұйрық беруден ажырату.", "Use one example to explain how feedback adjusts a response and supports homeostasis; distinguish result correction from simply issuing a command."], links: [theory("functions"), theory("cns-pns"), { section: "tests" }] },
];
const summary: { title: Copy; text: Copy; anchor: string }[] = [
  { title: ["Система", "Жүйе", "System"], text: ["Нервная система получает информацию, объединяет сигналы и организует ответ. Нейроны передают и обрабатывают сигналы; глия поддерживает условия их работы.", "Жүйке жүйесі ақпаратты қабылдап, сигналдарды біріктіреді және жауапты ұйымдастырады. Нейрондар сигналдарды өткізеді және өңдейді; глия олардың жұмыс жағдайын қолдайды.", "The nervous system receives information, integrates signals and organises responses. Neurons transmit and process signals; glia support their working environment."], anchor: "nervous-system" },
  { title: ["Организация", "Ұйымдасу", "Organisation"], text: ["ЦНС — головной и спинной мозг. ПНС связывает их с органами. Афферентные пути идут к ЦНС, эфферентные — к мышцам и железам.", "ОЖЖ — ми мен жұлын. ШЖЖ оларды ағзалармен байланыстырады. Афференттік жолдар ОЖЖ-ге, эфференттік жолдар бұлшықеттер мен бездерге бағытталады.", "The CNS comprises brain and spinal cord. The PNS connects them with the body. Afferent pathways lead towards the CNS; efferent pathways lead to muscles and glands."], anchor: "cns-pns" },
  { title: ["Сигналы", "Сигналдар", "Signals"], text: ["На вводном уровне различайте два этапа: сигнал распространяется по нервному волокну, затем влияние передаётся следующей клетке. Подробные механизмы возбуждения, торможения и синаптической передачи рассматриваются в следующих модулях.", "Кіріспе деңгейде екі кезеңді ажыратыңыз: сигнал жүйке талшығы бойымен таралады, содан кейін әсер келесі жасушаға беріледі. Қозу, тежелу және синапстық берілістің егжей-тегжейлі тетіктері кейінгі модульдерде қарастырылады.", "At an introductory level, distinguish two stages: a signal propagates along a nerve fibre and then influence is transmitted to the next cell. Detailed mechanisms of excitation, inhibition and synaptic transmission are developed in later modules."], anchor: "principles" },
  { title: ["Регуляция", "Реттелу", "Regulation"], text: ["Рефлекторный ответ может начаться до осознания раздражителя. Обратная связь сообщает о результате и помогает его корректировать. Гомеостаз — относительная стабильность, а не полная неизменность.", "Рефлекстік жауап тітіркендіргішті саналы сезінуден бұрын басталуы мүмкін. Кері байланыс нәтиже туралы хабарлап, оны түзетуге көмектеседі. Гомеостаз — толық өзгермеу емес, салыстырмалы тұрақтылық.", "A reflex may begin before conscious awareness of a stimulus. Feedback reports the outcome and helps adjust it. Homeostasis means relative stability, not complete absence of change."], anchor: "functions" },
];
const clinical: { id: string; title: Copy; mechanism: Copy; manifestation: Copy; why: Copy; anchor: string }[] = [
  { id: "withdrawal", title: ["Отдёргивание руки", "Қолды тартып алу", "Withdrawing the hand"], mechanism: ["Сенсорный вход активирует спинальные сети, которые изменяют активность мотонейронов.", "Сенсорлық кіріс мотонейрон белсенділігін өзгертетін жұлын желілерін белсендіреді.", "Sensory input activates spinal networks that alter motor neuron activity."], manifestation: ["При болезненном раздражении рука может отдёрнуться до осознанной оценки ситуации.", "Ауырсындыратын әсер кезінде қол жағдайды саналы бағалаудан бұрын тартылуы мүмкін.", "A painful stimulus may trigger hand withdrawal before conscious appraisal."], why: ["Для запуска защитной двигательной реакции достаточно спинальной обработки; восходящие сигналы обеспечивают последующее осознанное восприятие. Это разные, взаимодействующие процессы.", "Қорғаныш қимылын бастауға жұлындық өңдеу жеткілікті; жоғары өрлейтін сигналдар кейінгі саналы қабылдауды қамтамасыз етеді. Бұлар өзара байланысқан бөлек үдерістер.", "Spinal processing can initiate the protective motor response; ascending signals support subsequent conscious perception. These are distinct, interacting processes."], anchor: "functions" },
  { id: "sensory", title: ["Ослабление сенсорного входа", "Сенсорлық кірістің әлсіреуі", "Reduced sensory input"], mechanism: ["Для рефлекторной реакции информация от рецептора должна достигнуть центральной сети по афферентному пути.", "Рефлекстік реакция үшін рецептор ақпараты афференттік жолмен орталық желіге жетуі керек.", "A reflex requires receptor information to reach the central network through an afferent pathway."], manifestation: ["В учебной модели прерывание этого пути ослабляет или устраняет ответ на раздражение, даже если мышца способна сокращаться.", "Оқу моделінде бұл жолдың үзілуі бұлшықет жиырыла алса да, тітіркенуге жауапты әлсіретеді немесе жояды.", "In a teaching model, interrupting this pathway reduces or abolishes the response even when the muscle can still contract."], why: ["Сохранный эффектор не компенсирует отсутствие запускающего сигнала. Наблюдаемое снижение ответа само по себе не определяет причину или место нарушения.", "Сақталған эффектор іске қосатын сигналдың жоқтығын өтемейді. Жауаптың төмендеуі өздігінен бұзылыстың себебін не орнын анықтамайды.", "An intact effector cannot replace a missing initiating signal. A reduced response alone does not identify the cause or location of a disturbance."], anchor: "cns-pns" },
  { id: "synaptic", title: ["Нарушение передачи между клетками", "Жасушалар арасындағы берілістің бұзылуы", "Impaired transmission between cells"], mechanism: ["Сигнал может пройти по нервному волокну, но следующий этап — передача влияния другой клетке — может быть нарушен отдельно.", "Сигнал жүйке талшығы бойымен өтуі мүмкін, бірақ келесі кезең — әсерді басқа жасушаға беру — бөлек бұзылуы мүмкін.", "A signal may travel along a nerve fibre while the next stage—transmission of influence to another cell—is impaired separately."], manifestation: ["В учебной модели ответ следующей клетки снижен, несмотря на сохранённое проведение по входящему волокну.", "Оқу моделінде кіріс талшығы бойымен өткізу сақталғанымен, келесі жасушаның жауабы төмендейді.", "In the teaching model, the next cell's response is reduced despite preserved conduction along the incoming fibre."], why: ["Это помогает различить два функциональных этапа. Молекулярные причины нарушения межклеточной передачи рассматриваются в следующих модулях.", "Бұл екі функциялық кезеңді ажыратуға көмектеседі. Жасушааралық беріліс бұзылысының молекулалық себептері кейінгі модульдерде қарастырылады.", "This distinguishes two functional stages. Molecular causes of impaired intercellular transmission are covered in later modules."], anchor: "principles" },
];

const terms: { id: string; term: Copy; definition: Copy; anchor: string }[] = [
  { id: "neuron", term: ["Нейрон", "Нейрон", "Neuron"], definition: ["Возбудимая клетка, принимающая, обрабатывающая и передающая сигналы.", "Сигналдарды қабылдайтын, өңдейтін және өткізетін қозғыш жасуша.", "An excitable cell that receives, processes and transmits signals."], anchor: "nervous-system" },
  { id: "glia", term: ["Нейроглия", "Нейроглия", "Neuroglia"], definition: ["Клетки, поддерживающие среду и работу нейронов; некоторые образуют миелин.", "Нейрондардың ортасы мен қызметін қолдайтын жасушалар; кейбірі миелин түзеді.", "Cells supporting neurons and their environment; some form myelin."], anchor: "nervous-system" },
  { id: "cns", term: ["Центральная нервная система (ЦНС)", "Орталық жүйке жүйесі (ОЖЖ)", "Central nervous system (CNS)"], definition: ["Головной и спинной мозг; обеспечивают обработку сигналов и организацию ответов.", "Ми мен жұлын; сигналдарды өңдеп, жауаптарды ұйымдастырады.", "The brain and spinal cord, which process signals and organise responses."], anchor: "cns-pns" },
  { id: "pns", term: ["Периферическая нервная система (ПНС)", "Шеткі жүйке жүйесі (ШЖЖ)", "Peripheral nervous system (PNS)"], definition: ["Нервные структуры вне головного и спинного мозга, связывающие ЦНС с органами и тканями.", "Ми мен жұлыннан тыс орналасқан, ОЖЖ-ні ағзалармен және тіндермен байланыстыратын жүйкелік құрылымдар.", "Neural structures outside the brain and spinal cord that connect the CNS with organs and tissues."], anchor: "cns-pns" },
  { id: "receptor", term: ["Сенсорный рецептор", "Сенсорлық рецептор", "Sensory receptor"], definition: ["Структура, преобразующая действие раздражителя в сигнал для нервной системы.", "Тітіркендіргіш әсерін жүйке жүйесіне арналған сигналға түрлендіретін құрылым.", "A structure that converts a stimulus into a signal for the nervous system."], anchor: "cns-pns" },
  { id: "afferent", term: ["Афферентный путь", "Афференттік жол", "Afferent pathway"], definition: ["Путь передачи сенсорной информации от периферии к ЦНС.", "Сенсорлық ақпаратты шеттен ОЖЖ-ге жеткізетін жол.", "A pathway carrying sensory information from the periphery towards the CNS."], anchor: "cns-pns" },
  { id: "efferent", term: ["Эфферентный путь", "Эфференттік жол", "Efferent pathway"], definition: ["Путь передачи команд от ЦНС к исполнительным органам.", "ОЖЖ-ден атқарушы ағзаларға бұйрық жеткізетін жол.", "A pathway carrying commands from the CNS towards effectors."], anchor: "cns-pns" },
  { id: "effector", term: ["Эффектор", "Эффектор", "Effector"], definition: ["Исполнительная структура, например мышца или железа, реализующая ответ.", "Жауапты іске асыратын атқарушы құрылым, мысалы бұлшықет немесе без.", "A responding structure, such as a muscle or gland, that carries out an output."], anchor: "cns-pns" },
  { id: "excitation", term: ["Возбуждение", "Қозу", "Excitation"], definition: ["Термин для активирующего влияния в нервной системе; его клеточные механизмы подробно изучаются в следующих модулях.", "Жүйке жүйесіндегі белсендіруші ықпалды білдіретін термин; оның жасушалық тетіктері кейінгі модульдерде егжей-тегжейлі оқытылады.", "A term for an activating influence in the nervous system; its cellular mechanisms are developed in later modules."], anchor: "principles" },
  { id: "inhibition", term: ["Торможение", "Тежелу", "Inhibition"], definition: ["Термин для ограничивающего или регулирующего влияния в нервной системе; клеточные механизмы рассматриваются позже.", "Жүйке жүйесіндегі шектеуші немесе реттеуші ықпалды білдіретін термин; жасушалық тетіктер кейін қарастырылады.", "A term for a limiting or regulatory influence in the nervous system; cellular mechanisms are covered later."], anchor: "principles" },
  { id: "synapse", term: ["Синапс", "Синапс", "Synapse"], definition: ["Специализированный контакт для передачи сигнала от нейрона другой клетке.", "Нейроннан басқа жасушаға сигнал беретін маманданған түйісу.", "A specialised contact transmitting a signal from a neuron to another cell."], anchor: "principles" },
  { id: "integration", term: ["Интеграция", "Интеграция", "Integration"], definition: ["Объединение и обработка входящих сигналов для формирования согласованного ответа.", "Үйлесімді жауап қалыптастыру үшін кіріс сигналдарын біріктіру және өңдеу.", "Combining and processing incoming signals to produce a coordinated response."], anchor: "principles" },
  { id: "feedback", term: ["Обратная связь", "Кері байланыс", "Feedback"], definition: ["Информация о результате действия, используемая для последующей коррекции.", "Кейінгі түзету үшін қолданылатын әрекет нәтижесі туралы ақпарат.", "Information about an action's outcome used for subsequent adjustment."], anchor: "cns-pns" },
  { id: "homeostasis", term: ["Гомеостаз", "Гомеостаз", "Homeostasis"], definition: ["Поддержание относительной стабильности внутренней среды за счёт механизмов регуляции.", "Реттелу механизмдері арқылы ішкі ортаның салыстырмалы тұрақтылығын сақтау.", "Maintenance of relative stability of the internal environment through regulatory mechanisms."], anchor: "functions" },
];

const review: { prompt: Copy; explanation: Copy; anchor: string }[] = [
  { prompt: ["Почему нервная система — не просто система проводов?", "Неліктен жүйке жүйесі жай өткізгіштер жүйесі емес?", "Why is the nervous system more than a wiring system?"], explanation: ["Она не только проводит, но и обрабатывает сигналы, объединяет входы и выбирает ответ с учётом состояния организма.", "Ол сигналдарды өткізіп қана қоймай, өңдейді, кірістерді біріктіреді және организм күйін ескеріп жауапты таңдайды.", "It conducts and processes signals, combines inputs and selects responses according to the body's state."], anchor: "nervous-system" },
  { prompt: ["Чем различаются ЦНС и ПНС? Приведите по два примера структур.", "ОЖЖ мен ШЖЖ қалай ажыратылады? Әрқайсысына екі құрылымнан мысал келтіріңіз.", "How do CNS and PNS differ? Give two examples of structures in each."], explanation: ["ЦНС включает головной и спинной мозг. К ПНС относятся, например, нервы и ганглии вне ЦНС. Это анатомическое деление, а не разделение на важную и второстепенную системы.", "ОЖЖ-ге ми мен жұлын кіреді. ШЖЖ-ге, мысалы, ОЖЖ-ден тыс жүйкелер мен ганглийлер жатады. Бұл маңызды және қосалқы жүйелерге емес, анатомиялық бөліну.", "The CNS includes brain and spinal cord. Examples in the PNS are nerves and ganglia outside the CNS. This is an anatomical distinction, not a division into important and secondary systems."], anchor: "cns-pns" },
  { prompt: ["Опишите путь от раздражения кожи до сокращения мышцы.", "Терінің тітіркенуінен бұлшықет жиырылуына дейінгі жолды сипаттаңыз.", "Describe the pathway from skin stimulation to muscle contraction."], explanation: ["Рецептор преобразует раздражение; афферентный путь передаёт информацию в ЦНС; центральная сеть интегрирует вход; эфферентный путь воздействует на мышцу-эффектор. Обратная связь позволяет корректировать результат.", "Рецептор тітіркенуді түрлендіреді; афференттік жол ақпаратты ОЖЖ-ге өткізеді; орталық желі кірісті біріктіреді; эфференттік жол бұлшықет-эффекторға әсер етеді. Кері байланыс нәтижені түзетуге мүмкіндік береді.", "A receptor transduces the stimulus; an afferent pathway carries information to the CNS; a central network integrates input; an efferent pathway acts on the muscle effector. Feedback supports correction of the outcome."], anchor: "cns-pns" },
  { prompt: ["Почему организованный ответ нервной системы нельзя свести к максимальной активности всех её частей?", "Неліктен жүйке жүйесінің ұйымдасқан жауабын оның барлық бөлігінің ең жоғары белсенділігіне теңеуге болмайды?", "Why can an organized nervous-system response not be reduced to maximal activity of all its parts?"], explanation: ["Для согласованного ответа нервная система должна избирательно организовать нужные действия и ограничить конкурирующие. Клеточные механизмы возбуждения и торможения рассматриваются в следующих модулях.", "Үйлесімді жауап үшін жүйке жүйесі қажетті әрекеттерді таңдап ұйымдастырып, бәсекелес әрекеттерді шектеуі керек. Қозу мен тежелудің жасушалық тетіктері кейінгі модульдерде қарастырылады.", "A coordinated response requires selective organization of appropriate actions and limitation of competing actions. Cellular excitation and inhibition are developed in later modules."], anchor: "principles" },
  { prompt: ["Как на вводном уровне отличить проведение по нервному волокну от передачи между клетками?", "Кіріспе деңгейде жүйке талшығы бойымен өткізуді жасушалар арасындағы берілістен қалай ажыратуға болады?", "At an introductory level, how do conduction along a nerve fibre and transmission between cells differ?"], explanation: ["Проведение описывает распространение сигнала вдоль нервного волокна, а межклеточная передача — переход влияния к следующей клетке. Здесь важно различить этапы; ионные и молекулярные механизмы подробно изучаются в следующих модулях.", "Өткізу сигналдың жүйке талшығы бойымен таралуын, ал жасушааралық берілу әсердің келесі жасушаға өтуін сипаттайды. Бұл жерде кезеңдерді ажырату маңызды; иондық және молекулалық тетіктер кейінгі модульдерде егжей-тегжейлі оқытылады.", "Conduction describes signal propagation along a nerve fibre, whereas intercellular transmission passes influence to the next cell. The goal here is to distinguish the stages; ionic and molecular mechanisms are developed in later modules."], anchor: "principles" },
  { prompt: ["Что добавляет обратная связь к передаче команды?", "Кері байланыс бұйрық беруге не қосады?", "What does feedback add to issuing a command?"], explanation: ["Она сообщает, что реально произошло, и позволяет изменить последующую команду. Поэтому регуляция может поддерживать показатели в определённых пределах, а не требовать их полной неизменности.", "Ол нақты не болғанын хабарлап, келесі бұйрықты өзгертуге мүмкіндік береді. Сондықтан реттелу көрсеткіштердің толық өзгермеуін емес, белгілі шектерде сақталуын қамтамасыз етеді.", "It reports what actually happened and allows subsequent commands to change. Regulation can therefore keep variables within a range rather than requiring complete constancy."], anchor: "functions" },
  { prompt: ["Перенесите принцип сенсорного входа, интеграции и эфферентного выхода в новую ситуацию: что изменится, если ослабнет только афферентное звено?", "Сенсорлық кіріс, интеграция және эфференттік шығыс қағидасын жаңа жағдайға қолданыңыз: тек афференттік буын әлсіресе не өзгереді?", "Transfer the sensory input, integration and efferent output principle to a new situation: what changes if only the afferent link is weakened?"], explanation: ["Центральная сеть получает меньше или менее надёжную информацию о стимуле, поэтому запуск или настройка ответа нарушается даже при сохранном эфферентном пути и эффекторе. По одному снижению ответа нельзя определить точное место нарушения.", "Орталық желі стимул туралы аз немесе сенімсіз ақпарат алады, сондықтан эфференттік жол мен эффектор сақталса да жауаптың іске қосылуы немесе реттелуі бұзылады. Жауаптың төмендеуіне қарап бұзылыстың нақты орнын анықтауға болмайды.", "The central network receives less or less reliable information about the stimulus, so response initiation or adjustment is impaired even with an intact efferent pathway and effector. A reduced response alone does not localize the disturbance."], anchor: "cns-pns" },
  { prompt: ["Как на функциональной схеме отличить нарушение проведения по нервному волокну от нарушения передачи влияния следующей клетке?", "Функциялық сызбада жүйке талшығы бойымен өткізудің бұзылуын әсердің келесі жасушаға берілу бұзылуынан қалай ажыратуға болады?", "On a functional map, how would you distinguish impaired conduction along a nerve fibre from impaired transmission of influence to the next cell?"], explanation: ["Проверьте два этапа отдельно: дошёл ли сигнал по волокну и возник ли ответ на следующем функциональном звене. Подробные пре- и постсинаптические механизмы изучаются позже.", "Екі кезеңді бөлек тексеріңіз: сигнал талшық бойымен жетті ме және келесі функциялық буында жауап пайда болды ма. Пре- және постсинапстық тетіктер кейін егжей-тегжейлі оқытылады.", "Test the two stages separately: whether the signal travelled along the fibre and whether a response appeared at the next functional link. Detailed pre- and postsynaptic mechanisms are studied later."], anchor: "principles" },
];

export function createStudyLessons(language: Language): Record<"objectives" | "pretest" | "one-minute" | "clinical" | "questions" | "glossary" | "references", StudyLesson> {
  const t = (copy: Copy) => pick(copy, language);
  const title = (section: Parameters<typeof getSectionTitle>[0]) => getSectionTitle(section, language);
  const tests = { RU: testsRU, KZ: testsKZ, EN: testsEN }[language];
  const sourceLinks: StudyLink[][] = [[theory("principles"), { section: "clinical", anchor: "synaptic" }, { section: "cases" }, { section: "questions" }], [theory("functions"), { section: "clinical", anchor: "withdrawal" }, { section: "cases" }]];
  return {
    objectives: { kind: "objectives", title: title("objectives"), introduction: t(["После изучения модуля проверьте, можете ли вы выполнить каждое действие самостоятельно. Ссылки ведут к материалам и проверочным активностям.", "Модульден кейін әр әрекетті өз бетіңізше орындай алатыныңызды тексеріңіз. Сілтемелер материалдар мен тексеру тапсырмаларына апарады.", "After studying the module, check whether you can perform each action independently. Links lead to the relevant material and assessment activities."]), cards: goals.map((goal, index) => ({ id: goal.id, title: `${index + 1}`, paragraphs: [t(goal.text)], links: goal.links })) },
    pretest: { kind: "pretest", title: title("pretest"), introduction: t(["Пять вопросов для определения исходных знаний. Это диагностика без итоговой оценки. Выберите ответ, прочитайте объяснение и используйте рекомендации для повторения. Попытка сбрасывается при перезагрузке или смене языка.", "Бастапқы білімді анықтайтын бес сұрақ. Бұл қорытынды бағаға кірмейтін диагностика. Жауапты таңдап, түсіндірмені оқыңыз және қайталау ұсыныстарын қолданыңыз. Бет жаңартылғанда немесе тіл ауысқанда әрекет қайта басталады.", "Five questions to check prior knowledge. This diagnostic does not contribute to a final grade. Choose an answer, read the explanation and use the review recommendations. Reloading or changing language resets the attempt."]), questions: ["organization", "cns-pns", "afferent", "synapse", "regulation"].map(id => { const node = tests.nodes[`${id}:main`]; if (node.type !== "question") throw Error("Expected diagnostic question"); return { ...node, topic: tests.competencies[id].title, target: theory(tests.competencies[id].theoryTarget.anchor) }; }) },
    "one-minute": { kind: "one-minute", title: title("one-minute"), introduction: t(["Не перечитывайте готовое резюме. За одну минуту восстановите тему по памяти: вход → центральная обработка → выход → обратная связь, затем откройте теорию и проверьте пропущенное звено.", "Дайын қорытындыны қайта оқымаңыз. Бір минут ішінде тақырыпты есте сақтаудан қалпына келтіріңіз: кіріс → орталық өңдеу → шығыс → кері байланыс; содан кейін теорияны ашып, өткізіп алған буынды тексеріңіз.", "Do not reread a prepared summary. In one minute, reconstruct the topic from memory: input → central processing → output → feedback; then open the theory and check the link you missed."]), cards: summary.map((item, index) => ({ id: `key-${index + 1}`, title: t(item.title), paragraphs: [t(["Сначала запишите или проговорите эту идею своими словами. Затем откройте связанный фрагмент теории и сравните направление связи, а не формулировку.", "Алдымен осы ойды өз сөзіңізбен жазыңыз немесе айтыңыз. Содан кейін байланысты теория бөлігін ашып, сөйлемді емес, байланыстың бағытын салыстырыңыз.", "First write or say this idea in your own words. Then open the linked theory passage and compare the direction of the relationship, not the wording."])], links: [theory(item.anchor)] })) },
    clinical: { kind: "clinical", title: title("clinical"), introduction: t(["Учебные примеры связывают физиологию с наблюдаемыми проявлениями. Они объясняют механизмы, а не устанавливают диагноз и не предлагают лечение.", "Оқу мысалдары физиологияны байқалатын көріністермен байланыстырады. Олар механизмдерді түсіндіреді, диагноз қоймайды және ем ұсынбайды.", "These teaching examples connect physiology with observable manifestations. They explain mechanisms rather than establish a diagnosis or recommend treatment."]), cards: clinical.map(item => ({ id: item.id, title: t(item.title), paragraphs: [t(["Механизм: ", "Механизм: ", "Mechanism: "]) + t(item.mechanism), t(["Проявление: ", "Көрініс: ", "Manifestation: "]) + t(item.manifestation), t(["Почему: ", "Неліктен: ", "Why: "]) + t(item.why)], links: [theory(item.anchor), { section: "references", anchor: item.id === "synaptic" ? "source-1" : "source-2" }] })) },
    questions: { kind: "questions", title: title("questions"), introduction: t(["Сначала сформулируйте ответ своими словами, затем сравните его с объяснением. Свободный ответ не оценивается автоматически и не сохраняется после ухода со страницы.", "Алдымен өз сөзіңізбен жауап беріп, кейін түсіндірмемен салыстырыңыз. Еркін жауап автоматты бағаланбайды және беттен шыққаннан кейін сақталмайды.", "Formulate an answer in your own words before comparing it with the explanation. Free-text answers are not automatically graded and are not saved after leaving the page."]), questions: review.map((item, index) => ({ id: `review-${index + 1}`, prompt: t(item.prompt), explanation: t(item.explanation), target: theory(item.anchor) })) },
    glossary: { kind: "glossary", title: title("glossary"), introduction: t(["Ищите по термину или определению. Ссылки открывают связанный фрагмент теории на выбранном языке.", "Термин немесе анықтама бойынша іздеңіз. Сілтемелер таңдалған тілдегі тиісті теория бөлігін ашады.", "Search terms or definitions. Links open the related theory passage in the selected language."]), terms: terms.map(item => ({ id: item.id, term: t(item.term), definition: t(item.definition), target: theory(item.anchor) })) },
    references: { kind: "references", title: title("references"), introduction: t(["Источники, уже используемые в ситуационных задачах Модуля 1. Названия и адреса сохранены; отсутствующие в проекте авторы, даты и издания не добавлены. Это тематические источники по синапсам и защитному рефлексу, а не исчерпывающая библиография модуля.", "Модуль 1 ситуациялық тапсырмаларында қолданылған дереккөздер. Атаулар мен мекенжайлар сақталған; жобада жоқ авторлар, күндер және басылымдар қосылмаған. Бұлар синапстар мен қорғаныш рефлексіне қатысты дереккөздер, модульдің толық библиографиясы емес.", "Sources already used in Module 1 case problems. Titles and URLs are preserved; authors, dates and editions absent from the project have not been added. These are topic-specific sources on synapses and the protective reflex, not an exhaustive module bibliography."]), cards: [{ id: "module-materials", title: t(["Материалы учебника", "Оқулық материалдары", "Textbook materials"]), paragraphs: [t(["Для общей организации нервной системы, путей и гомеостаза используйте теорию модуля. Практика и вопросы помогают проверить понимание.", "Жүйке жүйесінің жалпы ұйымдасуы, жолдары және гомеостаз үшін модуль теориясын қолданыңыз. Практика мен сұрақтар түсінуді тексеруге көмектеседі.", "Use the module theory for nervous system organisation, pathways and homeostasis. Practice and questions help assess understanding."])], links: [theory("nervous-system"), theory("cns-pns"), theory("functions"), { section: "practice" }, { section: "questions" }] }], sources: (casesRU.sources ?? []).map((source, index) => ({ ...source, description: index === 0 ? t(["Химическая синаптическая передача: связь с механизмами межклеточного сигнала.", "Химиялық синапстық берілу: жасушааралық сигнал механизмдерімен байланыс.", "Chemical synaptic transmission and the mechanisms of intercellular signalling."]) : t(["Реакция отдёргивания: связь сенсорного входа, спинальных сетей и защитного движения.", "Тартып алу реакциясы: сенсорлық кіріс, жұлын желілері және қорғаныш қимылының байланысы.", "Withdrawal response: links between sensory input, spinal networks and protective movement."]), links: sourceLinks[index] ?? [] })) },
  };
}
