"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {readCourseProgress,type CourseProgressData} from "../../lib/courseProgress";
import {modules,type Language} from "../../content/course";
type User={username:string;role:"student"|"teacher";displayName:string};
type Attempt={id:number;date:string;language:string;size:number;module:number;percent:number;level:string;blocks:{id:number;title:string;percent:number}[]};
const C={
RU:{checking:"Проверка доступа…",student:"Личный кабинет студента",teacher:"Кабинет преподавателя",studentRole:"студент",teacherRole:"преподаватель",progress:"Мой прогресс",visited:"Посещено модулей",local:"Текущие данные обучения сохраняются в этом браузере; для общей ведомости группы требуется серверная синхронизация.",attempts:"Экзаменационных попыток",average:"средний результат",trend:"динамика",review:"Повторить в первую очередь",progressLink:"Прогресс и оценивание →",exam:"Экзаменационный центр →",analytics:"Экзаменационная аналитика",weak:"Слабые блоки",teacherInfo:"Доступ защищён ролью преподавателя. Сейчас показана аналитика попыток из этого браузера; групповая ведомость появится после подключения серверного хранилища.",cards:["Группы и студенты","Прогресс 25 модулей","Экзаменационные попытки","Слабые темы и механизмы"],waiting:"Ожидает серверных данных группы.",book:"К учебнику",logout:"Выйти"},
EN:{checking:"Checking access…",student:"Student dashboard",teacher:"Teacher dashboard",studentRole:"student",teacherRole:"teacher",progress:"My progress",visited:"Modules visited",local:"Current learning data is stored in this browser; a shared group record requires server synchronization.",attempts:"Exam attempts",average:"average result",trend:"trend",review:"Review first",progressLink:"Progress and assessment →",exam:"Exam Center →",analytics:"Exam analytics",weak:"Weak blocks",teacherInfo:"Access is protected by the teacher role. Analytics currently reflects attempts in this browser; group records require server storage.",cards:["Groups and students","Progress across 25 modules","Exam attempts","Weak topics and mechanisms"],waiting:"Waiting for group server data.",book:"Back to textbook",logout:"Log out"},
KZ:{checking:"Қолжетімділік тексерілуде…",student:"Студент кабинеті",teacher:"Оқытушы кабинеті",studentRole:"студент",teacherRole:"оқытушы",progress:"Менің прогресім",visited:"Қаралған модульдер",local:"Ағымдағы оқу деректері осы браузерде сақталады; топтың ортақ ведомосы үшін серверлік синхрондау қажет.",attempts:"Емтихан әрекеттері",average:"орташа нәтиже",trend:"динамика",review:"Алдымен қайталау",progressLink:"Прогресс және бағалау →",exam:"Емтихан орталығы →",analytics:"Емтихан аналитикасы",weak:"Әлсіз блоктар",teacherInfo:"Қолжетімділік оқытушы рөлімен қорғалған. Қазір осы браузердегі әрекеттер талданады; топтық ведомость серверлік сақтау қосылғаннан кейін қолжетімді болады.",cards:["Топтар және студенттер","25 модуль бойынша прогресс","Емтихан әрекеттері","Әлсіз тақырыптар мен механизмдер"],waiting:"Топтың серверлік деректері күтілуде.",book:"Оқулыққа оралу",logout:"Шығу"}} as const;
export default function Dashboard(){const sp=useSearchParams();const raw=sp.get("lang");const lang:Language=raw==="EN"||raw==="KZ"?raw:"RU";const c=C[lang];const[u,setU]=useState<User|null>(null),[loading,setLoading]=useState(true),[p,setP]=useState<CourseProgressData|null>(null),[attempts,setAttempts]=useState<Attempt[]>([]);
const weak=useMemo(()=>{const m=new Map<number,{title:string,sum:number,n:number}>();attempts.forEach(a=>a.blocks?.forEach(b=>{const x=m.get(b.id)??{title:b.title,sum:0,n:0};x.sum+=b.percent;x.n++;m.set(b.id,x)}));return [...m.entries()].map(([id,x])=>({id,title:x.title,percent:Math.round(x.sum/x.n)})).sort((a,b)=>a.percent-b.percent).slice(0,5)},[attempts]);
const avg=attempts.length?Math.round(attempts.reduce((s,a)=>s+a.percent,0)/attempts.length):0;const recent=[...attempts].sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)).slice(0,8);const trend=recent.length>=2?recent[0].percent-recent[recent.length-1].percent:0;
useEffect(()=>{setP(readCourseProgress());try{const a=JSON.parse(localStorage.getItem("neuro-course:exam-history:v1")||"[]");setAttempts(Array.isArray(a)?a:[])}catch{}fetch("/api/auth/me").then(async r=>{if(!r.ok){location.href=`/login?next=/dashboard?lang=${lang}`;return}setU((await r.json()).user);setLoading(false)}).catch(()=>location.href=`/login?next=/dashboard?lang=${lang}`)},[lang]);
if(loading||!u)return <main style={{padding:32}}>{c.checking}</main>;const logout=async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href=`/?lang=${lang}`};
return <main style={{maxWidth:1100,margin:"0 auto",padding:32}} lang={lang==="KZ"?"kk":lang.toLowerCase()}><nav style={{display:"flex",gap:10,justifyContent:"flex-end"}}>{(["RU","KZ","EN"] as Language[]).map(x=><Link key={x} href={`/dashboard?lang=${x}`} aria-current={x===lang?"page":undefined}>{x}</Link>)}</nav><h1>{u.role==="teacher"?c.teacher:c.student}</h1><p><strong>{u.displayName}</strong> · {u.role==="teacher"?c.teacherRole:c.studentRole}</p>
{u.role==="student"?<><h2>{c.progress}</h2><p>{c.visited}: <strong>{p?.visitedModules.length??0} / {modules[lang].length}</strong></p><p>{c.local}</p><p>{c.attempts}: <strong>{attempts.length}</strong>{attempts.length?<> · {c.average} <strong>{avg}%</strong>{recent.length>=2?<> · {c.trend} <strong>{trend>0?"+":""}{trend} p.p.</strong></>:null}</>:null}</p>{weak.length>0&&<p><strong>{c.review}:</strong> {weak.map(x=>`${x.id}. ${x.title} — ${x.percent}%`).join(" · ")}</p>}<Link href={`/modules/1/progress?lang=${lang}`}>{c.progressLink}</Link><br/><Link href={`/exam?lang=${lang}`}>{c.exam}</Link></>:<><h2>{c.teacher}</h2><p>{c.teacherInfo}</p>{attempts.length>0&&<section style={{padding:16,border:"1px solid #dce8ef",borderRadius:12,background:"#f8fcff",marginBottom:16}}><h3>{c.analytics}</h3><p>{c.attempts}: <strong>{attempts.length}</strong> · {c.average}: <strong>{avg}%</strong>{recent.length>=2?<> · {c.trend}: <strong>{trend>0?"+":""}{trend} p.p.</strong></>:null}</p>{weak.length>0&&<><strong>{c.weak}:</strong><ol>{weak.map(x=><li key={x.id}>{x.id}. {x.title} — {x.percent}%</li>)}</ol></>}</section>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}}>{c.cards.map(x=><div key={x} style={{padding:16,border:"1px solid #dce8ef",borderRadius:12,background:"#fff"}}><strong>{x}</strong><p style={{fontSize:14}}>{c.waiting}</p></div>)}</div></>}
<p style={{marginTop:28}}><Link href={`/?lang=${lang}`}>{c.book}</Link></p><button onClick={logout}>{c.logout}</button></main>}