"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {readCourseProgress,type CourseProgressData} from "../../lib/courseProgress";import {modules} from "../../content/course";
type User={username:string;role:"student"|"teacher";displayName:string};
export default function Dashboard(){const[u,setU]=useState<User|null>(null),[loading,setLoading]=useState(true),[p,setP]=useState<CourseProgressData|null>(null);
useEffect(()=>{setP(readCourseProgress());fetch("/api/auth/me").then(async r=>{if(!r.ok){location.href="/login?next=/dashboard";return}setU((await r.json()).user);setLoading(false)}).catch(()=>location.href="/login?next=/dashboard")},[]);
if(loading||!u)return <main style={{padding:32}}>Проверка доступа…</main>;
const logout=async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/"};
return <main style={{maxWidth:1100,margin:"0 auto",padding:32}}><h1>{u.role==="teacher"?"Кабинет преподавателя":"Личный кабинет студента"}</h1><p><strong>{u.displayName}</strong> · {u.role==="teacher"?"преподаватель":"студент"}</p>
{u.role==="student"?<><h2>Мой прогресс</h2><p>Посещено модулей: <strong>{p?.visitedModules.length??0} / {modules.RU.length}</strong></p><p>Ваши текущие данные обучения пока сохраняются в этом браузере; серверная синхронизация группы будет подключена отдельным хранилищем.</p><Link href="/modules/1/progress?lang=RU">Прогресс и оценивание →</Link><br/><Link href="/exam?lang=RU">Экзаменационный центр →</Link></>:<><h2>Панель преподавателя</h2><p>Доступ защищён ролью преподавателя. Здесь будет сводка групп после подключения серверного хранилища результатов.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}}>{["Группы и студенты","Прогресс 25 модулей","Экзаменационные попытки","Слабые темы и механизмы"].map(x=><div key={x} style={{padding:16,border:"1px solid #dce8ef",borderRadius:12,background:"#fff"}}><strong>{x}</strong><p style={{fontSize:14}}>Ожидает серверных данных группы.</p></div>)}</div></>}
<p style={{marginTop:28}}><Link href="/">К учебнику</Link></p><button onClick={logout}>Выйти</button></main>}